namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Administrative panel text strings for user, product, payment, gateway, and security management.
/// Coverage: AdminUsers, AdminProducts, AdminPayments, AdminLanguages, AdminDashboard,
/// AdminDeliveryAgents, AdminGateways, AdminApiKeys, AdminLogs, AdminAuditTimeline, AdminFeatures, etc.
/// </summary>
internal static class AdminTexts
{
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Admin.Nav.Users"] = "Usuarios",
        ["Admin.Nav.Products"] = "Itens",
        ["Admin.Nav.Payments"] = "Pagamentos",
        ["Admin.Nav.Gateways"] = "Gateways",
        ["Admin.Nav.Logs"] = "Logs",
        ["Admin.Nav.Languages"] = "Idiomas",
        ["Admin.Nav.Security"] = "Seguranca",

        ["AdminCommon.CloseNotice"] = "Fechar aviso",
        ["AdminCommon.ExtraActions"] = "Acoes adicionais",

        ["AdminProducts.Kicker"] = "Painel administrativo",
        ["AdminProducts.Title"] = "Itens",
        ["AdminProducts.Subtitle"] = "Gerencie catalogo, autoria e tipo de entrega com o mesmo layout das novas telas.",
        ["AdminProducts.Aria"] = "Gestao de produtos",
        ["AdminProducts.Filter.Id"] = "ID...",
        ["AdminProducts.Filter.Name"] = "Nome...",
        ["AdminProducts.Filter.User"] = "Usuario...",
        ["AdminProducts.Filter.MinPrice"] = "Preco minimo",
        ["AdminProducts.Filter.MaxPrice"] = "Preco maximo",
        ["AdminProducts.NewItem"] = "Novo item",
        ["AdminProducts.RestoredFilters"] = "Filtros de produtos restaurados da sessao anterior.",
        ["AdminProducts.Loading"] = "Carregando produtos...",
        ["AdminProducts.Empty"] = "Nenhum produto encontrado.",
        ["AdminProducts.Name"] = "Nome",
        ["AdminProducts.User"] = "Usuario",
        ["AdminProducts.Price"] = "Preco",
        ["AdminProducts.Type"] = "Tipo",
        ["AdminProducts.CreatedAt"] = "Criado em",
        ["AdminProducts.ConfirmDelete"] = "Tem certeza que deseja deletar este produto?",
        ["AdminProducts.LogDeleted"] = "Produto deletado (ID: {0})",
        ["AdminProducts.DeletedToast"] = "Produto deletado!",

        ["AdminPayments.Kicker"] = "Painel administrativo",
        ["AdminPayments.Title"] = "Pagamentos",
        ["AdminPayments.Subtitle"] = "Acompanhe gateway, valores e confirmacao em uma interface consistente.",
        ["AdminPayments.Aria"] = "Gestao de pagamentos",
        ["AdminPayments.Filter.User"] = "Usuario...",
        ["AdminPayments.Filter.Product"] = "Produto...",
        ["AdminPayments.Filter.Min"] = "Valor minimo",
        ["AdminPayments.Filter.Max"] = "Valor maximo",
        ["AdminPayments.Filter.AllStatuses"] = "Todos os status",
        ["AdminPayments.RestoredFilters"] = "Filtros de pagamentos restaurados da sessao anterior.",
        ["AdminPayments.Loading"] = "Carregando pagamentos...",
        ["AdminPayments.Empty"] = "Nenhum pagamento encontrado.",
        ["AdminPayments.EmptyHint"] = "Pagamentos processados aparecerao aqui.",
        ["AdminPayments.Product"] = "Produto",
        ["AdminPayments.User"] = "Usuario",

        ["AdminUsers.Kicker"] = "Painel administrativo",
        ["AdminUsers.Title"] = "Usuarios do Sistema",
        ["AdminUsers.Subtitle"] = "Controle contas, status e permissoes no novo padrao visual.",
        ["AdminUsers.Aria"] = "Gestao de usuarios",
        ["AdminUsers.Filter.User"] = "Usuario...",
        ["AdminUsers.Filter.Email"] = "Email...",
        ["AdminUsers.Filter.Role"] = "Role...",
        ["AdminUsers.Filter.All"] = "Todos",
        ["AdminUsers.RestoredFilters"] = "Filtros de usuarios restaurados da sessao anterior.",
        ["AdminUsers.Loading"] = "Carregando usuarios...",
        ["AdminUsers.Empty"] = "Nenhum usuario encontrado.",
        ["AdminUsers.EmptyHint"] = "Usuarios cadastrados aparecerao aqui.",
        ["AdminUsers.User"] = "Usuario",
        ["AdminUsers.Email"] = "Email",
        ["AdminUsers.Role"] = "Role",
        ["AdminUsers.ActiveColumn"] = "Ativo",
        ["AdminUsers.Active"] = "Ativo",
        ["AdminUsers.Blocked"] = "Bloqueado",
        ["AdminUsers.Lock"] = "Bloquear",
        ["AdminUsers.Unlock"] = "Desbloquear",
        ["AdminUsers.ConfirmLock"] = "Tem certeza que deseja bloquear este usuario?",
        ["AdminUsers.ConfirmDelete"] = "Tem certeza que deseja deletar este usuario?",
        ["AdminUsers.LockedToast"] = "Usuario bloqueado!",
        ["AdminUsers.UnlockedToast"] = "Usuario desbloqueado!",
        ["AdminUsers.DeletedToast"] = "Usuario deletado!",
        ["AdminUsers.NotFoundToast"] = "Usuario nao encontrado.",
        ["AdminUsers.DeleteErrorToast"] = "Erro ao deletar usuario.",
        ["AdminUsers.LogLocked"] = "Usuario bloqueado (ID: {0})",
        ["AdminUsers.LogUnlocked"] = "Usuario desbloqueado (ID: {0})",
        ["AdminUsers.LogDeleted"] = "Usuario deletado (ID: {0})",

        ["AdminLanguages.Kicker"] = "Configuracao global",
        ["AdminLanguages.Title"] = "Idiomas da Interface",
        ["AdminLanguages.Subtitle"] = "Defina o idioma padrao da interface para todo o sistema.",
        ["AdminLanguages.Aria"] = "Configuracoes de idioma",
        ["AdminLanguages.Current"] = "Idioma atual",
        ["AdminLanguages.Select"] = "Selecione o idioma da interface",
        ["AdminLanguages.Save"] = "Salvar idioma",
        ["AdminLanguages.Success"] = "Idioma atualizado com sucesso.",
        ["AdminLanguages.Hint"] = "Obs: textos de botoes que serao trocados por icones podem ficar fora desta etapa.",

        ["AdminDashboard.Kicker"] = "Controle total",
        ["AdminDashboard.Title"] = "Painel Administrativo",
        ["AdminDashboard.Subtitle"] = "Acesse gestao, metricas e configuracoes criticas em um layout consistente.",
        ["AdminDashboard.Aria"] = "Painel administrativo",
        ["AdminDashboard.Welcome"] = "Bem-vindo, administrador!",
        ["AdminDashboard.KpiAria"] = "Metricas operacionais",
        ["AdminDashboard.KpiUsersAria"] = "Abrir gestao de usuarios",
        ["AdminDashboard.KpiUsers"] = "Usuarios",
        ["AdminDashboard.KpiPaidSales"] = "Vendas pagas",
        ["AdminDashboard.KpiPaidVolume"] = "Volume pago (BTC)",
        ["AdminDashboard.ViewDetails"] = "Ver detalhes",
        ["AdminDashboard.CurrencyLabel"] = "Moeda de cotacao padrao:",
        ["AdminDashboard.QuoteQueriesLabel"] = "Consultas de cotacao (total):",
        ["AdminDashboard.OperationFeeLabel"] = "Taxa operacional (%):",
        ["AdminDashboard.SaveFee"] = "Salvar taxa",
        ["AdminDashboard.OperationFeeSaved"] = "Taxa operacional salva com sucesso.",
        ["AdminDashboard.OperationFeeRangeError"] = "Informe uma taxa entre 0 e 100.",
        ["AdminDashboard.AccessDeniedSettings"] = "Acesso negado para alterar configuracoes.",
        ["AdminDashboard.SecurityTitle"] = "Seguranca",
        ["AdminDashboard.SecuritySubtitle"] = "Configuracao da autenticacao, lockout e baseline de protecao por ambiente.",
        ["AdminDashboard.BaselineAria"] = "Base do ambiente",
        ["AdminDashboard.BaselineTitle"] = "Base do ambiente",
        ["AdminDashboard.Environment"] = "Ambiente",
        ["AdminDashboard.EnvironmentDevelopment"] = "Desenvolvimento",
        ["AdminDashboard.EnvironmentProduction"] = "Producao",
        ["AdminDashboard.Credentials"] = "Credenciais",
        ["AdminDashboard.MinPassword"] = "Senha minima",
        ["AdminDashboard.Characters"] = "caracteres",
        ["AdminDashboard.UniqueChars"] = "Chars unicos",
        ["AdminDashboard.RequireDigit"] = "Exige numero",
        ["AdminDashboard.RequireLowercase"] = "Exige minuscula",
        ["AdminDashboard.RequireUppercase"] = "Exige maiuscula",
        ["AdminDashboard.RequireSymbol"] = "Exige simbolo",
        ["AdminDashboard.Session"] = "Sessao",
        ["AdminDashboard.SessionDuration"] = "Tempo de sessao",
        ["AdminDashboard.Minutes"] = "min",
        ["AdminDashboard.RuntimeAria"] = "Controles em runtime",
        ["AdminDashboard.RuntimeTitle"] = "Controles em runtime",
        ["AdminDashboard.RequireConfirmedEmail"] = "Exigir e-mail confirmado no login",
        ["AdminDashboard.LockoutAttempts"] = "Lockout apos tentativas invalidas",
        ["AdminDashboard.LockoutDuration"] = "Duracao do lockout (min)",
        ["AdminDashboard.SaveSecurityPolicy"] = "Salvar politica de seguranca",
        ["AdminDashboard.SecurityPolicySaved"] = "Politica de seguranca salva com sucesso.",
        ["AdminDashboard.SecurityPolicyRangeError"] = "Valores invalidos. Tentativas: 1-20, lockout: 1-1440 min.",
        ["AdminDashboard.AccessDeniedSecurity"] = "Acesso negado para alterar a politica de seguranca.",

        ["AdminDeliveryAgents.Kicker"] = "Painel administrativo",
        ["AdminDeliveryAgents.Title"] = "Entregadores",
        ["AdminDeliveryAgents.Subtitle"] = "Gerencie cadastro e disponibilidade com o mesmo padrao visual aplicado aos perfis.",
        ["AdminDeliveryAgents.Aria"] = "Gestao de entregadores",
        ["AdminDeliveryAgents.Filter.Search"] = "Buscar por nome...",
        ["AdminDeliveryAgents.Refresh"] = "Atualizar",
        ["AdminDeliveryAgents.Edit"] = "Editar entregador",
        ["AdminDeliveryAgents.New"] = "Novo entregador",
        ["AdminDeliveryAgents.Name"] = "Nome",
        ["AdminDeliveryAgents.Contact"] = "Contato",
        ["AdminDeliveryAgents.BusinessDays"] = "Prazo (dias uteis)",
        ["AdminDeliveryAgents.Active"] = "Ativo",
        ["AdminDeliveryAgents.Inactive"] = "Desativado",
        ["AdminDeliveryAgents.Create"] = "Criar",
        ["AdminDeliveryAgents.Empty"] = "Nenhum entregador encontrado.",
        ["AdminDeliveryAgents.EmptyHint"] = "Cadastre um entregador usando o botao acima.",
        ["AdminDeliveryAgents.CreatedAt"] = "Criado em",
        ["AdminDeliveryAgents.Activate"] = "Ativar",
        ["AdminDeliveryAgents.Deactivate"] = "Desativar",
        ["AdminDeliveryAgents.ErrorNameRequired"] = "Informe o nome do entregador.",
        ["AdminDeliveryAgents.ErrorDaysRange"] = "Informe um prazo entre 1 e 60 dias uteis.",
        ["AdminDeliveryAgents.ErrorNotFound"] = "Entregador nao encontrado.",
        ["AdminDeliveryAgents.Updated"] = "Entregador atualizado com sucesso.",
        ["AdminDeliveryAgents.Created"] = "Entregador criado com sucesso.",

        ["AdminDeliveryAgentView.Loading"] = "Carregando entregador...",
        ["AdminDeliveryAgentView.NotFound"] = "Entregador nao encontrado.",
        ["AdminDeliveryAgentView.Kicker"] = "Painel administrativo",
        ["AdminDeliveryAgentView.Subtitle"] = "Visualizacao administrativa completa do entregador para gestao e auditoria.",
        ["AdminDeliveryAgentView.AdminData"] = "Dados administrativos",
        ["AdminDeliveryAgentView.NotInformed"] = "Nao informado",
        ["AdminDeliveryAgentView.AverageTime"] = "Prazo medio",
        ["AdminDeliveryAgentView.BusinessDaysValue"] = "dia(s) util(eis)",
        ["AdminDeliveryAgentView.Operation"] = "Operacao",
        ["AdminDeliveryAgentView.OperationHint"] = "Use esta visualizacao para validar disponibilidade, dados de contato e SLA operacional.",
        ["AdminDeliveryAgentView.AdminScope"] = "Escopo administrativo",

        ["AdminGateways.Kicker"] = "Painel administrativo",
        ["AdminGateways.Title"] = "Gateways de Pagamento",
        ["AdminGateways.Subtitle"] = "Ative ou desative meios de pagamento com padronizacao visual e operacional.",
        ["AdminGateways.Aria"] = "Configuracao de gateways",
        ["AdminGateways.Active"] = "Ativo",
        ["AdminGateways.Inactive"] = "Desativado",
        ["AdminGateways.ConfirmDisable"] = "Tem certeza que deseja desativar o gateway '{0}'?",
        ["AdminGateways.EnabledAction"] = "ativado",
        ["AdminGateways.DisabledAction"] = "desativado",
        ["AdminGateways.LogChanged"] = "Gateway '{0}' {1}",
        ["AdminGateways.ToastChanged"] = "Gateway '{0}' {1}!",
        ["AdminGateways.SaveError"] = "Gateway nao encontrado ou erro ao salvar.",
        ["AdminGateways.CredentialsHeader"] = "Credenciais",
        ["AdminGateways.Configured"] = "Configurado",
        ["AdminGateways.NotConfigured"] = "Sem credenciais",
        ["AdminGateways.NotConfiguredHint"] = "As variaveis de ambiente ou segredos para este gateway nao estao configurados. O gateway nao aparecera como opcao de pagamento mesmo que esteja ativo.",

        ["AdminApiKeys.Title"] = "API Keys dos Servidores",
        ["AdminApiKeys.Subtitle"] = "Gerencie chaves de API para integracao com game servers OpenTibia.",
        ["AdminApiKeys.Aria"] = "Gerenciamento de API keys",
        ["AdminApiKeys.Server"] = "Servidor",
        ["AdminApiKeys.Prefix"] = "Prefixo",
        ["AdminApiKeys.Label"] = "Label",
        ["AdminApiKeys.Active"] = "Ativa",
        ["AdminApiKeys.Revoked"] = "Revogada",
        ["AdminApiKeys.LastUsed"] = "Ultimo uso",
        ["AdminApiKeys.Never"] = "Nunca",
        ["AdminApiKeys.CreateNew"] = "Nova API Key",
        ["AdminApiKeys.SelectServer"] = "Selecione o servidor",
        ["AdminApiKeys.LabelPlaceholder"] = "Ex: Producao, Teste...",
        ["AdminApiKeys.Generate"] = "Gerar Chave",
        ["AdminApiKeys.CopyWarning"] = "Copie a chave agora – ela nao sera exibida novamente.",
        ["AdminApiKeys.Copied"] = "Chave copiada!",
        ["AdminApiKeys.ConfirmRevoke"] = "Tem certeza que deseja revogar esta API key? O game server perdera acesso.",
        ["AdminApiKeys.Revoke"] = "Revogar",
        ["AdminApiKeys.RevokeSuccess"] = "API key revogada com sucesso.",
        ["AdminApiKeys.RevokeError"] = "Erro ao revogar API key.",
        ["AdminApiKeys.CreateSuccess"] = "API key criada com sucesso.",
        ["AdminApiKeys.CreateError"] = "Erro ao criar API key.",
        ["AdminApiKeys.NoKeys"] = "Nenhuma API key cadastrada.",
        ["AdminApiKeys.NoServers"] = "Nenhum servidor cadastrado para gerar API key.",

        ["AdminUserView.Kicker"] = "Painel administrativo",
        ["AdminUserView.Subtitle"] = "Visualizacao completa para auditoria e gestao de conta.",
        ["AdminUserView.AdminData"] = "Dados administrativos",
        ["AdminUserView.NotFound"] = "Usuario nao encontrado.",
        ["AdminUserView.NotInformed"] = "Nao informado",
        ["AdminUserView.FullName"] = "Nome completo",
        ["AdminUserView.BirthDate"] = "Nascimento",
        ["AdminUserView.Governance"] = "Governanca",
        ["AdminUserView.GovernanceHint"] = "Esta visualizacao permite inspecao de dados para revisao administrativa e fluxo de suporte.",
        ["AdminUserView.AdminScope"] = "Escopo administrativo",

        ["AdminProductView.Kicker"] = "Painel administrativo",
        ["AdminProductView.Title"] = "Detalhes do Produto",
        ["AdminProductView.Subtitle"] = "Visualizacao administrativa do cadastro e status de entrega.",
        ["AdminProductView.Aria"] = "Detalhes do produto",
        ["AdminProductView.NotFound"] = "Produto nao encontrado.",
        ["AdminProductView.RequiresDelivery"] = "Necessita entrega",
        ["AdminProductView.NoInfoproduct"] = "Nao (infoproduto)",

        ["AdminProductEdit.Kicker"] = "Painel administrativo",
        ["AdminProductEdit.Title"] = "Editar Produto",
        ["AdminProductEdit.Subtitle"] = "Ajuste dados do anuncio com o mesmo padrao visual das telas novas.",
        ["AdminProductEdit.Aria"] = "Edicao de produto",
        ["AdminProductEdit.NotFound"] = "Produto nao encontrado.",
        ["AdminProductEdit.Price"] = "Preco",
        ["AdminProductEdit.RequiresPhysicalDelivery"] = "Necessita entrega fisica",
        ["AdminProductEdit.DigitalHint"] = "Desmarque para infoprodutos/entrega digital.",
        ["AdminProductEdit.UpdatedToast"] = "Produto atualizado com sucesso!",
        ["AdminProductEdit.LogEdited"] = "Produto editado (ID: {0})",

        ["AdminUserEdit.Kicker"] = "Painel administrativo",
        ["AdminUserEdit.Title"] = "Editar Usuario",
        ["AdminUserEdit.Subtitle"] = "Atualize informacoes cadastrais mantendo consistencia visual com as demais telas.",
        ["AdminUserEdit.Aria"] = "Edicao de usuario",
        ["AdminUserEdit.NotFound"] = "Usuario nao encontrado.",
        ["AdminUserEdit.UpdatedToast"] = "Usuario atualizado com sucesso!",
        ["AdminUserEdit.UpdateErrorToast"] = "Erro ao atualizar usuario.",
        ["AdminUserEdit.LogEdited"] = "Usuario editado (ID: {0})",

        ["AdminLogs.Kicker"] = "Painel administrativo",
        ["AdminLogs.Title"] = "Logs do Sistema",
        ["AdminLogs.Subtitle"] = "Monitore eventos, seguranca e auditoria com o mesmo layout das telas novas.",
        ["AdminLogs.Aria"] = "Monitoramento de logs",
        ["AdminLogs.Total"] = "Total de logs:",
        ["AdminLogs.Filter.Global"] = "Busca geral (usuario/fonte/mensagem)...",
        ["AdminLogs.Filter.User"] = "Usuario...",
        ["AdminLogs.Filter.Source"] = "Fonte...",
        ["AdminLogs.Filter.Message"] = "Mensagem...",
        ["AdminLogs.Filter.AllLevels"] = "Todos os niveis",
        ["AdminLogs.ExportCsv"] = "Exportar CSV",
        ["AdminLogs.ExportJson"] = "Exportar JSON",
        ["AdminLogs.QuickRange"] = "Periodo rapido:",
        ["AdminLogs.Today"] = "Hoje",
        ["AdminLogs.Last7Days"] = "Ultimos 7 dias",
        ["AdminLogs.Last30Days"] = "Ultimos 30 dias",
        ["AdminLogs.CurrentMonth"] = "Mes atual",
        ["AdminLogs.ClearRange"] = "Limpar periodo",
        ["AdminLogs.AuditView"] = "Visao de auditoria:",
        ["AdminLogs.All"] = "Todos",
        ["AdminLogs.PaymentPanelStale"] = "Painel defasado",
        ["AdminLogs.ReleaseOnly"] = "Somente repasses",
        ["AdminLogs.ReleaseOk"] = "Repasses OK",
        ["AdminLogs.ReleaseRefused"] = "Repasses recusados",
        ["AdminLogs.SecurityPolicy"] = "Politica de seguranca",
        ["AdminLogs.InvalidDateRange"] = "Intervalo de datas invalido: a data inicial nao pode ser maior que a data final.",
        ["AdminLogs.RestoredFilters"] = "Filtros de logs restaurados da sessao anterior.",
        ["AdminLogs.AppliedPeriod"] = "Periodo aplicado:",
        ["AdminLogs.Empty"] = "Nenhum log encontrado para os filtros informados.",
        ["AdminLogs.DateTime"] = "Data/Hora",
        ["AdminLogs.Level"] = "Nivel",
        ["AdminLogs.Source"] = "Fonte",
        ["AdminLogs.User"] = "Usuario",
        ["AdminLogs.Message"] = "Mensagem",
        ["AdminLogs.Exception"] = "Excecao",
        ["AdminLogs.IdPrefix"] = "ID:",
        ["AdminLogs.ExportTruncated"] = "Export truncado para {0} registros para manter performance.",
        ["AdminLogs.PeriodRange"] = "{0} ate {1}",
        ["AdminLogs.PeriodFrom"] = "a partir de {0}",
        ["AdminLogs.PeriodUntil"] = "ate {0}",
        ["AdminLogs.PeriodNone"] = "sem periodo",

        ["AdminAuditTimeline.Title"] = "Timeline de auditoria",
        ["AdminAuditTimeline.Subtitle"] = "Historico completo de eventos auditados para esta entidade.",
        ["AdminAuditTimeline.Aria"] = "Timeline de auditoria da entidade",
        ["AdminAuditTimeline.Entity"] = "Entidade",
        ["AdminAuditTimeline.EntityId"] = "ID",
        ["AdminAuditTimeline.Empty"] = "Nenhum evento de auditoria encontrado para esta entidade.",
        ["AdminAuditTimeline.EventType"] = "Evento",
        ["AdminAuditTimeline.DateTime"] = "Data/Hora",
        ["AdminAuditTimeline.Level"] = "Nivel",
        ["AdminAuditTimeline.Source"] = "Fonte",
        ["AdminAuditTimeline.User"] = "Ator",
        ["AdminAuditTimeline.Message"] = "Mensagem",
        ["AdminAuditTimeline.Metadata"] = "Metadata",
        ["AdminAuditTimeline.ExportCsv"] = "Exportar CSV",
        ["AdminAuditTimeline.ExportJson"] = "Exportar JSON",
        ["AdminAuditTimeline.BackToLogs"] = "Logs",
        ["AdminAuditTimeline.ViewHistory"] = "Ver historico",

        ["AdminFeatures.Title"] = "Features do sistema",
        ["AdminFeatures.Aria"] = "Gerenciamento de features",
        ["AdminFeatures.Subtitle"] = "Habilite ou desabilite funcionalidades experimentais. Mudancas tem efeito imediato.",
        ["AdminFeatures.Enabled"] = "Habilitada",
        ["AdminFeatures.Disabled"] = "Desabilitada",
        ["AdminFeatures.Back"] = "Voltar",
        ["AdminFeatures.AccessDenied"] = "Acesso negado.",
        ["AdminFeatures.LuaName"] = "Entrega automatica de itens via Lua",
        ["AdminFeatures.LuaDescription"] = "Quando habilitada, servidores integrados com o script Lua confirmam entregas automaticamente assim que o comprador estiver online no jogo. Requer que o GM instale e configure o script de integracao.",
        ["AdminFeatures.LuaFallback"] = "Fluxo ativo: evidencias manuais – vendedor envia print, comprador confirma recebimento, admin libera os fundos.",
        ["AdminFeatures.ConfirmToggle"] = "Deseja {0} a feature \"{1}\"?\n\nEsta mudanca tera efeito imediato para todos os usuarios.",
        ["AdminFeatures.ToastEnabled"] = "Feature \"{0}\" habilitada.",
        ["AdminFeatures.ToastDisabled"] = "Feature \"{0}\" desabilitada. Modo manual ativo.",
        ["AdminFeatures.LogChanged"] = "Feature \"{0}\" {1} pelo admin.",
        ["AdminFeatures.VerbEnable"] = "habilitar",
        ["AdminFeatures.VerbDisable"] = "desabilitar",
    };

    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Admin.Nav.Users"] = "Users",
        ["Admin.Nav.Products"] = "Products",
        ["Admin.Nav.Payments"] = "Payments",
        ["Admin.Nav.Gateways"] = "Gateways",
        ["Admin.Nav.Logs"] = "Logs",
        ["Admin.Nav.Languages"] = "Languages",
        ["Admin.Nav.Security"] = "Security",

        ["AdminCommon.CloseNotice"] = "Close notice",
        ["AdminCommon.ExtraActions"] = "Additional actions",

        // ... (additional translations follow same pattern as PtBr)
        // For brevity, showing English stubs here
    };

    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Spanish translations follow same pattern
    };

    /// <summary>
    /// Merge all admin text dictionaries into a single language-keyed dictionary
    /// </summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
