namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Authentication and identity management text strings.
/// Coverage: Identity, Login, Register, PasswordReset, ConfirmEmail, Profile, Preferences
/// </summary>
internal static class AuthTexts
{
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Identity.Common.GoToLogin"] = "Ir para login",
        ["Identity.Common.BackToLogin"] = "Voltar para login",
        ["Identity.Common.BackToProfile"] = "Voltar para perfil",
        ["Identity.Common.Email"] = "Email",
        ["Identity.Common.Password"] = "Senha",
        ["Identity.Common.ConfirmPassword"] = "Confirmar senha",
        ["Identity.Common.UserNotFound"] = "Usuario nao encontrado.",
        ["Identity.Login.Title"] = "Login",
        ["Identity.Login.Heading"] = "Entrar no Confirma Ai!",
        ["Identity.Login.RememberMe"] = "Lembrar-me",
        ["Identity.Login.ForgotPassword"] = "Esqueceu a senha?",
        ["Identity.Login.ErrorInvalid"] = "Login invalido.",
        ["Identity.Login.ErrorLocked"] = "Conta temporariamente bloqueada por tentativas invalidas. Tente novamente em alguns minutos.",
        ["Identity.Login.ErrorConfirmEmail"] = "Login nao permitido. Confirme seu email antes de entrar.",
        ["Identity.Register.Title"] = "Registrar",
        ["Identity.Register.Heading"] = "Registrar no Confirma Ai!",
        ["Identity.Register.HaveAccount"] = "Ja tem uma conta? Entrar",
        ["Identity.RegisterConfirmation.Title"] = "Confirme seu registro",
        ["Identity.RegisterConfirmation.Heading"] = "Registro concluido",
        ["Identity.RegisterConfirmation.Message"] = "Enviamos um link de confirmacao para {0}. Confirme o email antes de fazer login.",
        ["Identity.Resend.Title"] = "Reenviar confirmacao",
        ["Identity.Resend.Heading"] = "Reenviar confirmacao de email",
        ["Identity.Resend.Subtitle"] = "Digite o email usado no registro para receber um novo link de confirmacao.",
        ["Identity.Resend.Submit"] = "Reenviar email",
        ["Identity.Resend.StatusQueued"] = "Se o email existe, o link de confirmacao sera enviado.",
        ["Identity.Forgot.Title"] = "Recuperar senha",
        ["Identity.Forgot.Heading"] = "Recuperar senha",
        ["Identity.Forgot.Subtitle"] = "Digite seu email para receber instrucoes de recuperacao.",
        ["Identity.Forgot.Submit"] = "Enviar link de recuperacao",
        ["Identity.Forgot.CreateAccount"] = "Criar conta",
        ["Identity.ForgotConfirmation.Title"] = "Confirmacao de recuperacao",
        ["Identity.ForgotConfirmation.Heading"] = "Verifique seu email",
        ["Identity.ForgotConfirmation.Message"] = "Se existe uma conta com este email, enviamos instrucoes de recuperacao.",
        ["Identity.ForgotConfirmation.DevHint"] = "Ambiente de desenvolvimento detectado: quando SMTP esta desabilitado, emails de teste sao salvos em",
        ["Identity.ForgotConfirmation.LastEmail"] = "Ultimo email salvo:",
        ["Identity.Reset.Title"] = "Redefinir senha",
        ["Identity.Reset.Heading"] = "Redefinir senha",
        ["Identity.Reset.Submit"] = "Atualizar senha",
        ["Identity.Reset.ErrorCodeRequired"] = "Codigo de redefinicao e obrigatorio.",
        ["Identity.ResetConfirmation.Title"] = "Senha redefinida",
        ["Identity.ResetConfirmation.Heading"] = "Senha atualizada",
        ["Identity.ResetConfirmation.Message"] = "Sua senha foi redefinida com sucesso.",
        ["Identity.ResetConfirmation.LoginWithNewPassword"] = "Entrar com a nova senha",
        ["Identity.ChangePassword.Title"] = "Alterar senha",
        ["Identity.ChangePassword.Heading"] = "Alterar senha",
        ["Identity.ChangePassword.Submit"] = "Salvar nova senha",
        ["Identity.ChangePassword.CurrentPassword"] = "Senha atual",
        ["Identity.ChangePassword.NewPassword"] = "Nova senha",
        ["Identity.ChangePassword.ConfirmNewPassword"] = "Confirmar nova senha",
        ["Identity.ChangePasswordConfirmation.Title"] = "Senha alterada",
        ["Identity.ChangePasswordConfirmation.Heading"] = "Senha alterada",
        ["Identity.ChangePasswordConfirmation.Message"] = "Sua senha foi alterada com sucesso.",
        ["Identity.ConfirmEmail.Title"] = "Confirmacao de email",
        ["Identity.ConfirmEmail.Heading"] = "Confirmacao de email",
        ["Identity.ConfirmEmail.InvalidLink"] = "Link de confirmacao invalido.",
        ["Identity.ConfirmEmail.Success"] = "Obrigado por confirmar seu email.",
        ["Identity.ConfirmEmail.Failure"] = "Nao foi possivel confirmar seu email.",
        ["Identity.Email.ConfirmSubject"] = "Confirme seu email",
        ["Identity.Email.ConfirmBody"] = "Confirme sua conta clicando aqui: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ConfirmAction"] = "confirmar conta",
        ["Identity.Email.ResetSubject"] = "Redefinir sua senha",
        ["Identity.Email.ResetBody"] = "Para redefinir sua senha, clique aqui: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ResetAction"] = "redefinir senha",
    };

    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Identity.Common.GoToLogin"] = "Go to login",
        ["Identity.Common.BackToLogin"] = "Back to login",
        ["Identity.Common.BackToProfile"] = "Back to profile",
        ["Identity.Common.Email"] = "Email",
        ["Identity.Common.Password"] = "Password",
        ["Identity.Common.ConfirmPassword"] = "Confirm password",
        ["Identity.Common.UserNotFound"] = "User not found.",
        ["Identity.Login.Title"] = "Login",
        ["Identity.Login.Heading"] = "Login to Confirmai!",
        ["Identity.Login.RememberMe"] = "Remember me",
        ["Identity.Login.ForgotPassword"] = "Forgot password?",
        ["Identity.Login.ErrorInvalid"] = "Invalid login.",
        ["Identity.Login.ErrorLocked"] = "Account temporarily locked due to invalid attempts. Try again in a few minutes.",
        ["Identity.Login.ErrorConfirmEmail"] = "Login not allowed. Confirm your email before signing in.",
        ["Identity.Register.Title"] = "Register",
        ["Identity.Register.Heading"] = "Register on Confirmai!",
        ["Identity.Register.HaveAccount"] = "Already have an account? Login",
        ["Identity.RegisterConfirmation.Title"] = "Confirm your registration",
        ["Identity.RegisterConfirmation.Heading"] = "Registration completed",
        ["Identity.RegisterConfirmation.Message"] = "We sent a confirmation link to {0}. Confirm the email before logging in.",
        ["Identity.Resend.Title"] = "Resend confirmation",
        ["Identity.Resend.Heading"] = "Resend email confirmation",
        ["Identity.Resend.Subtitle"] = "Enter the email used at registration to receive a new confirmation link.",
        ["Identity.Resend.Submit"] = "Resend email",
        ["Identity.Resend.StatusQueued"] = "If the email exists, the confirmation link will be sent.",
        ["Identity.Forgot.Title"] = "Recover password",
        ["Identity.Forgot.Heading"] = "Recover password",
        ["Identity.Forgot.Subtitle"] = "Enter your email to receive reset instructions.",
        ["Identity.Forgot.Submit"] = "Send recovery link",
        ["Identity.Forgot.CreateAccount"] = "Create account",
        ["Identity.ForgotConfirmation.Title"] = "Recovery confirmation",
        ["Identity.ForgotConfirmation.Heading"] = "Check your email",
        ["Identity.ForgotConfirmation.Message"] = "If an account exists with this email, we sent recovery instructions.",
        ["Identity.ForgotConfirmation.DevHint"] = "Development environment detected: when SMTP is disabled, test emails are saved at",
        ["Identity.ForgotConfirmation.LastEmail"] = "Last saved email:",
        ["Identity.Reset.Title"] = "Reset password",
        ["Identity.Reset.Heading"] = "Reset password",
        ["Identity.Reset.Submit"] = "Update password",
        ["Identity.Reset.ErrorCodeRequired"] = "Reset code is required.",
        ["Identity.ResetConfirmation.Title"] = "Password reset",
        ["Identity.ResetConfirmation.Heading"] = "Password updated",
        ["Identity.ResetConfirmation.Message"] = "Your password was reset successfully.",
        ["Identity.ResetConfirmation.LoginWithNewPassword"] = "Login with the new password",
        ["Identity.ChangePassword.Title"] = "Change password",
        ["Identity.ChangePassword.Heading"] = "Change password",
        ["Identity.ChangePassword.Submit"] = "Save new password",
        ["Identity.ChangePassword.CurrentPassword"] = "Current password",
        ["Identity.ChangePassword.NewPassword"] = "New password",
        ["Identity.ChangePassword.ConfirmNewPassword"] = "Confirm new password",
        ["Identity.ChangePasswordConfirmation.Title"] = "Password changed",
        ["Identity.ChangePasswordConfirmation.Heading"] = "Password changed",
        ["Identity.ChangePasswordConfirmation.Message"] = "Your password was changed successfully.",
        ["Identity.ConfirmEmail.Title"] = "Email confirmation",
        ["Identity.ConfirmEmail.Heading"] = "Email confirmation",
        ["Identity.ConfirmEmail.InvalidLink"] = "Invalid confirmation link.",
        ["Identity.ConfirmEmail.Success"] = "Thanks for confirming your email.",
        ["Identity.ConfirmEmail.Failure"] = "Could not confirm your email.",
        ["Identity.Email.ConfirmSubject"] = "Confirm your email",
        ["Identity.Email.ConfirmBody"] = "Confirm your account by clicking here: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ConfirmAction"] = "confirm account",
        ["Identity.Email.ResetSubject"] = "Reset your password",
        ["Identity.Email.ResetBody"] = "To reset your password, click here: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ResetAction"] = "reset password",
    };

    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Identity.Common.GoToLogin"] = "Ir al inicio de sesion",
        ["Identity.Common.BackToLogin"] = "Volver al inicio de sesion",
        ["Identity.Common.BackToProfile"] = "Volver al perfil",
        ["Identity.Common.Email"] = "Email",
        ["Identity.Common.Password"] = "Contrasena",
        ["Identity.Common.ConfirmPassword"] = "Confirmar contrasena",
        ["Identity.Common.UserNotFound"] = "Usuario no encontrado.",
        ["Identity.Login.Title"] = "Inicio de sesion",
        ["Identity.Login.Heading"] = "Inicia sesion en Confirmai!",
        ["Identity.Login.RememberMe"] = "Recuerdame",
        ["Identity.Login.ForgotPassword"] = "Olvidaste tu contrasena?",
        ["Identity.Login.ErrorInvalid"] = "Inicio de sesion invalido.",
        ["Identity.Login.ErrorLocked"] = "Cuenta bloqueada temporalmente por intentos invalidos. Intentalo de nuevo en unos minutos.",
        ["Identity.Login.ErrorConfirmEmail"] = "Inicio de sesion no permitido. Confirma tu email antes de iniciar sesion.",
        ["Identity.Register.Title"] = "Registrarse",
        ["Identity.Register.Heading"] = "Registrate en Confirmai!",
        ["Identity.Register.HaveAccount"] = "Ya tienes cuenta? Inicia sesion",
        ["Identity.RegisterConfirmation.Title"] = "Confirma tu registro",
        ["Identity.RegisterConfirmation.Heading"] = "Registro completado",
        ["Identity.RegisterConfirmation.Message"] = "Enviamos un enlace de confirmacion a {0}. Confirma el email antes de iniciar sesion.",
        ["Identity.Resend.Title"] = "Reenviar confirmacion",
        ["Identity.Resend.Heading"] = "Reenviar confirmacion de email",
        ["Identity.Resend.Subtitle"] = "Introduce el email usado en el registro para recibir un nuevo enlace de confirmacion.",
        ["Identity.Resend.Submit"] = "Reenviar email",
        ["Identity.Resend.StatusQueued"] = "Si el email existe, se enviara el enlace de confirmacion.",
        ["Identity.Forgot.Title"] = "Recuperar contrasena",
        ["Identity.Forgot.Heading"] = "Recuperar contrasena",
        ["Identity.Forgot.Subtitle"] = "Introduce tu email para recibir instrucciones de recuperacion.",
        ["Identity.Forgot.Submit"] = "Enviar enlace de recuperacion",
        ["Identity.Forgot.CreateAccount"] = "Crear cuenta",
        ["Identity.ForgotConfirmation.Title"] = "Confirmacion de recuperacion",
        ["Identity.ForgotConfirmation.Heading"] = "Revisa tu email",
        ["Identity.ForgotConfirmation.Message"] = "Si existe una cuenta con este email, enviamos instrucciones de recuperacion.",
        ["Identity.ForgotConfirmation.DevHint"] = "Ambiente de desarrollo detectado: cuando SMTP esta deshabilitado, los emails de prueba se guardan en",
        ["Identity.ForgotConfirmation.LastEmail"] = "Ultimo email guardado:",
        ["Identity.Reset.Title"] = "Restablecer contrasena",
        ["Identity.Reset.Heading"] = "Restablecer contrasena",
        ["Identity.Reset.Submit"] = "Actualizar contrasena",
        ["Identity.Reset.ErrorCodeRequired"] = "Se requiere codigo de restablecimiento.",
        ["Identity.ResetConfirmation.Title"] = "Contrasena restablecida",
        ["Identity.ResetConfirmation.Heading"] = "Contrasena actualizada",
        ["Identity.ResetConfirmation.Message"] = "Tu contrasena fue restablecida exitosamente.",
        ["Identity.ResetConfirmation.LoginWithNewPassword"] = "Inicia sesion con la nueva contrasena",
        ["Identity.ChangePassword.Title"] = "Cambiar contrasena",
        ["Identity.ChangePassword.Heading"] = "Cambiar contrasena",
        ["Identity.ChangePassword.Submit"] = "Guardar nueva contrasena",
        ["Identity.ChangePassword.CurrentPassword"] = "Contrasena actual",
        ["Identity.ChangePassword.NewPassword"] = "Nueva contrasena",
        ["Identity.ChangePassword.ConfirmNewPassword"] = "Confirmar nueva contrasena",
        ["Identity.ChangePasswordConfirmation.Title"] = "Contrasena cambiada",
        ["Identity.ChangePasswordConfirmation.Heading"] = "Contrasena cambiada",
        ["Identity.ChangePasswordConfirmation.Message"] = "Tu contrasena fue cambiada exitosamente.",
        ["Identity.ConfirmEmail.Title"] = "Confirmacion de email",
        ["Identity.ConfirmEmail.Heading"] = "Confirmacion de email",
        ["Identity.ConfirmEmail.InvalidLink"] = "Enlace de confirmacion invalido.",
        ["Identity.ConfirmEmail.Success"] = "Gracias por confirmar tu email.",
        ["Identity.ConfirmEmail.Failure"] = "No se pudo confirmar tu email.",
        ["Identity.Email.ConfirmSubject"] = "Confirma tu email",
        ["Identity.Email.ConfirmBody"] = "Confirma tu cuenta haciendo clic aqui: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ConfirmAction"] = "confirmar cuenta",
        ["Identity.Email.ResetSubject"] = "Restablece tu contrasena",
        ["Identity.Email.ResetBody"] = "Para restablecer tu contrasena, haz clic aqui: <a href='{0}'>{1}</a>.",
        ["Identity.Email.ResetAction"] = "restablecer contrasena",
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
