namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Core UI text domain: Navigation, Layout, Common, Error, Index, Breadcrumb
/// Covers fundamental app text strings used across all pages.
/// </summary>
internal static class CoreTexts
{
    /// <summary>PT-BR Portuguese (Brazil) strings</summary>
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation
        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Marketplace"] = "Marketplace",
        ["Nav.MyProducts"] = "Meus Produtos",
        ["Nav.InvoiceHistory"] = "Historico de faturas",
        ["Nav.Login"] = "Entrar",
        ["Nav.Register"] = "Registrar",
        ["Nav.Admin"] = "Admin",
        ["Nav.AdminLanguages"] = "Idiomas",
        ["Nav.About"] = "Sobre",
        ["Nav.Contact"] = "Contato",
        ["Nav.Payments"] = "Pagamentos",
        ["Nav.Integration"] = "Integracao",
        ["Nav.Mailbox"] = "Caixa de Entrada",
        ["Nav.Profile"] = "Perfil",
        ["Nav.Sports"] = "Partidas",

        // Layout
        ["Layout.HeaderQuoteTitle"] = "Moeda ativa para exibicao de cotacao",
        ["Layout.HeaderQuote"] = "Cotacao",
        ["Layout.Language"] = "Idioma",
        ["Layout.LanguagePtBr"] = "Portugues (Brasil)",
        ["Layout.LanguageEnUs"] = "Ingles (Estados Unidos)",
        ["Layout.LanguageEsEs"] = "Espanhol",
        ["Layout.Hello"] = "Bem-vindo",
        ["Layout.UserFallback"] = "Usuario",
        ["Layout.Logout"] = "Sair",
        ["Layout.WelcomeVisitor"] = "Bem-vindo, visitante!",
        ["Layout.NewsTicker1"] = "Novidades do Confirmai",
        ["Layout.NewsTicker2"] = "Confirme sua presença nos jogos",
        ["Layout.NewsTicker3"] = "Novos recursos disponiveis",
        ["Layout.NewsTicker4"] = "Participe da comunidade",

        // Index
        ["Index.TabExplore"] = "Explorar",
        ["Index.TabMyGames"] = "Meus Jogos",
        ["Index.CityLabel"] = "Cidade",
        ["Index.OtherCity"] = "Outra cidade...",
        ["Index.FutsalCardDesc"] = "Peladas, campeonatos e escolinhas na quadra",
        ["Index.PokerCardDesc"] = "Torneios, cash games e ligas semanais",
        ["Index.ViewMatches"] = "Ver partidas →",
        ["Index.ViewTournaments"] = "Ver torneios →",
        ["Index.LoadingConfirmations"] = "Carregando suas confirmações…",
        ["Index.NoConfirmations"] = "Você ainda não confirmou presença em nenhum evento.",
        ["Index.ViewFutsal"] = "Ver Futsal",
        ["Index.ViewPoker"] = "Ver Poker",
        ["Index.Upcoming"] = "Próximos",
        ["Index.Confirmed"] = "Confirmado",
        ["Index.ConfirmedCount"] = "confirmados",
        ["Index.Previous"] = "Anteriores",
        ["Index.NoPrevious"] = "Nenhuma partida anterior.",
        ["Index.Cancelled"] = "Cancelado",
        ["Index.NoCancelled"] = "Nenhuma partida cancelada.",
        ["Index.LoginRequired"] = "Faça login",
        ["Index.LoginRequiredSuffix"] = "para ver seus jogos.",
        ["Index.Goalkeeper"] = "Goleiro",
        ["Index.Line"] = "Linha",
        ["Index.Enter"] = "Entrar",
        ["Index.SportsAvailable"] = "Esportes disponíveis",
        ["Index.VolleyballCardDesc"] = "Partidas de vôlei",
        ["Index.BeachTennisCardDesc"] = "Partidas de beach tennis",
        ["Index.FootvolleyCardDesc"] = "Partidas de futevôlei",
        ["Index.ChessCardDesc"] = "Partidas de xadrez",
        ["Index.SportVolleyball"] = "🏐 Vôlei",
        ["Index.SportBeachTennis"] = "🎾 Beach Tennis",
        ["Index.SportFootvolley"] = "🏖️ Futevôlei",
        ["Index.SportChess"] = "♟️ Xadrez",
        ["Index.FilterAllSports"] = "Todos os esportes",
        ["Index.FilterAllPeriods"] = "Todos os períodos",
        ["Index.FilterLast7Days"] = "Últimos 7 dias",
        ["Index.FilterLast30Days"] = "Últimos 30 dias",

        // Common
        ["Common.Loading"] = "Carregando...",
        ["Common.Error"] = "Erro",
        ["Common.Success"] = "Sucesso",
        ["Common.Confirm"] = "Confirmar",
        ["Common.Cancel"] = "Cancelar",
        ["Common.Delete"] = "Deletar",
        ["Common.Edit"] = "Editar",
        ["Common.Save"] = "Salvar",
        ["Common.Close"] = "Fechar",
        ["Common.Back"] = "Voltar",
        ["Common.Next"] = "Próximo",
        ["Common.Previous"] = "Anterior",
        ["Common.Search"] = "Buscar",
        ["Common.Filter"] = "Filtro",
        ["Common.Clear"] = "Limpar",
        ["Common.Export"] = "Exportar",
        ["Common.Import"] = "Importar",
        ["Common.NotFound"] = "Nao encontrado",
        ["Common.NoData"] = "Sem dados",
        ["Common.Optional"] = "Opcional",
        ["Common.Required"] = "Obrigatorio",

        // App
        ["App.NotAuthorized"] = "Voce nao tem permissao para acessar esta pagina.",

        // Breadcrumb
        ["Breadcrumb.Home"] = "Inicio",
        ["Breadcrumb.Admin"] = "Admin",
        ["Breadcrumb.Users"] = "Usuarios",
        ["Breadcrumb.Payments"] = "Pagamentos",
        ["Breadcrumb.Logs"] = "Logs",
        ["Breadcrumb.Edit"] = "Editar",
        ["Breadcrumb.View"] = "Visualizar",
        ["Breadcrumb.Buy"] = "Comprar",
        ["Breadcrumb.Items"] = "Itens",
        ["Breadcrumb.Products"] = "Produtos",
        ["Breadcrumb.About"] = "Sobre",
        ["Breadcrumb.Contact"] = "Contato",
        ["Breadcrumb.Dashboard"] = "Dashboard",
        ["Breadcrumb.Marketplace"] = "Marketplace",
        ["Breadcrumb.Languages"] = "Idiomas",

        // Error
        ["Error.Title"] = "Erro",
        ["Error.Message"] = "Algo deu errado",
        ["Error.NotFound"] = "Pagina nao encontrada",
        ["Error.AccessDenied"] = "Acesso negado",
        ["Error.InternalServer"] = "Erro interno do servidor",
        ["App.NotFound.Title"] = "Página não encontrada",
        ["App.NotFound.Description"] = "O endereço que você acessou não existe ou foi movido.",
        ["App.NotFound.Help"] = "Verifique o link ou volte para o início.",
        ["App.NotFound.BackToDashboard"] = "Voltar ao início",

        // Groups
        ["Groups.Title"] = "Grupos",
        ["Groups.NotFound"] = "Grupo não encontrado.",
        ["Groups.Partidas"] = "Partidas",
        ["Groups.Proximas"] = "Próximas",
        ["Groups.Realizadas"] = "Realizadas",
        ["Groups.Semanais"] = "Semanais",
        ["Groups.NovaPartida"] = "Nova partida",
        ["Groups.VerMais"] = "Ver mais",
        ["Groups.VerMenos"] = "Ver menos",
        ["Groups.MyGroups"] = "Meus grupos",
        ["Groups.JoinGroup"] = "Entrar em um grupo",
        ["Groups.JoinOther"] = "Entrar em outro grupo",
        ["Groups.JoinCode"] = "Entrar com código de convite",
        ["Groups.CreateNew"] = "Criar novo grupo",
        ["Groups.ViewMatches"] = "Ver Partidas",
        ["Groups.Or"] = "ou",
        ["Groups.Enter"] = "Entrar",

        // Onboarding hint
        ["Onboarding.Title"] = "Como funciona",
        ["Onboarding.Intro"] = "Cada grupo representa uma turma — o seu racha, pelada ou baba. Você pode ter vários grupos: um para o futebol de segunda, outro para o futebol de sábado, e por aí vai.",
        ["Onboarding.Step1"] = "Crie um grupo para cada racha e convide a turma",
        ["Onboarding.Step2"] = "Crie partidas semanais ou avulsas para o grupo",
        ["Onboarding.Step3"] = "Os membros efetuam pagamento e confirmam presença na partida",
        ["Onboarding.AccessGroups"] = "Acessar grupos",

        // Payment
        ["Payment.PixOrganizer"] = "Pix do Organizador",
        ["Payment.SelectReceiver"] = "Selecione qual admin recebe os pagamentos das partidas.",
        ["Payment.SelectReceiverSub"] = "A chave Pix do admin selecionado será exibida aos jogadores na página de pagamento.",
        ["Payment.NoPixAdmin"] = "Nenhum admin do grupo tem Chave Pix cadastrada no perfil.",
        ["Payment.ConfigurePix"] = "Configure a sua Chave Pix →",
        ["Payment.AdminReceives"] = "Admin que recebe:",
        ["Payment.AutoReceiver"] = "— Automático (primeiro admin com Pix) —",
        ["Payment.Save"] = "Salvar",
        ["Payment.Saving"] = "Salvando…",
        ["Payment.ManualFlow"] = "Este grupo utiliza o fluxo padrão: Pix direto para o organizador com envio de comprovante.",

        // Shared components (C28 migration)
        ["Shared.CitySelector.UseLocation"] = "Usar minha localização",
        ["Shared.CitySelector.FilterLabel"] = "Filtro de cidade",
        ["Shared.EntityProfileShell.AdditionalActions"] = "Ações adicionais",
        ["Shared.EventListingShell.NextDay"] = "Próximo dia",
        ["Shared.EventListingShell.Available"] = "disponíveis",
        ["Shared.EventListingShell.SelectDate"] = "Selecionar data",
        ["Shared.EventListingShell.PreviousDay"] = "Dia anterior",
        ["Shared.EventListingShell.Loading"] = "Carregando",
        ["Shared.EventListingShell.ViewToday"] = "Ver hoje",
        ["Common.Page"] = "Página",
        ["Shared.UserSummaryCard.User"] = "Usuário:",
        ["Shared.UserSummaryCard.NotInformedFemale"] = "Não informada",
        ["Shared.UserSummaryCard.Permissions"] = "Permissões:",
        ["Shared.UserSummaryCard.Email"] = "Email:",
        ["Shared.UserSummaryCard.FullName"] = "Nome completo:",
        ["Shared.UserSummaryCard.BirthDate"] = "Data de nascimento:",
        ["Shared.UserSummaryCard.Status"] = "Status:",
        ["Shared.UserSummaryCard.Active"] = "Ativo",
    };

    /// <summary>EN-US English (United States) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation
        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Marketplace"] = "Marketplace",
        ["Nav.MyProducts"] = "My Products",
        ["Nav.InvoiceHistory"] = "Invoice History",
        ["Nav.Login"] = "Login",
        ["Nav.Register"] = "Register",
        ["Nav.Admin"] = "Admin",
        ["Nav.AdminLanguages"] = "Languages",
        ["Nav.About"] = "About",
        ["Nav.Contact"] = "Contact",
        ["Nav.Payments"] = "Payments",
        ["Nav.Integration"] = "Integration",
        ["Nav.Mailbox"] = "Inbox",
        ["Nav.Profile"] = "Profile",
        ["Nav.Sports"] = "Matches",

        // Layout
        ["Layout.HeaderQuoteTitle"] = "Active currency for quote display",
        ["Layout.HeaderQuote"] = "Quote",
        ["Layout.Language"] = "Language",
        ["Layout.LanguagePtBr"] = "Portuguese (Brazil)",
        ["Layout.LanguageEnUs"] = "English (United States)",
        ["Layout.LanguageEsEs"] = "Spanish",
        ["Layout.Hello"] = "Welcome",
        ["Layout.UserFallback"] = "User",
        ["Layout.Logout"] = "Logout",
        ["Layout.WelcomeVisitor"] = "Welcome, visitor!",
        ["Layout.NewsTicker1"] = "Confirmai News",
        ["Layout.NewsTicker2"] = "Confirm your presence in games",
        ["Layout.NewsTicker3"] = "New features available",
        ["Layout.NewsTicker4"] = "Join the community",

        // Index
        ["Index.TabExplore"] = "Explore",
        ["Index.TabMyGames"] = "My Games",
        ["Index.CityLabel"] = "City",
        ["Index.OtherCity"] = "Other city...",
        ["Index.FutsalCardDesc"] = "Pickup games, tournaments and training sessions",
        ["Index.PokerCardDesc"] = "Tournaments, cash games and weekly leagues",
        ["Index.ViewMatches"] = "View matches →",
        ["Index.ViewTournaments"] = "View tournaments →",
        ["Index.LoadingConfirmations"] = "Loading your confirmations…",
        ["Index.NoConfirmations"] = "You haven't confirmed presence in any event yet.",
        ["Index.ViewFutsal"] = "View Futsal",
        ["Index.ViewPoker"] = "View Poker",
        ["Index.Upcoming"] = "Upcoming",
        ["Index.Confirmed"] = "Confirmed",
        ["Index.ConfirmedCount"] = "confirmed",
        ["Index.Previous"] = "Previous",
        ["Index.NoPrevious"] = "No previous matches.",
        ["Index.Cancelled"] = "Cancelled",
        ["Index.NoCancelled"] = "No cancelled matches.",
        ["Index.LoginRequired"] = "Log in",
        ["Index.LoginRequiredSuffix"] = "to view your games.",
        ["Index.Goalkeeper"] = "Goalkeeper",
        ["Index.Line"] = "Line",
        ["Index.Enter"] = "Enter",
        ["Index.SportsAvailable"] = "Available sports",
        ["Index.VolleyballCardDesc"] = "Volleyball matches",
        ["Index.BeachTennisCardDesc"] = "Beach tennis matches",
        ["Index.FootvolleyCardDesc"] = "Footvolley matches",
        ["Index.ChessCardDesc"] = "Chess matches",
        ["Index.SportVolleyball"] = "🏐 Volleyball",
        ["Index.SportBeachTennis"] = "🎾 Beach Tennis",
        ["Index.SportFootvolley"] = "🏖️ Footvolley",
        ["Index.SportChess"] = "♟️ Chess",
        ["Index.FilterAllSports"] = "All sports",
        ["Index.FilterAllPeriods"] = "All periods",
        ["Index.FilterLast7Days"] = "Last 7 days",
        ["Index.FilterLast30Days"] = "Last 30 days",

        // Common
        ["Common.Loading"] = "Loading...",
        ["Common.Error"] = "Error",
        ["Common.Success"] = "Success",
        ["Common.Confirm"] = "Confirm",
        ["Common.Cancel"] = "Cancel",
        ["Common.Delete"] = "Delete",
        ["Common.Edit"] = "Edit",
        ["Common.Save"] = "Save",
        ["Common.Close"] = "Close",
        ["Common.Back"] = "Back",
        ["Common.Next"] = "Next",
        ["Common.Previous"] = "Previous",
        ["Common.Search"] = "Search",
        ["Common.Filter"] = "Filter",
        ["Common.Clear"] = "Clear",
        ["Common.Export"] = "Export",
        ["Common.Import"] = "Import",
        ["Common.NotFound"] = "Not found",
        ["Common.NoData"] = "No data",
        ["Common.Optional"] = "Optional",
        ["Common.Required"] = "Required",

        // App
        ["App.NotAuthorized"] = "You are not authorized to access this page.",

        // Breadcrumb
        ["Breadcrumb.Home"] = "Home",
        ["Breadcrumb.Admin"] = "Admin",
        ["Breadcrumb.Users"] = "Users",
        ["Breadcrumb.Payments"] = "Payments",
        ["Breadcrumb.Logs"] = "Logs",
        ["Breadcrumb.Edit"] = "Edit",
        ["Breadcrumb.View"] = "View",
        ["Breadcrumb.Buy"] = "Buy",
        ["Breadcrumb.Items"] = "Items",
        ["Breadcrumb.Products"] = "Products",
        ["Breadcrumb.About"] = "About",
        ["Breadcrumb.Contact"] = "Contact",
        ["Breadcrumb.Dashboard"] = "Dashboard",
        ["Breadcrumb.Marketplace"] = "Marketplace",
        ["Breadcrumb.Languages"] = "Languages",

        // Error
        ["Error.Title"] = "Error",
        ["Error.Message"] = "Something went wrong",
        ["Error.NotFound"] = "Page not found",
        ["Error.AccessDenied"] = "Access denied",
        ["Error.InternalServer"] = "Internal server error",
        ["App.NotFound.Title"] = "Page not found",
        ["App.NotFound.Description"] = "The address you opened does not exist or has moved.",
        ["App.NotFound.Help"] = "Check the link or go back home.",
        ["App.NotFound.BackToDashboard"] = "Back to home",

        // Groups
        ["Groups.Title"] = "Groups",
        ["Groups.NotFound"] = "Group not found.",
        ["Groups.Partidas"] = "Matches",
        ["Groups.Proximas"] = "Upcoming",
        ["Groups.Realizadas"] = "Completed",
        ["Groups.Semanais"] = "Weekly",
        ["Groups.NovaPartida"] = "New match",
        ["Groups.VerMais"] = "Show more",
        ["Groups.VerMenos"] = "Show less",
        ["Groups.MyGroups"] = "My groups",
        ["Groups.JoinGroup"] = "Join a group",
        ["Groups.JoinOther"] = "Join another group",
        ["Groups.JoinCode"] = "Join with invite code",
        ["Groups.CreateNew"] = "Create new group",
        ["Groups.ViewMatches"] = "View Matches",
        ["Groups.Or"] = "or",
        ["Groups.Enter"] = "Enter",

        // Onboarding hint
        ["Onboarding.Title"] = "How it works",
        ["Onboarding.Intro"] = "Each group represents your crew — your pickup game, match or kickabout. You can have multiple groups: one for Monday football, another for Saturday football, and so on.",
        ["Onboarding.Step1"] = "Create a group for each pickup game and invite your crew",
        ["Onboarding.Step2"] = "Create weekly or one-off matches for the group",
        ["Onboarding.Step3"] = "Members pay and confirm their presence for the match",
        ["Onboarding.AccessGroups"] = "Access groups",

        // Payment
        ["Payment.PixOrganizer"] = "Organizer Pix",
        ["Payment.SelectReceiver"] = "Select which admin receives match payments.",
        ["Payment.SelectReceiverSub"] = "The selected admin's Pix key will be shown to players on the payment page.",
        ["Payment.NoPixAdmin"] = "No group admin has a Pix key registered in their profile.",
        ["Payment.ConfigurePix"] = "Configure your Pix Key →",
        ["Payment.AdminReceives"] = "Receiving admin:",
        ["Payment.AutoReceiver"] = "— Automatic (first admin with Pix) —",
        ["Payment.Save"] = "Save",
        ["Payment.Saving"] = "Saving…",
        ["Payment.ManualFlow"] = "This group uses the standard flow: direct Pix to the organizer with proof upload.",

        // Shared components (C28 migration)
        ["Shared.CitySelector.UseLocation"] = "Use my location",
        ["Shared.CitySelector.FilterLabel"] = "City filter",
        ["Shared.EntityProfileShell.AdditionalActions"] = "Additional actions",
        ["Shared.EventListingShell.NextDay"] = "Next day",
        ["Shared.EventListingShell.Available"] = "available",
        ["Shared.EventListingShell.SelectDate"] = "Select date",
        ["Shared.EventListingShell.PreviousDay"] = "Previous day",
        ["Shared.EventListingShell.Loading"] = "Loading",
        ["Shared.EventListingShell.ViewToday"] = "View today",
        ["Common.Page"] = "Page",
        ["Shared.UserSummaryCard.User"] = "User:",
        ["Shared.UserSummaryCard.NotInformedFemale"] = "Not informed",
        ["Shared.UserSummaryCard.Permissions"] = "Permissions:",
        ["Shared.UserSummaryCard.Email"] = "Email:",
        ["Shared.UserSummaryCard.FullName"] = "Full name:",
        ["Shared.UserSummaryCard.BirthDate"] = "Date of birth:",
        ["Shared.UserSummaryCard.Status"] = "Status:",
        ["Shared.UserSummaryCard.Active"] = "Active",
    };

    /// <summary>ES-ES Spanish (Spain) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation
        ["Nav.Dashboard"] = "Panel",
        ["Nav.Marketplace"] = "Mercado",
        ["Nav.MyProducts"] = "Mis Productos",
        ["Nav.InvoiceHistory"] = "Historial de facturas",
        ["Nav.Login"] = "Iniciar sesion",
        ["Nav.Register"] = "Registrarse",
        ["Nav.Admin"] = "Admin",
        ["Nav.AdminLanguages"] = "Idiomas",
        ["Nav.About"] = "Acerca de",
        ["Nav.Contact"] = "Contacto",
        ["Nav.Payments"] = "Pagos",
        ["Nav.Integration"] = "Integracion",
        ["Nav.Mailbox"] = "Bandeja de entrada",
        ["Nav.Profile"] = "Perfil",
        ["Nav.Sports"] = "Partidos",

        // Layout
        ["Layout.HeaderQuoteTitle"] = "Moneda activa para mostrar cotizacion",
        ["Layout.HeaderQuote"] = "Cotizacion",
        ["Layout.Language"] = "Idioma",
        ["Layout.LanguagePtBr"] = "Portugues (Brasil)",
        ["Layout.LanguageEnUs"] = "Ingles (Estados Unidos)",
        ["Layout.LanguageEsEs"] = "Espanol",
        ["Layout.Hello"] = "Bienvenido",
        ["Layout.UserFallback"] = "Usuario",
        ["Layout.Logout"] = "Cerrar sesion",
        ["Layout.WelcomeVisitor"] = "Bienvenido, visitante!",
        ["Layout.NewsTicker1"] = "Noticias de Confirmai",
        ["Layout.NewsTicker2"] = "Confirma tu presencia en los juegos",
        ["Layout.NewsTicker3"] = "Nuevas caracteristicas disponibles",
        ["Layout.NewsTicker4"] = "Unete a la comunidad",

        // Index
        ["Index.TabExplore"] = "Explorar",
        ["Index.TabMyGames"] = "Mis Juegos",
        ["Index.CityLabel"] = "Ciudad",
        ["Index.OtherCity"] = "Otra ciudad...",
        ["Index.FutsalCardDesc"] = "Partidos, torneos y escuelas en la cancha",
        ["Index.PokerCardDesc"] = "Torneos, cash games y ligas semanales",
        ["Index.ViewMatches"] = "Ver partidos →",
        ["Index.ViewTournaments"] = "Ver torneos →",
        ["Index.LoadingConfirmations"] = "Cargando tus confirmaciones…",
        ["Index.NoConfirmations"] = "Aun no has confirmado presencia en ningun evento.",
        ["Index.ViewFutsal"] = "Ver Futsal",
        ["Index.ViewPoker"] = "Ver Poker",
        ["Index.Upcoming"] = "Proximos",
        ["Index.Confirmed"] = "Confirmado",
        ["Index.ConfirmedCount"] = "confirmados",
        ["Index.Previous"] = "Anteriores",
        ["Index.NoPrevious"] = "Ningun partido anterior.",
        ["Index.Cancelled"] = "Cancelado",
        ["Index.NoCancelled"] = "Ningun partido cancelado.",
        ["Index.LoginRequired"] = "Inicia sesion",
        ["Index.LoginRequiredSuffix"] = "para ver tus juegos.",
        ["Index.Goalkeeper"] = "Portero",
        ["Index.Line"] = "Linea",
        ["Index.Enter"] = "Entrar",
        ["Index.SportsAvailable"] = "Deportes disponibles",
        ["Index.VolleyballCardDesc"] = "Partidos de voleibol",
        ["Index.BeachTennisCardDesc"] = "Partidos de beach tennis",
        ["Index.FootvolleyCardDesc"] = "Partidos de futvolei",
        ["Index.ChessCardDesc"] = "Partidos de ajedrez",
        ["Index.SportVolleyball"] = "🏐 Voleibol",
        ["Index.SportBeachTennis"] = "🎾 Beach Tennis",
        ["Index.SportFootvolley"] = "🏖️ Futvolei",
        ["Index.SportChess"] = "♟️ Ajedrez",
        ["Index.FilterAllSports"] = "Todos los deportes",
        ["Index.FilterAllPeriods"] = "Todos los periodos",
        ["Index.FilterLast7Days"] = "Ultimos 7 dias",
        ["Index.FilterLast30Days"] = "Ultimos 30 dias",

        // Common
        ["Common.Loading"] = "Cargando...",
        ["Common.Error"] = "Error",
        ["Common.Success"] = "Exito",
        ["Common.Confirm"] = "Confirmar",
        ["Common.Cancel"] = "Cancelar",
        ["Common.Delete"] = "Eliminar",
        ["Common.Edit"] = "Editar",
        ["Common.Save"] = "Guardar",
        ["Common.Close"] = "Cerrar",
        ["Common.Back"] = "Atras",
        ["Common.Next"] = "Siguiente",
        ["Common.Previous"] = "Anterior",
        ["Common.Search"] = "Buscar",
        ["Common.Filter"] = "Filtro",
        ["Common.Clear"] = "Limpiar",
        ["Common.Export"] = "Exportar",
        ["Common.Import"] = "Importar",
        ["Common.NotFound"] = "No encontrado",
        ["Common.NoData"] = "Sin datos",
        ["Common.Optional"] = "Opcional",
        ["Common.Required"] = "Obligatorio",

        // App
        ["App.NotAuthorized"] = "No tienes permiso para acceder a esta pagina.",

        // Breadcrumb
        ["Breadcrumb.Home"] = "Inicio",
        ["Breadcrumb.Admin"] = "Admin",
        ["Breadcrumb.Users"] = "Usuarios",
        ["Breadcrumb.Payments"] = "Pagos",
        ["Breadcrumb.Logs"] = "Registros",
        ["Breadcrumb.Edit"] = "Editar",
        ["Breadcrumb.View"] = "Ver",
        ["Breadcrumb.Buy"] = "Comprar",
        ["Breadcrumb.Items"] = "Articulos",
        ["Breadcrumb.Products"] = "Productos",
        ["Breadcrumb.About"] = "Acerca de",
        ["Breadcrumb.Contact"] = "Contacto",
        ["Breadcrumb.Dashboard"] = "Panel",
        ["Breadcrumb.Marketplace"] = "Mercado",
        ["Breadcrumb.Languages"] = "Idiomas",

        // Error
        ["Error.Title"] = "Error",
        ["Error.Message"] = "Algo salio mal",
        ["Error.NotFound"] = "Pagina no encontrada",
        ["Error.AccessDenied"] = "Acceso denegado",
        ["Error.InternalServer"] = "Error interno del servidor",
        ["App.NotFound.Title"] = "Página no encontrada",
        ["App.NotFound.Description"] = "La dirección que abriste no existe o fue movida.",
        ["App.NotFound.Help"] = "Revisa el enlace o vuelve al inicio.",
        ["App.NotFound.BackToDashboard"] = "Volver al inicio",

        // Groups
        ["Groups.Title"] = "Grupos",
        ["Groups.NotFound"] = "Grupo no encontrado.",
        ["Groups.Partidas"] = "Partidos",
        ["Groups.Proximas"] = "Proximos",
        ["Groups.Realizadas"] = "Realizados",
        ["Groups.Semanais"] = "Semanales",
        ["Groups.NovaPartida"] = "Nuevo partido",
        ["Groups.VerMais"] = "Ver mas",
        ["Groups.VerMenos"] = "Ver menos",
        ["Groups.MyGroups"] = "Mis grupos",
        ["Groups.JoinGroup"] = "Unirse a un grupo",
        ["Groups.JoinOther"] = "Unirse a otro grupo",
        ["Groups.JoinCode"] = "Unirse con codigo de invitacion",
        ["Groups.CreateNew"] = "Crear nuevo grupo",
        ["Groups.ViewMatches"] = "Ver Partidos",
        ["Groups.Or"] = "o",
        ["Groups.Enter"] = "Entrar",

        // Onboarding hint
        ["Onboarding.Title"] = "Como funciona",
        ["Onboarding.Intro"] = "Cada grupo representa tu equipo — tu partido, pachanga o partido informal. Puedes tener varios grupos: uno para el futbol del lunes, otro para el del sabado, y asi sucesivamente.",
        ["Onboarding.Step1"] = "Crea un grupo para cada partido e invita a tu equipo",
        ["Onboarding.Step2"] = "Crea partidos semanales o puntuales para el grupo",
        ["Onboarding.Step3"] = "Los miembros pagan y confirman su presencia para el partido",
        ["Onboarding.AccessGroups"] = "Acceder a grupos",

        // Payment
        ["Payment.PixOrganizer"] = "Pix del Organizador",
        ["Payment.SelectReceiver"] = "Selecciona que admin recibe los pagos de los partidos.",
        ["Payment.SelectReceiverSub"] = "La clave Pix del admin seleccionado se mostrara a los jugadores en la pagina de pago.",
        ["Payment.NoPixAdmin"] = "Ningun admin del grupo tiene clave Pix registrada en su perfil.",
        ["Payment.ConfigurePix"] = "Configura tu clave Pix →",
        ["Payment.AdminReceives"] = "Admin que recibe:",
        ["Payment.AutoReceiver"] = "— Automatico (primer admin con Pix) —",
        ["Payment.Save"] = "Guardar",
        ["Payment.Saving"] = "Guardando…",
        ["Payment.ManualFlow"] = "Este grupo usa el flujo estandar: Pix directo al organizador con envio de comprobante.",

        // Shared components (C28 migration)
        ["Shared.CitySelector.UseLocation"] = "Usar mi ubicación",
        ["Shared.CitySelector.FilterLabel"] = "Filtro de ciudad",
        ["Shared.EntityProfileShell.AdditionalActions"] = "Acciones adicionales",
        ["Shared.EventListingShell.NextDay"] = "Día siguiente",
        ["Shared.EventListingShell.Available"] = "disponibles",
        ["Shared.EventListingShell.SelectDate"] = "Seleccionar fecha",
        ["Shared.EventListingShell.PreviousDay"] = "Día anterior",
        ["Shared.EventListingShell.Loading"] = "Cargando",
        ["Shared.EventListingShell.ViewToday"] = "Ver hoy",
        ["Common.Page"] = "Página",
        ["Shared.UserSummaryCard.User"] = "Usuario:",
        ["Shared.UserSummaryCard.NotInformedFemale"] = "No informada",
        ["Shared.UserSummaryCard.Permissions"] = "Permisos:",
        ["Shared.UserSummaryCard.Email"] = "Correo:",
        ["Shared.UserSummaryCard.FullName"] = "Nombre completo:",
        ["Shared.UserSummaryCard.BirthDate"] = "Fecha de nacimiento:",
        ["Shared.UserSummaryCard.Status"] = "Estado:",
        ["Shared.UserSummaryCard.Active"] = "Activo",
    };

    /// <summary>Get combined dictionary for all languages</summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
