namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Futsal UI text domain: match detail, create, edit, escalacao, schedule, components.
/// </summary>
internal static class FutsalTexts
{
    /// <summary>PT-BR Portuguese (Brazil) strings</summary>
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Futsal.PageTitle"] = "Partida",
        ["Futsal.CreatePageTitle"] = "Criar Partida · Futsal · Confirmai",
        ["Futsal.EditPageTitle"] = "Editar Partida · Futsal · Confirmai",
        ["Futsal.ScheduleEditPageTitle"] = "Editar Partida Semanal · Confirmai",
        ["Futsal.ScheduleIndexPageTitle"] = "Partidas Semanais — Confirmai",
        ["Futsal.EscalacaoPageTitle"] = "Escalação",
        ["Futsal.PostMatchPageTitle"] = "Pós-Partida",

        // Common match strings
        ["Futsal.MatchNotFound"] = "Partida não encontrada.",
        ["Futsal.ScheduleNotFound"] = "Agendamento não encontrado.",
        ["Futsal.AccessDenied"] = "Acesso negado.",
        ["Futsal.OnlyOrganizerCanEdit"] = "Apenas o organizador pode editar esta partida.",
        ["Futsal.OnlyCreatorCanEditSchedule"] = "Apenas o criador pode editar este agendamento.",
        ["Futsal.MatchCancelled"] = "Esta partida foi cancelada.",
        ["Futsal.EnterToConfirm"] = "Entrar para confirmar presença",
        ["Futsal.ConfirmPresence"] = "Confirmar presença",
        ["Futsal.NewMatch"] = "Nova Partida",
        ["Futsal.NewMatchFutsal"] = "Nova Partida de Futsal",
        ["Futsal.NewMatchGroup"] = "Nova Partida — {0}",
        ["Futsal.CreateMatch"] = "Criar Partida",
        ["Futsal.Creating"] = "Criando…",
        ["Futsal.EditMatch"] = "Editar Partida",
        ["Futsal.SaveChanges"] = "Salvar Alterações",
        ["Futsal.Saving"] = "Salvando…",

        // Player tags
        ["Futsal.Player"] = "Jogador",
        ["Futsal.Goalkeeper"] = "Goleiro",
        ["Futsal.You"] = "Você",
        ["Futsal.Mvp"] = "⭐ Destaque",
        ["Futsal.NoPay"] = "não paga",
        ["Futsal.Paid"] = "pago",
        ["Futsal.Pending"] = "pendente",
        ["Futsal.Pay"] = "pagar",
        ["Futsal.MarkPaid"] = "marcar pago?",
        ["Futsal.UnmarkPaid"] = "desmarcar?",
        ["Futsal.Proof"] = "📎 comprovante",
        ["Futsal.ProofTitle"] = "Comprovante enviado - clique para gerenciar",
        ["Futsal.ProofSent"] = "Comprovante enviado",
        ["Futsal.NoProofTitle"] = "Sem comprovante - clique para marcar pago",
        ["Futsal.GatewayPaidTitle"] = "Pago via gateway — não pode ser desfeito pelo admin",
        ["Futsal.Receiver"] = "recebedor",

        // Actions
        ["Futsal.Remove"] = "remover",
        ["Futsal.RemoveConfirm"] = "remover?",
        ["Futsal.Cancel"] = "cancelar",
        ["Futsal.CancelSignupConfirm"] = "cancelar inscrição?",
        ["Futsal.Waitlist"] = "Entrar na lista de espera",
        ["Futsal.WaitlistGk"] = "Entrar na lista de espera de goleiros",
        ["Futsal.WaitlistLine"] = "Entrar na lista de espera de linha",
        ["Futsal.RemoveSlot"] = "Remover vaga",
        ["Futsal.AddSlot"] = "Adicionar vaga",
        ["Futsal.RemoveSlotGk"] = "Remover vaga de goleiro",
        ["Futsal.AddSlotGk"] = "Adicionar vaga de goleiro",
        ["Futsal.RemoveSlotLine"] = "Remover vaga de linha",
        ["Futsal.AddSlotLine"] = "Adicionar vaga de linha",

        // Confirmed banner
        ["Futsal.ConfirmedToPlay"] = "Confirmado para jogar na",
        ["Futsal.Gol"] = "GOL",
        ["Futsal.Linha"] = "LINHA",
        ["Futsal.PaidAmount"] = "Pago R$ {0}",
        ["Futsal.PayAmount"] = "Pagar R$ {0}",

        // Private group
        ["Futsal.JoinRequestSent"] = "Solicitação enviada — aguardando aprovação do administrador do grupo.",
        ["Futsal.CancelJoinRequest"] = "Cancelar solicitação",
        ["Futsal.CancellingJoin"] = "Cancelando…",
        ["Futsal.JoinRequestRejected"] = "Sua solicitação de entrada foi recusada.",
        ["Futsal.PrivateGroup"] = "Este grupo é privado. Solicite entrada para o administrador.",
        ["Futsal.RequestJoin"] = "Solicitar entrada",
        ["Futsal.SendingJoin"] = "Enviando...",

        // Escalacao
        ["Futsal.EscalacaoNotAvailable"] = "Escalação não disponível",
        ["Futsal.EscalacaoNotMounted"] = "A escalação ainda não foi montada pelo organizador.",
        ["Futsal.BackToMatch"] = "Voltar à partida",
        ["Futsal.PostMatchOnlyMembers"] = "Apenas membros do grupo podem ver o resumo e votar no destaque.",
        ["Futsal.MontarEscalacao"] = "Montar Escalação",
        ["Futsal.VerEscalacao"] = "Ver Escalação",
        ["Futsal.EscalacaoConfirmedAt"] = "Escalação confirmada em {0}",
        ["Futsal.ResetEscalacao"] = "Resetar escalação",
        ["Futsal.ResetConfirm"] = "Tem certeza? A escalação será desfeita e os jogadores voltarão a não ter time atribuído.",
        ["Futsal.Resetting"] = "Resetando…",
        ["Futsal.SimResetar"] = "Sim, resetar",
        ["Futsal.ShufflePlayers"] = "Embaralhar jogadores de linha",
        ["Futsal.ConfirmEscalacao"] = "Confirmar escalação",
        ["Futsal.TeamsUnbalanced"] = "Times desiguais — iguale os jogadores de linha para confirmar.",
        ["Futsal.ConfirmEscalacaoModal"] = "Confirmar esta escalação? Os times ficarão visíveis para todos os confirmados.",
        ["Futsal.SimConfirmar"] = "Sim, confirmar",

        // Escalacao share
        ["Futsal.Copied"] = "Copiado!",
        ["Futsal.CopyEscalacao"] = "Copiar escalação",
        ["Futsal.ShareWhatsApp"] = "Compartilhar no WhatsApp",

        // Escalacao score
        ["Futsal.Score"] = "Placar",
        ["Futsal.TeamWon"] = "🏆 {0} venceu!",
        ["Futsal.Draw"] = "🤝 Empate",
        ["Futsal.RegisteredBy"] = "Registrado por {0}",
        ["Futsal.RegisteredAt"] = "em {0}",
        ["Futsal.ConfirmScore"] = "Confirmar placar",
        ["Futsal.ScoreNotRegistered"] = "Placar ainda não registrado.",

        // Quorum
        ["Futsal.MatchEnded"] = "Partida encerrada",
        ["Futsal.QuorumReached"] = "Quantidade mínima de jogadores atingida",
        ["Futsal.QuorumNeeded"] = "Quantidade mínima de jogadores é: {0} de linha + {1} goleiro(s)",
        ["Futsal.LackingPlayers"] = "Faltam {0} jogador(es) para atingir o mínimo necessário",

        // Location
        ["Futsal.Location"] = "Localização",
        ["Futsal.LocationIframeTitle"] = "Localização da quadra",
        ["Futsal.OpenInMaps"] = "Abrir no Google Maps",

        // Form fields
        ["Futsal.Identity"] = "Identidade da Partida",
        ["Futsal.MatchName"] = "Nome da partida",
        ["Futsal.MatchNamePlaceholder"] = "Ex: \"Rachão da Galera do Zé\", \"Pelada de Quinta\"",
        ["Futsal.LocalNameLabel"] = "Como vocês chamam o jogo na sua região?",
        ["Futsal.LocalNamePlaceholder"] = "racha, pelada, baba, rachão…",
        ["Futsal.LocalNameHint"] = "Opcional — aparece nos cards para identificar o estilo da região.",
        ["Futsal.Modality"] = "Modalidade",
        ["Futsal.ModalityFutsal"] = "Futsal",
        ["Futsal.ModalitySociety"] = "Fut7 / Society",
        ["Futsal.ModalityCampo"] = "Campo",
        ["Futsal.Venue"] = "Local",
        ["Futsal.VenueField"] = "Quadra / Society / Campo",
        ["Futsal.VenueSelect"] = "— Selecione a quadra —",
        ["Futsal.VenueSelectShort"] = "— selecione —",
        ["Futsal.NoVenueRegistered"] = "Nenhuma quadra cadastrada ainda. Solicite ao administrador do sistema.",
        ["Futsal.DateTime"] = "Data & Horário",
        ["Futsal.Date"] = "Data",
        ["Futsal.StartTime"] = "Hora de início",
        ["Futsal.Duration"] = "Duração",
        ["Futsal.Slots"] = "Vagas",
        ["Futsal.TotalSlots"] = "Vagas totais (linha + goleiros)",
        ["Futsal.Goalkeepers"] = "Goleiros",
        ["Futsal.NoGkHint"] = "0 = sem reserva de goleiro.",
        ["Futsal.RotateInGoal"] = "Revezar jogadores de linha no gol",
        ["Futsal.Price"] = "Valor",
        ["Futsal.PricePerPlayer"] = "Valor por jogador (R$)",
        ["Futsal.PriceHint"] = "Use 0 para partidas sem cobrança.",
        ["Futsal.CancelMatch"] = "Cancelar partida",
        ["Futsal.CancelMatchConfirm"] = "Tem certeza? Todos os confirmados serão avisados.",
        ["Futsal.No"] = "Não",
        ["Futsal.SimCancelar"] = "Sim, cancelar",

        // Schedule
        ["Futsal.WeeklyMatches"] = "Partidas Semanais",
        ["Futsal.LoadingWeekly"] = "Carregando suas partidas semanais…",
        ["Futsal.NoWeeklyMatches"] = "Nenhuma partida semanal cadastrada.",
        ["Futsal.NoWeeklyHint"] = "Crie uma partida semanal para gerar partidas automaticamente toda semana.",
        ["Futsal.Inactive"] = "Inativa",
        ["Futsal.Players"] = "jogadores",
        ["Futsal.GoalkeepersShort"] = "goleiros",
        ["Futsal.Next"] = "Próxima: {0}",
        ["Futsal.ConfirmedCount"] = "confirmados",
        ["Futsal.NoFutureMatch"] = "Nenhuma partida futura gerada.",
        ["Futsal.Deactivate"] = "Desativar",
        ["Futsal.Reactivate"] = "Reativar",
        ["Futsal.ScheduleWarning"] = "⚠️ Alterações aqui não afetam partidas já geradas — apenas as próximas ocorrências.",
        ["Futsal.Identification"] = "Identificação",
        ["Futsal.Schedule"] = "Horário",
        ["Futsal.DayOfWeek"] = "Dia da semana",
        ["Futsal.Create.PixRequired"] = "Configure sua chave Pix no perfil antes de criar uma partida com preço.",

        // Futsal components (C28 migration)
        ["Futsal.WaitlistTitle"] = "Lista de espera",
        ["Futsal.Reserve"] = "Reserva",
        ["Futsal.MatchHighlight"] = "Destaque da Partida",
        ["Futsal.DaysOfWeek"] = "Dias da semana",
    };

    /// <summary>EN-US English (United States) strings</summary>
    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Futsal.PageTitle"] = "Match",
        ["Futsal.CreatePageTitle"] = "Create Match · Futsal · Confirmai",
        ["Futsal.EditPageTitle"] = "Edit Match · Futsal · Confirmai",
        ["Futsal.ScheduleEditPageTitle"] = "Edit Weekly Match · Confirmai",
        ["Futsal.ScheduleIndexPageTitle"] = "Weekly Matches — Confirmai",
        ["Futsal.EscalacaoPageTitle"] = "Lineup",
        ["Futsal.PostMatchPageTitle"] = "Post-Match",

        // Common match strings
        ["Futsal.MatchNotFound"] = "Match not found.",
        ["Futsal.ScheduleNotFound"] = "Schedule not found.",
        ["Futsal.AccessDenied"] = "Access denied.",
        ["Futsal.OnlyOrganizerCanEdit"] = "Only the organizer can edit this match.",
        ["Futsal.OnlyCreatorCanEditSchedule"] = "Only the creator can edit this schedule.",
        ["Futsal.MatchCancelled"] = "This match has been cancelled.",
        ["Futsal.EnterToConfirm"] = "Join to confirm attendance",
        ["Futsal.ConfirmPresence"] = "Confirm attendance",
        ["Futsal.NewMatch"] = "New Match",
        ["Futsal.NewMatchFutsal"] = "New Futsal Match",
        ["Futsal.NewMatchGroup"] = "New Match — {0}",
        ["Futsal.CreateMatch"] = "Create Match",
        ["Futsal.Creating"] = "Creating…",
        ["Futsal.EditMatch"] = "Edit Match",
        ["Futsal.SaveChanges"] = "Save Changes",
        ["Futsal.Saving"] = "Saving…",

        // Player tags
        ["Futsal.Player"] = "Player",
        ["Futsal.Goalkeeper"] = "Goalkeeper",
        ["Futsal.You"] = "You",
        ["Futsal.Mvp"] = "⭐ MVP",
        ["Futsal.NoPay"] = "unpaid",
        ["Futsal.Paid"] = "paid",
        ["Futsal.Pending"] = "pending",
        ["Futsal.Pay"] = "pay",
        ["Futsal.MarkPaid"] = "mark paid?",
        ["Futsal.UnmarkPaid"] = "unmark?",
        ["Futsal.Proof"] = "📎 receipt",
        ["Futsal.ProofTitle"] = "Receipt sent - click to manage",
        ["Futsal.ProofSent"] = "Receipt sent",
        ["Futsal.NoProofTitle"] = "No receipt - click to mark paid",
        ["Futsal.GatewayPaidTitle"] = "Paid via gateway — cannot be undone by admin",
        ["Futsal.Receiver"] = "receiver",

        // Actions
        ["Futsal.Remove"] = "remove",
        ["Futsal.RemoveConfirm"] = "remove?",
        ["Futsal.Cancel"] = "cancel",
        ["Futsal.CancelSignupConfirm"] = "cancel signup?",
        ["Futsal.Waitlist"] = "Join waitlist",
        ["Futsal.WaitlistGk"] = "Join goalkeeper waitlist",
        ["Futsal.WaitlistLine"] = "Join outfield waitlist",
        ["Futsal.RemoveSlot"] = "Remove slot",
        ["Futsal.AddSlot"] = "Add slot",
        ["Futsal.RemoveSlotGk"] = "Remove goalkeeper slot",
        ["Futsal.AddSlotGk"] = "Add goalkeeper slot",
        ["Futsal.RemoveSlotLine"] = "Remove outfield slot",
        ["Futsal.AddSlotLine"] = "Add outfield slot",

        // Confirmed banner
        ["Futsal.ConfirmedToPlay"] = "Confirmed to play in",
        ["Futsal.Gol"] = "GK",
        ["Futsal.Linha"] = "OUT",
        ["Futsal.PaidAmount"] = "Paid R$ {0}",
        ["Futsal.PayAmount"] = "Pay R$ {0}",

        // Private group
        ["Futsal.JoinRequestSent"] = "Request sent — awaiting group admin approval.",
        ["Futsal.CancelJoinRequest"] = "Cancel request",
        ["Futsal.CancellingJoin"] = "Cancelling…",
        ["Futsal.JoinRequestRejected"] = "Your join request was rejected.",
        ["Futsal.PrivateGroup"] = "This group is private. Request entry from the admin.",
        ["Futsal.RequestJoin"] = "Request join",
        ["Futsal.SendingJoin"] = "Sending...",

        // Escalacao
        ["Futsal.EscalacaoNotAvailable"] = "Lineup not available",
        ["Futsal.EscalacaoNotMounted"] = "The lineup has not yet been set by the organizer.",
        ["Futsal.BackToMatch"] = "Back to match",
        ["Futsal.PostMatchOnlyMembers"] = "Only group members can view the summary and vote for the highlight.",
        ["Futsal.MontarEscalacao"] = "Build Lineup",
        ["Futsal.VerEscalacao"] = "View Lineup",
        ["Futsal.EscalacaoConfirmedAt"] = "Lineup confirmed at {0}",
        ["Futsal.ResetEscalacao"] = "Reset lineup",
        ["Futsal.ResetConfirm"] = "Are you sure? The lineup will be undone and players will have no team assigned again.",
        ["Futsal.Resetting"] = "Resetting…",
        ["Futsal.SimResetar"] = "Yes, reset",
        ["Futsal.ShufflePlayers"] = "Shuffle outfield players",
        ["Futsal.ConfirmEscalacao"] = "Confirm lineup",
        ["Futsal.TeamsUnbalanced"] = "Unbalanced teams — balance the outfield players to confirm.",
        ["Futsal.ConfirmEscalacaoModal"] = "Confirm this lineup? The teams will be visible to all confirmed players.",
        ["Futsal.SimConfirmar"] = "Yes, confirm",

        // Escalacao share
        ["Futsal.Copied"] = "Copied!",
        ["Futsal.CopyEscalacao"] = "Copy lineup",
        ["Futsal.ShareWhatsApp"] = "Share on WhatsApp",

        // Escalacao score
        ["Futsal.Score"] = "Score",
        ["Futsal.TeamWon"] = "🏆 {0} won!",
        ["Futsal.Draw"] = "🤝 Draw",
        ["Futsal.RegisteredBy"] = "Registered by {0}",
        ["Futsal.RegisteredAt"] = "at {0}",
        ["Futsal.ConfirmScore"] = "Confirm score",
        ["Futsal.ScoreNotRegistered"] = "Score not yet registered.",

        // Quorum
        ["Futsal.MatchEnded"] = "Match ended",
        ["Futsal.QuorumReached"] = "Minimum number of players reached",
        ["Futsal.QuorumNeeded"] = "Minimum number of players is: {0} outfield + {1} goalkeeper(s)",
        ["Futsal.LackingPlayers"] = "{0} player(s) needed to reach the minimum required",

        // Location
        ["Futsal.Location"] = "Location",
        ["Futsal.LocationIframeTitle"] = "Court location",
        ["Futsal.OpenInMaps"] = "Open in Google Maps",

        // Form fields
        ["Futsal.Identity"] = "Match Identity",
        ["Futsal.MatchName"] = "Match name",
        ["Futsal.MatchNamePlaceholder"] = "Ex: \"Rachão da Galera do Zé\", \"Pelada de Quinta\"",
        ["Futsal.LocalNameLabel"] = "What do you call the game in your region?",
        ["Futsal.LocalNamePlaceholder"] = "racha, pelada, baba, rachão…",
        ["Futsal.LocalNameHint"] = "Optional — appears on cards to identify the regional style.",
        ["Futsal.Modality"] = "Modality",
        ["Futsal.ModalityFutsal"] = "Futsal",
        ["Futsal.ModalitySociety"] = "Fut7 / Society",
        ["Futsal.ModalityCampo"] = "Field",
        ["Futsal.Venue"] = "Venue",
        ["Futsal.VenueField"] = "Court / Society / Field",
        ["Futsal.VenueSelect"] = "— Select court —",
        ["Futsal.VenueSelectShort"] = "— select —",
        ["Futsal.NoVenueRegistered"] = "No court registered yet. Request the system admin.",
        ["Futsal.DateTime"] = "Date & Time",
        ["Futsal.Date"] = "Date",
        ["Futsal.StartTime"] = "Start time",
        ["Futsal.Duration"] = "Duration",
        ["Futsal.Slots"] = "Slots",
        ["Futsal.TotalSlots"] = "Total slots (outfield + goalkeepers)",
        ["Futsal.Goalkeepers"] = "Goalkeepers",
        ["Futsal.NoGkHint"] = "0 = no goalkeeper backup.",
        ["Futsal.RotateInGoal"] = "Rotate outfield players in goal",
        ["Futsal.Price"] = "Price",
        ["Futsal.PricePerPlayer"] = "Price per player (R$)",
        ["Futsal.PriceHint"] = "Use 0 for free matches.",
        ["Futsal.CancelMatch"] = "Cancel match",
        ["Futsal.CancelMatchConfirm"] = "Are you sure? All confirmed players will be notified.",
        ["Futsal.No"] = "No",
        ["Futsal.SimCancelar"] = "Yes, cancel",

        // Schedule
        ["Futsal.WeeklyMatches"] = "Weekly Matches",
        ["Futsal.LoadingWeekly"] = "Loading your weekly matches…",
        ["Futsal.NoWeeklyMatches"] = "No weekly matches registered.",
        ["Futsal.NoWeeklyHint"] = "Create a weekly match to generate matches automatically every week.",
        ["Futsal.Inactive"] = "Inactive",
        ["Futsal.Players"] = "players",
        ["Futsal.GoalkeepersShort"] = "goalkeepers",
        ["Futsal.Next"] = "Next: {0}",
        ["Futsal.ConfirmedCount"] = "confirmed",
        ["Futsal.NoFutureMatch"] = "No future match generated.",
        ["Futsal.Deactivate"] = "Deactivate",
        ["Futsal.Reactivate"] = "Reactivate",
        ["Futsal.ScheduleWarning"] = "⚠️ Changes here do not affect already generated matches — only upcoming occurrences.",
        ["Futsal.Identification"] = "Identification",
        ["Futsal.Schedule"] = "Schedule",
        ["Futsal.DayOfWeek"] = "Day of the week",
        ["Futsal.Create.PixRequired"] = "Set up your Pix key in the profile before creating a match with a price.",

        // Futsal components (C28 migration)
        ["Futsal.WaitlistTitle"] = "Waitlist",
        ["Futsal.Reserve"] = "Reserve",
        ["Futsal.MatchHighlight"] = "Match Highlight",
        ["Futsal.DaysOfWeek"] = "Days of the week",
    };

    /// <summary>ES-ES Spanish (Spain) strings</summary>
    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Futsal.PageTitle"] = "Partido",
        ["Futsal.CreatePageTitle"] = "Crear Partido · Futsal · Confirmai",
        ["Futsal.EditPageTitle"] = "Editar Partido · Futsal · Confirmai",
        ["Futsal.ScheduleEditPageTitle"] = "Editar Partido Semanal · Confirmai",
        ["Futsal.ScheduleIndexPageTitle"] = "Partidos Semanales — Confirmai",
        ["Futsal.EscalacaoPageTitle"] = "Alineación",
        ["Futsal.PostMatchPageTitle"] = "Post-Partido",

        // Common match strings
        ["Futsal.MatchNotFound"] = "Partido no encontrado.",
        ["Futsal.ScheduleNotFound"] = "Programación no encontrada.",
        ["Futsal.AccessDenied"] = "Acceso denegado.",
        ["Futsal.OnlyOrganizerCanEdit"] = "Solo el organizador puede editar este partido.",
        ["Futsal.OnlyCreatorCanEditSchedule"] = "Solo el creador puede editar esta programación.",
        ["Futsal.MatchCancelled"] = "Este partido ha sido cancelado.",
        ["Futsal.EnterToConfirm"] = "Unirse para confirmar asistencia",
        ["Futsal.ConfirmPresence"] = "Confirmar asistencia",
        ["Futsal.NewMatch"] = "Nuevo Partido",
        ["Futsal.NewMatchFutsal"] = "Nuevo Partido de Futsal",
        ["Futsal.NewMatchGroup"] = "Nuevo Partido — {0}",
        ["Futsal.CreateMatch"] = "Crear Partido",
        ["Futsal.Creating"] = "Creando…",
        ["Futsal.EditMatch"] = "Editar Partido",
        ["Futsal.SaveChanges"] = "Guardar Cambios",
        ["Futsal.Saving"] = "Guardando…",

        // Player tags
        ["Futsal.Player"] = "Jugador",
        ["Futsal.Goalkeeper"] = "Portero",
        ["Futsal.You"] = "Tú",
        ["Futsal.Mvp"] = "⭐ Destacado",
        ["Futsal.NoPay"] = "no paga",
        ["Futsal.Paid"] = "pagado",
        ["Futsal.Pending"] = "pendiente",
        ["Futsal.Pay"] = "pagar",
        ["Futsal.MarkPaid"] = "marcar pagado?",
        ["Futsal.UnmarkPaid"] = "desmarcar?",
        ["Futsal.Proof"] = "📎 comprobante",
        ["Futsal.ProofTitle"] = "Comprobante enviado - haz clic para gestionar",
        ["Futsal.ProofSent"] = "Comprobante enviado",
        ["Futsal.NoProofTitle"] = "Sin comprobante - haz clic para marcar pagado",
        ["Futsal.GatewayPaidTitle"] = "Pagado vía gateway — no puede ser deshecho por el admin",
        ["Futsal.Receiver"] = "receptor",

        // Actions
        ["Futsal.Remove"] = "eliminar",
        ["Futsal.RemoveConfirm"] = "eliminar?",
        ["Futsal.Cancel"] = "cancelar",
        ["Futsal.CancelSignupConfirm"] = "cancelar inscripción?",
        ["Futsal.Waitlist"] = "Unirse a lista de espera",
        ["Futsal.WaitlistGk"] = "Unirse a lista de espera de porteros",
        ["Futsal.WaitlistLine"] = "Unirse a lista de espera de línea",
        ["Futsal.RemoveSlot"] = "Eliminar plaza",
        ["Futsal.AddSlot"] = "Añadir plaza",
        ["Futsal.RemoveSlotGk"] = "Eliminar plaza de portero",
        ["Futsal.AddSlotGk"] = "Añadir plaza de portero",
        ["Futsal.RemoveSlotLine"] = "Eliminar plaza de línea",
        ["Futsal.AddSlotLine"] = "Añadir plaza de línea",

        // Confirmed banner
        ["Futsal.ConfirmedToPlay"] = "Confirmado para jugar en",
        ["Futsal.Gol"] = "POR",
        ["Futsal.Linha"] = "LIN",
        ["Futsal.PaidAmount"] = "Pagado R$ {0}",
        ["Futsal.PayAmount"] = "Pagar R$ {0}",

        // Private group
        ["Futsal.JoinRequestSent"] = "Solicitud enviada — esperando aprobación del administrador del grupo.",
        ["Futsal.CancelJoinRequest"] = "Cancelar solicitud",
        ["Futsal.CancellingJoin"] = "Cancelando…",
        ["Futsal.JoinRequestRejected"] = "Tu solicitud de entrada fue rechazada.",
        ["Futsal.PrivateGroup"] = "Este grupo es privado. Solicita entrada al administrador.",
        ["Futsal.RequestJoin"] = "Solicitar entrada",
        ["Futsal.SendingJoin"] = "Enviando...",

        // Escalacao
        ["Futsal.EscalacaoNotAvailable"] = "Alineación no disponible",
        ["Futsal.EscalacaoNotMounted"] = "La alineación aún no ha sido montada por el organizador.",
        ["Futsal.BackToMatch"] = "Volver al partido",
        ["Futsal.PostMatchOnlyMembers"] = "Solo los miembros del grupo pueden ver el resumen y votar por el destacado.",
        ["Futsal.MontarEscalacao"] = "Montar Alineación",
        ["Futsal.VerEscalacao"] = "Ver Alineación",
        ["Futsal.EscalacaoConfirmedAt"] = "Alineación confirmada en {0}",
        ["Futsal.ResetEscalacao"] = "Reiniciar alineación",
        ["Futsal.ResetConfirm"] = "¿Estás seguro? La alineación se deshará y los jugadores volverán a no tener equipo asignado.",
        ["Futsal.Resetting"] = "Reiniciando…",
        ["Futsal.SimResetar"] = "Sí, reiniciar",
        ["Futsal.ShufflePlayers"] = "Barajar jugadores de línea",
        ["Futsal.ConfirmEscalacao"] = "Confirmar alineación",
        ["Futsal.TeamsUnbalanced"] = "Equipos desiguales — equilibra los jugadores de línea para confirmar.",
        ["Futsal.ConfirmEscalacaoModal"] = "¿Confirmar esta alineación? Los equipos serán visibles para todos los confirmados.",
        ["Futsal.SimConfirmar"] = "Sí, confirmar",

        // Escalacao share
        ["Futsal.Copied"] = "¡Copiado!",
        ["Futsal.CopyEscalacao"] = "Copiar alineación",
        ["Futsal.ShareWhatsApp"] = "Compartir en WhatsApp",

        // Escalacao score
        ["Futsal.Score"] = "Marcador",
        ["Futsal.TeamWon"] = "🏆 {0} ganó!",
        ["Futsal.Draw"] = "🤝 Empate",
        ["Futsal.RegisteredBy"] = "Registrado por {0}",
        ["Futsal.RegisteredAt"] = "en {0}",
        ["Futsal.ConfirmScore"] = "Confirmar marcador",
        ["Futsal.ScoreNotRegistered"] = "Marcador aún no registrado.",

        // Quorum
        ["Futsal.MatchEnded"] = "Partido finalizado",
        ["Futsal.QuorumReached"] = "Número mínimo de jugadores alcanzado",
        ["Futsal.QuorumNeeded"] = "Número mínimo de jugadores es: {0} de línea + {1} portero(s)",
        ["Futsal.LackingPlayers"] = "Faltan {0} jugador(es) para alcanzar el mínimo necesario",

        // Location
        ["Futsal.Location"] = "Ubicación",
        ["Futsal.LocationIframeTitle"] = "Ubicación de la cancha",
        ["Futsal.OpenInMaps"] = "Abrir en Google Maps",

        // Form fields
        ["Futsal.Identity"] = "Identidad del Partido",
        ["Futsal.MatchName"] = "Nombre del partido",
        ["Futsal.MatchNamePlaceholder"] = "Ex: \"Rachão da Galera do Zé\", \"Pelada de Quinta\"",
        ["Futsal.LocalNameLabel"] = "¿Cómo llaman al juego en su región?",
        ["Futsal.LocalNamePlaceholder"] = "racha, pelada, baba, rachão…",
        ["Futsal.LocalNameHint"] = "Opcional — aparece en las tarjetas para identificar el estilo regional.",
        ["Futsal.Modality"] = "Modalidad",
        ["Futsal.ModalityFutsal"] = "Futsal",
        ["Futsal.ModalitySociety"] = "Fut7 / Society",
        ["Futsal.ModalityCampo"] = "Campo",
        ["Futsal.Venue"] = "Lugar",
        ["Futsal.VenueField"] = "Cancha / Society / Campo",
        ["Futsal.VenueSelect"] = "— Seleccione cancha —",
        ["Futsal.VenueSelectShort"] = "— seleccione —",
        ["Futsal.NoVenueRegistered"] = "Ninguna cancha registrada todavía. Solicítelo al administrador del sistema.",
        ["Futsal.DateTime"] = "Fecha y Hora",
        ["Futsal.Date"] = "Fecha",
        ["Futsal.StartTime"] = "Hora de inicio",
        ["Futsal.Duration"] = "Duración",
        ["Futsal.Slots"] = "Plazas",
        ["Futsal.TotalSlots"] = "Plazas totales (línea + porteros)",
        ["Futsal.Goalkeepers"] = "Porteros",
        ["Futsal.NoGkHint"] = "0 = sin reserva de portero.",
        ["Futsal.RotateInGoal"] = "Rotar jugadores de línea en la portería",
        ["Futsal.Price"] = "Precio",
        ["Futsal.PricePerPlayer"] = "Precio por jugador (R$)",
        ["Futsal.PriceHint"] = "Usa 0 para partidos sin cobro.",
        ["Futsal.CancelMatch"] = "Cancelar partido",
        ["Futsal.CancelMatchConfirm"] = "¿Estás seguro? Todos los confirmados serán avisados.",
        ["Futsal.No"] = "No",
        ["Futsal.SimCancelar"] = "Sí, cancelar",

        // Schedule
        ["Futsal.WeeklyMatches"] = "Partidos Semanales",
        ["Futsal.LoadingWeekly"] = "Cargando tus partidos semanales…",
        ["Futsal.NoWeeklyMatches"] = "Ningún partido semanal registrado.",
        ["Futsal.NoWeeklyHint"] = "Crea un partido semanal para generar partidos automáticamente cada semana.",
        ["Futsal.Inactive"] = "Inactiva",
        ["Futsal.Players"] = "jugadores",
        ["Futsal.GoalkeepersShort"] = "porteros",
        ["Futsal.Next"] = "Próxima: {0}",
        ["Futsal.ConfirmedCount"] = "confirmados",
        ["Futsal.NoFutureMatch"] = "Ningún partido futuro generado.",
        ["Futsal.Deactivate"] = "Desactivar",
        ["Futsal.Reactivate"] = "Reactivar",
        ["Futsal.ScheduleWarning"] = "⚠️ Los cambios aquí no afectan a los partidos ya generados — solo las próximas ocurrencias.",
        ["Futsal.Identification"] = "Identificación",
        ["Futsal.Schedule"] = "Horario",
        ["Futsal.DayOfWeek"] = "Día de la semana",
        ["Futsal.Create.PixRequired"] = "Configura tu clave Pix en el perfil antes de crear un partido con precio.",

        // Futsal components (C28 migration)
        ["Futsal.WaitlistTitle"] = "Lista de espera",
        ["Futsal.Reserve"] = "Reserva",
        ["Futsal.MatchHighlight"] = "Destaque de la Partida",
        ["Futsal.DaysOfWeek"] = "Días de la semana",
    };

    /// <summary>Get combined dictionary for all languages</summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
