namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Group UI text domain: group detail, create, join, features, payments, ranking, partidas, components.
/// </summary>
internal static class GroupTexts
{
    /// <summary>PT-BR Portuguese (Brazil) strings</summary>
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Group.PageTitle"] = "Grupo",
        ["Group.CreatePageTitle"] = "Criar Grupo — Confirmai",
        ["Group.InvitePageTitle"] = "Convite",
        ["Group.ConfigPageTitle"] = "Configurações — {0}",
        ["Group.PaymentsPageTitle"] = "Pagamentos — {0}",
        ["Group.RankingPageTitle"] = "Ranking — {0}",
        ["Group.PartidasPageTitle"] = "Partidas — {0}",

        // Common
        ["Group.NotFound"] = "Grupo não encontrado.",
        ["Group.NotAuthorized"] = "Acesso não autorizado.",
        ["Group.FeatureNotEnabled"] = "Funcionalidade não habilitada.",
        ["Group.Inactive"] = "Grupo inativo.",
        ["Group.BackToGroup"] = "← Voltar ao grupo",
        ["Group.BackToStart"] = "← Voltar ao início",
        ["Group.Member"] = "Membro",
        ["Group.You"] = "Você",
        ["Group.Admin"] = "admin",
        ["Group.Creator"] = "criador",
        ["Group.InactiveTag"] = "inativo",
        ["Group.SportFutsal"] = "⚽ Futsal",
        ["Group.SportPoker"] = "🃏 Poker",

        // Index page
        ["Group.JoinCodeHint"] = "Use um código de convite ou crie um novo grupo para começar.",
        ["Group.Approve"] = "Aprovar",
        ["Group.PendingSingular"] = "pendente",
        ["Group.PendingPlural"] = "pendentes",
        ["Group.PixPending"] = "⚠ Pix pendente",
        ["Group.PixPendingTitle"] = "Nenhum admin tem chave Pix cadastrada",
        ["Group.NoMatchScheduled"] = "Sem partida agendada",
        ["Group.MembersSingular"] = "membro",
        ["Group.MembersPlural"] = "membros",
        ["Group.Weekly"] = "Semanal",
        ["Group.WeeklyTitle"] = "Partida semanal automática",

        // Detail page
        ["Group.InviteLink"] = "Link de convite:",
        ["Group.Code"] = "Código:",
        ["Group.Copy"] = "Copiar",
        ["Group.Copied"] = "Copiado!",
        ["Group.Invite"] = "Convidar",
        ["Group.Settings"] = "Configurações",
        ["Group.Metrics"] = "Métricas",
        ["Group.Members"] = "Membros",
        ["Group.PartidasLink"] = "Partidas",
        ["Group.RankingLink"] = "Ranking",
        ["Group.PaymentsLink"] = "Pagamentos",
        ["Group.PixNotConfigured"] = "Pix do organizador não configurado",
        ["Group.PixNotConfiguredDesc"] = "Nenhum administrador do grupo possui chave Pix cadastrada. Os participantes não terão opção de pagamento manual por Pix.",
        ["Group.ConfigureNow"] = "Configurar agora →",
        ["Group.JoinRequestSent"] = "Solicitação enviada — aguardando aprovação do administrador.",
        ["Group.CancelJoinRequest"] = "Cancelar solicitação",
        ["Group.CancellingJoin"] = "Cancelando…",
        ["Group.JoinRequestRejected"] = "Sua solicitação foi recusada.",
        ["Group.NotMemberInfo"] = "Você não é membro deste grupo. Solicite entrada ou peça o código de convite ao organizador.",
        ["Group.RequestJoin"] = "Solicitar entrada",
        ["Group.SendingJoin"] = "Enviando…",

        // Create page
        ["Group.NewGroup"] = "Novo Grupo",
        ["Group.CreateInfoBox"] = "Crie um grupo e convide jogadores para participarem das partidas!",
        ["Group.GroupIdentity"] = "Identidade do Grupo",
        ["Group.Sport"] = "Esporte",
        ["Group.SportFutsalOption"] = "Futsal / Futebol",
        ["Group.SportPokerOption"] = "Poker",
        ["Group.GroupName"] = "Nome do grupo",
        ["Group.GroupLogo"] = "Logo/Imagem do grupo",
        ["Group.NoImageSelected"] = "Nenhuma imagem selecionada",
        ["Group.SelectImage"] = "Selecionar imagem",
        ["Group.UploadHint"] = "PNG, JPG ou WebP • Máximo 5 MB",
        ["Group.Logo.Selected"] = "Imagem selecionada com sucesso!",
        ["Group.Logo.InvalidFormat"] = "Formato inválido. Use PNG, JPG ou WebP.",
        ["Group.Logo.TooLarge"] = "Arquivo muito grande. Máximo 5 MB.",
        ["Group.Logo.ProcessError"] = "Erro ao processar imagem.",
        ["Group.Location"] = "Localização",
        ["Group.SelectUF"] = "— Selecione —",
        ["Group.ForeignUF"] = "EX — Estrangeiro",
        ["Group.SelectCity"] = "Selecione a UF",
        ["Group.CreateButton"] = "Criar Grupo",
        ["Group.Creating"] = "Criando…",
        ["Group.AuthRequired"] = "Você precisa estar autenticado.",

        // Join page
        ["Group.InvalidInvite"] = "Convite inválido ou expirado.",
        ["Group.Home"] = "Início",
        ["Group.EnterToJoin"] = "Entrar para participar do grupo",
        ["Group.AlreadyMember"] = "Você já é membro deste grupo.",
        ["Group.ViewGroup"] = "Ver grupo",
        ["Group.JoinedGroup"] = "Você entrou no grupo {0}!",
        ["Group.JoinGroupBtn"] = "Entrar no grupo",
        ["Group.Cancelled"] = "cancelado",
        ["Group.Full"] = "lotado",
        ["Group.Open"] = "aberto",
        ["Group.DateTimeHeader"] = "Data/Hora",
        ["Group.PlayersHeader"] = "Jogadores",
        ["Group.StatusHeader"] = "Status",
        ["Group.PlayersHeader"] = "Jogadores",
        ["Group.SubNavLabel"] = "Navegação do grupo",
        ["Group.NavOverview"] = "Visão geral",
        ["Group.Access"] = "Acessar",
        ["Group.NextMatch"] = "Próxima partida",
        ["Group.ConfirmPresence"] = "Confirmar presença",
        ["Group.CreateFirstMatch"] = "Criar a primeira partida",
        ["Group.NoMatchOrganizer"] = "O organizador ainda não marcou a próxima partida.",
        ["Group.EventCancelled"] = "cancelada",
        ["Group.EventFull"] = "cheia",
        ["Group.EventOpen"] = "aberto",
        ["Group.EventNext"] = "próxima",
        ["Group.JoinError"] = "Erro ao entrar no grupo. Tente novamente.",

        // Features page
        ["Group.ConfigTitle"] = "Configurações do grupo",
        ["Group.RankingPostMatchEnabled"] = "Ranking pós-partida ativado.",
        ["Group.RankingPostMatchDisabled"] = "Ranking pós-partida desativado.",
        ["Group.BestPlayerVotingEnabled"] = "Votação melhor da partida ativada.",
        ["Group.BestPlayerVotingDisabled"] = "Votação melhor da partida desativada.",
        ["Group.SaveError"] = "Erro ao salvar. Tente novamente.",

        // FeaturesToggles component
        ["Group.PaymentsSection"] = "Pagamentos",
        ["Group.PaymentsSectionSub"] = "Escolha como os jogadores pagam as partidas deste grupo.",
        ["Group.GatewayTitle"] = "Intermédio do site (Gateways de pagamento)",
        ["Group.GatewayDesc"] = "Quando ativado, o pagamento das partidas é processado via gateways (EfiBank, Abacate e futuras integrações) com repasse automático ao organizador. Desativar significa pagamento via Pix direto ao organizador, mas funcionalidades adicionais como ranking e votação do melhor da partida ficam indisponíveis.",
        ["Group.NoGateway"] = "Nenhum gateway está disponível no momento. Habilite/configure em Admin > Gateways.",
        ["Group.AvailableNow"] = "Disponíveis agora: {0}",
        ["Group.Activate"] = "Ativar",
        ["Group.Deactivate"] = "Desativar",
        ["Group.AdditionalFeatures"] = "Funcionalidades adicionais",
        ["Group.AdditionalFeaturesSub"] = "Ative ou desative funcionalidades opcionais para este grupo.",
        ["Group.RankingPostMatch"] = "Ranking pós-partida",
        ["Group.RankingPostMatchDesc"] = "Exibe um ranking de participações e desempenho dos membros, com visões mensal e anual, na página do grupo.",
        ["Group.RequiresGateways"] = "Requer intermédio do site (gateways) ativado.",
        ["Group.BestPlayerVoting"] = "Votação melhor da partida",
        ["Group.BestPlayerVotingDesc"] = "Permite que os membros votem no melhor jogador da partida após o encerramento do evento.",

        // MembersManager component
        ["Group.MembersPermissions"] = "Membros & Permissões",
        ["Group.MembersPermissionsSub"] = "Promova membros a admin ou remova permissões de admin.",
        ["Group.OnlyCreatorCanManage"] = "Apenas o criador do grupo pode adicionar ou remover administradores.",
        ["Group.RemoveAdmin"] = "Remover admin",
        ["Group.MakeAdmin"] = "Tornar admin",
        ["Group.MakeAdminConfirm"] = "tornar admin?",
        ["Group.PromoteToAdmin"] = "Promover a admin",
        ["Group.MustHaveOneAdmin"] = "O grupo deve ter pelo menos um admin",
        ["Group.RemoveAdminTitle"] = "Remover permissão de admin",

        // PayoutAccountEditor component
        ["Group.PayoutTitle"] = "Chave PIX de Repasse (Taxa de Serviço)",
        ["Group.PayoutSub"] = "Configure a chave PIX do organizador para receber o valor das partidas (após dedução da taxa de serviço). Esta chave será usada para envio automático via API quando pagamentos são confirmados.",
        ["Group.PayoutRegistered"] = "Chave cadastrada:",
        ["Group.PayoutBeneficiary"] = "Beneficiário: {0}",
        ["Group.PixKeyType"] = "Tipo de chave:",
        ["Group.PixKey"] = "Chave PIX:",
        ["Group.PixKeyPlaceholder"] = "Digite a chave PIX",
        ["Group.BeneficiaryName"] = "Nome do beneficiário:",
        ["Group.BeneficiaryNamePlaceholder"] = "Nome completo ou razão social",
        ["Group.BeneficiaryCpf"] = "CPF do beneficiário:",
        ["Group.BankAccountNumber"] = "Número da conta bancária:",
        ["Group.BankAccountPlaceholder"] = "Número da conta (sem dígito)",
        ["Group.TestData"] = "Dados de teste",
        ["Group.PayoutSaving"] = "Salvando…",
        ["Group.PixKeyRandom"] = "Chave Aleatória",
        ["Group.PixKeyTypeUnknown"] = "Desconhecido",
        ["Group.PayoutTestBeneficiaryName"] = "Organizador Teste",
        ["Group.PixKeyRequired"] = "A chave PIX é obrigatória.",
        ["Group.BeneficiaryNameRequired"] = "O nome do beneficiário é obrigatório.",
        ["Group.BeneficiaryCpfRequired"] = "O CPF do beneficiário é obrigatório.",
        ["Group.BankAccountRequired"] = "O número da conta é obrigatório.",

        // Payments page
        ["Group.PaymentsTitle"] = "Pagamentos",
        ["Group.MyPaymentsTitle"] = "Meus pagamentos",
        ["Group.MyPaymentsEmpty"] = "Você não tem pagamentos neste grupo.",
        ["Group.MyPaymentPaid"] = "Pago",
        ["Group.MyPaymentPending"] = "Pendente",
        ["Group.MyPaymentProofSent"] = "Comprovante em análise",
        ["Group.MyPaymentPay"] = "Pagar",
        ["Group.MyPaymentsToPay"] = "A pagar",
        ["Group.MyPaymentsInReview"] = "Em análise",
        ["Group.MyPaymentsPaid"] = "Pagos",
        ["Group.MyPaymentsTotalDue"] = "Total a pagar",
        ["Group.PaymentsPending"] = "Pendentes",
        ["Group.PaymentsHistory"] = "Histórico",
        ["Group.PaymentsProofs"] = "Comprovantes",
        ["Group.PaymentsProofsEmpty"] = "Nenhum comprovante aguardando revisão.",
        ["Group.PaymentsProofPlayer"] = "Jogador",
        ["Group.PaymentsProofMatch"] = "Partida",
        ["Group.PaymentsProofDate"] = "Data",
        ["Group.PaymentsProofAmount"] = "Valor",
        ["Group.PaymentsProofUploadedAt"] = "Enviado em",
        ["Group.PaymentsProofAccept"] = "Aceitar",
        ["Group.PaymentsProofReject"] = "Rejeitar",
        ["Group.PaymentsProofAcceptConfirm"] = "Confirmar este pagamento?",
        ["Group.PaymentsMarkPaidConfirm"] = "Tem certeza que deseja confirmar este pagamento?",
        ["Group.PaymentsProofRejectConfirm"] = "Rejeitar este comprovante? O jogador terá que enviar novamente.",
        ["Group.PaymentsProofAccepting"] = "Aceitando...",
        ["Group.PaymentsProofRejecting"] = "Rejeitando...",
        ["Group.PaymentsRefresh"] = "Recarregar lista",
        ["Group.PaymentsLoading"] = "Carregando…",
        ["Group.AllParticipants"] = "Todos os participantes",
        ["Group.NoManualPayments"] = "Nenhum pagamento manual registrado ainda.",
        ["Group.NoDelinquent"] = "Nenhum jogador inadimplente. Tudo em dia!",
        ["Group.PaymentSingular"] = "pagamento",
        ["Group.PaymentPlural"] = "pagamentos",
        ["Group.GameSingular"] = "jogo",
        ["Group.GamePlural"] = "jogos",
        ["Group.Notified"] = "Notificado",
        ["Group.NotifyEmail"] = "Enviar e-mail de cobrança",
        ["Group.NotifyWhatsApp"] = "Cobrar via WhatsApp",
        ["Group.PendingMatches"] = "Partidas pendentes",
        ["Group.ViewProof"] = "Ver comprovante",
        ["Group.ViewMatch"] = "Ver partida",
        ["Group.ProofAlt"] = "Comprovante Pix",

        // Platform fee settlement tab (Fase A do Ciclo 27)
        ["Group.PlatformFeeTab"] = "Taxa da plataforma",
        ["Group.PlatformFeeTabTitle"] = "Repasse da taxa da plataforma",
        ["Group.PlatformFeeMatches"] = "Partidas com taxa",
        ["Group.PlatformFeeMatchesHint"] = "Selecione as partidas para fazer o repasse da taxa",
        ["Group.PlatformFeeMatchDate"] = "Data",
        ["Group.PlatformFeeMatchName"] = "Partida",
        ["Group.PlatformFeeMatchPlayers"] = "Pagantes",
        ["Group.PlatformFeeMatchFee"] = "Taxa",
        ["Group.PlatformFeeMatchStatus"] = "Status",
        ["Group.PlatformFeeMatchTotal"] = "Total",
        ["Group.PlatformFeeStatusPending"] = "Pendente",
        ["Group.PlatformFeeStatusPaid"] = "Pago",
        ["Group.PlatformFeeSummary"] = "Resumo do repasse",
        ["Group.PlatformFeeToSettle"] = "A repassar",
        ["Group.PlatformFeeAccrued"] = "Acumulado",
        ["Group.PlatformFeeInAnalysis"] = "Em análise",
        ["Group.PlatformFeeSettled"] = "Ja repassado",
        ["Group.PlatformFeePlatformPix"] = "Chave Pix da plataforma",
        ["Group.PlatformFeePlatformPixHint"] = "Transfira o valor a repassar para a chave Pix da plataforma abaixo e anexe o comprovante.",
        ["Group.PlatformFeeNoPixConfigured"] = "A chave Pix da plataforma não está configurada. Contate o administrador do sistema.",
        ["Group.PlatformFeeSubmit"] = "Enviar comprovante do repasse",
        ["Group.PlatformFeeSubmitAmount"] = "Valor do repasse (R$)",
        ["Group.PlatformFeeFillDue"] = "Total a repassar",
        ["Group.PlatformFeeSelectMatches"] = "Selecione ao menos uma partida para repassar.",
        ["Group.PlatformFeeSelectAll"] = "Selecionar todas",
        ["Group.PlatformFeeClearSelection"] = "Limpar seleção",
        ["Group.PlatformFeeSelectedAmount"] = "Total selecionado",
        ["Group.PlatformFeeSend"] = "Enviar comprovante",
        ["Group.PlatformFeeConfirmTitle"] = "Confirmar envio do repasse",
        ["Group.PlatformFeeConfirmMessage"] = "Voce confirma o envio do comprovante de {0} para quitar {1} partida(s)?",
        ["Group.PlatformFeeConfirmSend"] = "Confirmar envio",
        ["Group.PlatformFeeSubmitProof"] = "Comprovante (JPG, PNG ou WebP até 5 MB)",
        ["Group.PlatformFeeSubmitting"] = "Enviando…",
        ["Group.PlatformFeeSubmitSuccess"] = "Repasse enviado com sucesso. Aguardando revisão do administrador.",
        ["Group.PlatformFeeSubmitError"] = "Erro ao enviar repasse. Tente novamente.",
        ["Group.PlatformFeeHistory"] = "Histórico de repasses",
        ["Group.PlatformFeeHistoryDate"] = "Enviado em",
        ["Group.PlatformFeeHistoryAmount"] = "Valor",
        ["Group.PlatformFeeHistoryStatus"] = "Status",
        ["Group.PlatformFeeHistoryNote"] = "Motivo",
        ["Group.PlatformFeeHistoryReviewedAt"] = "Revisado em",
        ["Group.PlatformFeeHistoryProof"] = "Ver comprovante",
        ["Group.PlatformFeeHistoryEmpty"] = "Nenhum repasse enviado ainda.",
        ["Group.PlatformFeeMatchesEmpty"] = "Nenhuma partida com taxa acumulada ainda.",
        ["Group.PlatformFeeProofAlt"] = "Comprovante do repasse",

        // Ranking page
        ["Group.RankingTitle"] = "Ranking",
        ["Group.RankingFootnote"] = "Contabiliza apenas partidas com data já encerrada.",

        // Partidas page
        ["Group.RecurringNotice"] = "Partidas geradas automaticamente (semanal)",

        // Group detail components (C28 migration)
        ["Group.NoMatchScheduledEmpty"] = "Nenhuma partida agendada.",
        ["Group.NoMatchPlayed"] = "Nenhuma partida realizada.",
        ["Group.NoMembers"] = "Sem membros.",
        ["Group.PaymentsRefreshShort"] = "Recarregar",
        ["Group.PlayerSentProof"] = "Jogador enviou comprovante",
        ["Group.PendingRequestUserFallback"] = "Usuário",
        ["Group.ApproveRequest"] = "Aprovar solicitação",
        ["Group.RejectRequest"] = "Rejeitar solicitação",
        ["Group.ApproveAll"] = "Aprovar todos",
        ["Group.Reject"] = "Recusar",
        ["Group.ActionsLabel"] = "Ações do grupo",
        ["Group.PaymentsUpToDate"] = "Em dia",
        ["Group.RankingSub"] = "Ver ranking",
        ["Group.SettingsSub"] = "Funcionalidades e membros",
        ["Group.InviteSub"] = "Enviar convite",
        ["Group.LoginToJoin"] = "Entrar para participar",
        ["Group.ShowLess"] = "Mostrar menos",
        ["Group.ViewAllMembers"] = "Ver todos ({0})",
        ["Group.MemberActions"] = "Ações do membro",
        ["Group.SortNameAZ"] = "Nome A-Z",
        ["Group.Selected"] = "selecionado",
        ["Group.Upcoming"] = "próximos",
        ["Group.AttendanceRate"] = "Taxa de Presença",
        ["Group.PendingRequestsLabel"] = "Solicitações Pendentes",
        ["Group.ActionNeeded"] = "Ação necessária",
        ["Group.NoFinishedMatches"] = "Nenhuma partida encerrada no período.",
        ["Group.Wins"] = "Vitórias",
        ["Group.RankingGames"] = "Partidas",
        ["Group.RankingHighlights"] = "Destaques",
        ["Group.WeeklyRecurrences"] = "Recorrências semanais",
    };

    /// <summary>EN-US English (United States) strings</summary>
    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Group.PageTitle"] = "Group",
        ["Group.CreatePageTitle"] = "Create Group — Confirmai",
        ["Group.InvitePageTitle"] = "Invite",
        ["Group.ConfigPageTitle"] = "Settings — {0}",
        ["Group.PaymentsPageTitle"] = "Payments — {0}",
        ["Group.RankingPageTitle"] = "Ranking — {0}",
        ["Group.PartidasPageTitle"] = "Matches — {0}",

        // Common
        ["Group.NotFound"] = "Group not found.",
        ["Group.NotAuthorized"] = "Access not authorized.",
        ["Group.FeatureNotEnabled"] = "Feature not enabled.",
        ["Group.Inactive"] = "Group inactive.",
        ["Group.BackToGroup"] = "← Back to group",
        ["Group.BackToStart"] = "← Back to start",
        ["Group.Member"] = "Member",
        ["Group.You"] = "You",
        ["Group.Admin"] = "admin",
        ["Group.Creator"] = "creator",
        ["Group.InactiveTag"] = "inactive",
        ["Group.SportFutsal"] = "⚽ Futsal",
        ["Group.SportPoker"] = "🃏 Poker",

        // Index page
        ["Group.JoinCodeHint"] = "Use an invite code or create a new group to get started.",
        ["Group.Approve"] = "Approve",
        ["Group.PendingSingular"] = "pending",
        ["Group.PendingPlural"] = "pending",
        ["Group.PixPending"] = "⚠ Pix pending",
        ["Group.PixPendingTitle"] = "No admin has a registered Pix key",
        ["Group.NoMatchScheduled"] = "No match scheduled",
        ["Group.MembersSingular"] = "member",
        ["Group.MembersPlural"] = "members",
        ["Group.Weekly"] = "Weekly",
        ["Group.WeeklyTitle"] = "Automatic weekly match",

        // Detail page
        ["Group.InviteLink"] = "Invite link:",
        ["Group.Code"] = "Code:",
        ["Group.Copy"] = "Copy",
        ["Group.Copied"] = "Copied!",
        ["Group.Invite"] = "Invite",
        ["Group.Settings"] = "Settings",
        ["Group.Metrics"] = "Metrics",
        ["Group.Members"] = "Members",
        ["Group.PartidasLink"] = "Matches",
        ["Group.RankingLink"] = "Ranking",
        ["Group.PaymentsLink"] = "Payments",
        ["Group.PixNotConfigured"] = "Organizer Pix not configured",
        ["Group.PixNotConfiguredDesc"] = "No group administrator has a registered Pix key. Participants will not have the option for manual payment via Pix.",
        ["Group.ConfigureNow"] = "Configure now →",
        ["Group.JoinRequestSent"] = "Request sent — awaiting administrator approval.",
        ["Group.CancelJoinRequest"] = "Cancel request",
        ["Group.CancellingJoin"] = "Cancelling…",
        ["Group.JoinRequestRejected"] = "Your request was rejected.",
        ["Group.NotMemberInfo"] = "You are not a member of this group. Request to join or ask the organizer for the invite code.",
        ["Group.RequestJoin"] = "Request to join",
        ["Group.SendingJoin"] = "Sending…",

        // Create page
        ["Group.NewGroup"] = "New Group",
        ["Group.CreateInfoBox"] = "Create a group and invite players to join the matches!",
        ["Group.GroupIdentity"] = "Group Identity",
        ["Group.Sport"] = "Sport",
        ["Group.SportFutsalOption"] = "Futsal / Soccer",
        ["Group.SportPokerOption"] = "Poker",
        ["Group.GroupName"] = "Group name",
        ["Group.GroupLogo"] = "Group logo/image",
        ["Group.NoImageSelected"] = "No image selected",
        ["Group.SelectImage"] = "Select image",
        ["Group.UploadHint"] = "PNG, JPG or WebP • Maximum 5 MB",
        ["Group.Logo.Selected"] = "Image selected successfully!",
        ["Group.Logo.InvalidFormat"] = "Invalid format. Use PNG, JPG or WebP.",
        ["Group.Logo.TooLarge"] = "File too large. Maximum 5 MB.",
        ["Group.Logo.ProcessError"] = "Error processing image.",
        ["Group.Location"] = "Location",
        ["Group.SelectUF"] = "— Select —",
        ["Group.ForeignUF"] = "EX — Foreign",
        ["Group.SelectCity"] = "Select UF",
        ["Group.CreateButton"] = "Create Group",
        ["Group.Creating"] = "Creating…",
        ["Group.AuthRequired"] = "You must be signed in.",

        // Join page
        ["Group.InvalidInvite"] = "Invalid or expired invite.",
        ["Group.Home"] = "Home",
        ["Group.EnterToJoin"] = "Join to participate in the group",
        ["Group.AlreadyMember"] = "You are already a member of this group.",
        ["Group.ViewGroup"] = "View group",
        ["Group.JoinedGroup"] = "You joined group {0}!",
        ["Group.JoinGroupBtn"] = "Join group",
        ["Group.Cancelled"] = "cancelled",
        ["Group.Full"] = "full",
        ["Group.Open"] = "open",
        ["Group.DateTimeHeader"] = "Date/Time",
        ["Group.PlayersHeader"] = "Players",
        ["Group.StatusHeader"] = "Status",
        ["Group.PlayersHeader"] = "Players",
        ["Group.SubNavLabel"] = "Group navigation",
        ["Group.NavOverview"] = "Overview",
        ["Group.Access"] = "Open",
        ["Group.NextMatch"] = "Next match",
        ["Group.ConfirmPresence"] = "Confirm attendance",
        ["Group.CreateFirstMatch"] = "Create the first match",
        ["Group.NoMatchOrganizer"] = "The organizer hasn't scheduled the next match yet.",
        ["Group.EventCancelled"] = "cancelled",
        ["Group.EventFull"] = "full",
        ["Group.EventOpen"] = "open",
        ["Group.EventNext"] = "next",
        ["Group.JoinError"] = "Error joining the group. Please try again.",

        // Features page
        ["Group.ConfigTitle"] = "Group settings",
        ["Group.RankingPostMatchEnabled"] = "Post-match ranking enabled.",
        ["Group.RankingPostMatchDisabled"] = "Post-match ranking disabled.",
        ["Group.BestPlayerVotingEnabled"] = "Best player voting enabled.",
        ["Group.BestPlayerVotingDisabled"] = "Best player voting disabled.",
        ["Group.SaveError"] = "Error saving. Please try again.",

        // FeaturesToggles component
        ["Group.PaymentsSection"] = "Payments",
        ["Group.PaymentsSectionSub"] = "Choose how players pay for matches in this group.",
        ["Group.GatewayTitle"] = "Site intermediary (Payment gateways)",
        ["Group.GatewayDesc"] = "When enabled, match payments are processed via gateways (EfiBank, Abacate and future integrations) with automatic payout to the organizer. Disabling means payment via direct Pix to the organizer, but additional features such as ranking and best player voting become unavailable.",
        ["Group.NoGateway"] = "No gateway is currently available. Enable/configure in Admin > Gateways.",
        ["Group.AvailableNow"] = "Available now: {0}",
        ["Group.Activate"] = "Activate",
        ["Group.Deactivate"] = "Deactivate",
        ["Group.AdditionalFeatures"] = "Additional features",
        ["Group.AdditionalFeaturesSub"] = "Enable or disable optional features for this group.",
        ["Group.RankingPostMatch"] = "Post-match ranking",
        ["Group.RankingPostMatchDesc"] = "Displays a ranking of member participation and performance, with monthly and yearly views, on the group page.",
        ["Group.RequiresGateways"] = "Requires site intermediary (gateways) enabled.",
        ["Group.BestPlayerVoting"] = "Best player voting",
        ["Group.BestPlayerVotingDesc"] = "Allows members to vote for the best player of the match after the event ends.",

        // MembersManager component
        ["Group.MembersPermissions"] = "Members & Permissions",
        ["Group.MembersPermissionsSub"] = "Promote members to admin or remove admin permissions.",
        ["Group.OnlyCreatorCanManage"] = "Only the group creator can add or remove administrators.",
        ["Group.RemoveAdmin"] = "Remove admin",
        ["Group.MakeAdmin"] = "Make admin",
        ["Group.MakeAdminConfirm"] = "make admin?",
        ["Group.PromoteToAdmin"] = "Promote to admin",
        ["Group.MustHaveOneAdmin"] = "The group must have at least one admin",
        ["Group.RemoveAdminTitle"] = "Remove admin permission",

        // PayoutAccountEditor component
        ["Group.PayoutTitle"] = "Pix Payout Key (Service Fee)",
        ["Group.PayoutSub"] = "Configure the organizer's Pix key to receive match amounts (after service fee deduction). This key will be used for automatic sending via API when payments are confirmed.",
        ["Group.PayoutRegistered"] = "Registered key:",
        ["Group.PayoutBeneficiary"] = "Beneficiary: {0}",
        ["Group.PixKeyType"] = "Key type:",
        ["Group.PixKey"] = "Pix key:",
        ["Group.PixKeyPlaceholder"] = "Enter the Pix key",
        ["Group.BeneficiaryName"] = "Beneficiary name:",
        ["Group.BeneficiaryNamePlaceholder"] = "Full name or legal entity name",
        ["Group.BeneficiaryCpf"] = "Beneficiary CPF:",
        ["Group.BankAccountNumber"] = "Bank account number:",
        ["Group.BankAccountPlaceholder"] = "Account number (without digit)",
        ["Group.TestData"] = "Test data",
        ["Group.PayoutSaving"] = "Saving…",
        ["Group.PixKeyRandom"] = "Random Key",
        ["Group.PixKeyTypeUnknown"] = "Unknown",
        ["Group.PayoutTestBeneficiaryName"] = "Test Organizer",
        ["Group.PixKeyRequired"] = "The Pix key is required.",
        ["Group.BeneficiaryNameRequired"] = "The beneficiary name is required.",
        ["Group.BeneficiaryCpfRequired"] = "The beneficiary CPF is required.",
        ["Group.BankAccountRequired"] = "The account number is required.",

        // Payments page
        ["Group.PaymentsTitle"] = "Payments",
        ["Group.MyPaymentsTitle"] = "My payments",
        ["Group.MyPaymentsEmpty"] = "You have no payments in this group.",
        ["Group.MyPaymentPaid"] = "Paid",
        ["Group.MyPaymentPending"] = "Pending",
        ["Group.MyPaymentProofSent"] = "Proof under review",
        ["Group.MyPaymentPay"] = "Pay",
        ["Group.MyPaymentsToPay"] = "To pay",
        ["Group.MyPaymentsInReview"] = "Under review",
        ["Group.MyPaymentsPaid"] = "Paid",
        ["Group.MyPaymentsTotalDue"] = "Total due",
        ["Group.PaymentsPending"] = "Pending",
        ["Group.PaymentsHistory"] = "History",
        ["Group.PaymentsProofs"] = "Proofs",
        ["Group.PaymentsProofsEmpty"] = "No proofs awaiting review.",
        ["Group.PaymentsProofPlayer"] = "Player",
        ["Group.PaymentsProofMatch"] = "Match",
        ["Group.PaymentsProofDate"] = "Date",
        ["Group.PaymentsProofAmount"] = "Amount",
        ["Group.PaymentsProofUploadedAt"] = "Uploaded at",
        ["Group.PaymentsProofAccept"] = "Accept",
        ["Group.PaymentsProofReject"] = "Reject",
        ["Group.PaymentsProofAcceptConfirm"] = "Confirm this payment?",
        ["Group.PaymentsMarkPaidConfirm"] = "Are you sure you want to confirm this payment?",
        ["Group.PaymentsProofRejectConfirm"] = "Reject this proof? The player will have to resend it.",
        ["Group.PaymentsProofAccepting"] = "Accepting...",
        ["Group.PaymentsProofRejecting"] = "Rejecting...",
        ["Group.PaymentsRefresh"] = "Reload list",
        ["Group.PaymentsLoading"] = "Loading…",
        ["Group.AllParticipants"] = "All participants",
        ["Group.NoManualPayments"] = "No manual payments registered yet.",
        ["Group.NoDelinquent"] = "No delinquent players. All up to date!",
        ["Group.PaymentSingular"] = "payment",
        ["Group.PaymentPlural"] = "payments",
        ["Group.GameSingular"] = "game",
        ["Group.GamePlural"] = "games",
        ["Group.Notified"] = "Notified",
        ["Group.NotifyEmail"] = "Send payment reminder email",
        ["Group.NotifyWhatsApp"] = "Charge via WhatsApp",
        ["Group.PendingMatches"] = "Pending matches",
        ["Group.ViewProof"] = "View proof",
        ["Group.ViewMatch"] = "View match",
        ["Group.ProofAlt"] = "Pix proof",

        // Platform fee settlement tab
        ["Group.PlatformFeeTab"] = "Platform fee",
        ["Group.PlatformFeeTabTitle"] = "Platform fee payout",
        ["Group.PlatformFeeMatches"] = "Matches with fee",
        ["Group.PlatformFeeMatchesHint"] = "Select matches to pay out the fee",
        ["Group.PlatformFeeMatchDate"] = "Date",
        ["Group.PlatformFeeMatchName"] = "Match",
        ["Group.PlatformFeeMatchPlayers"] = "Payers",
        ["Group.PlatformFeeMatchFee"] = "Fee",
        ["Group.PlatformFeeMatchStatus"] = "Status",
        ["Group.PlatformFeeMatchTotal"] = "Total",
        ["Group.PlatformFeeStatusPending"] = "Pending",
        ["Group.PlatformFeeStatusPaid"] = "Paid",
        ["Group.PlatformFeeSummary"] = "Payout summary",
        ["Group.PlatformFeeToSettle"] = "To pay out",
        ["Group.PlatformFeeAccrued"] = "Accrued",
        ["Group.PlatformFeeInAnalysis"] = "Under review",
        ["Group.PlatformFeeSettled"] = "Already paid out",
        ["Group.PlatformFeePlatformPix"] = "Platform Pix key",
        ["Group.PlatformFeePlatformPixHint"] = "Transfer the amount to pay out to the platform Pix key below and attach the proof.",
        ["Group.PlatformFeeNoPixConfigured"] = "The platform Pix key is not configured. Contact the system administrator.",
        ["Group.PlatformFeeSubmit"] = "Submit payout proof",
        ["Group.PlatformFeeSubmitAmount"] = "Payout amount (R$)",
        ["Group.PlatformFeeFillDue"] = "Total to pay out",
        ["Group.PlatformFeeSelectMatches"] = "Select at least one match to pay out.",
        ["Group.PlatformFeeSelectAll"] = "Select all",
        ["Group.PlatformFeeClearSelection"] = "Clear selection",
        ["Group.PlatformFeeSelectedAmount"] = "Selected total",
        ["Group.PlatformFeeSend"] = "Submit proof",
        ["Group.PlatformFeeConfirmTitle"] = "Confirm payout submission",
        ["Group.PlatformFeeConfirmMessage"] = "Do you confirm submitting the proof of {0} to settle {1} match(es)?",
        ["Group.PlatformFeeConfirmSend"] = "Confirm submission",
        ["Group.PlatformFeeSubmitProof"] = "Proof (JPG, PNG or WebP up to 5 MB)",
        ["Group.PlatformFeeSubmitting"] = "Submitting…",
        ["Group.PlatformFeeSubmitSuccess"] = "Payout submitted successfully. Awaiting administrator review.",
        ["Group.PlatformFeeSubmitError"] = "Error submitting payout. Try again.",
        ["Group.PlatformFeeHistory"] = "Payout history",
        ["Group.PlatformFeeHistoryDate"] = "Submitted at",
        ["Group.PlatformFeeHistoryAmount"] = "Amount",
        ["Group.PlatformFeeHistoryStatus"] = "Status",
        ["Group.PlatformFeeHistoryNote"] = "Reason",
        ["Group.PlatformFeeHistoryReviewedAt"] = "Reviewed at",
        ["Group.PlatformFeeHistoryProof"] = "View proof",
        ["Group.PlatformFeeHistoryEmpty"] = "No payouts submitted yet.",
        ["Group.PlatformFeeMatchesEmpty"] = "No matches with accrued fee yet.",
        ["Group.PlatformFeeProofAlt"] = "Payout proof",

        // Ranking page
        ["Group.RankingTitle"] = "Ranking",
        ["Group.RankingFootnote"] = "Counts only matches whose date has already ended.",

        // Partidas page
        ["Group.RecurringNotice"] = "Automatically generated matches (weekly)",

        // Group detail components (C28 migration)
        ["Group.NoMatchScheduledEmpty"] = "No matches scheduled.",
        ["Group.NoMatchPlayed"] = "No matches played.",
        ["Group.NoMembers"] = "No members.",
        ["Group.PaymentsRefreshShort"] = "Reload",
        ["Group.PlayerSentProof"] = "Player sent proof",
        ["Group.PendingRequestUserFallback"] = "User",
        ["Group.ApproveRequest"] = "Approve request",
        ["Group.RejectRequest"] = "Reject request",
        ["Group.ApproveAll"] = "Approve all",
        ["Group.Reject"] = "Decline",
        ["Group.ActionsLabel"] = "Group actions",
        ["Group.PaymentsUpToDate"] = "Up to date",
        ["Group.RankingSub"] = "View ranking",
        ["Group.SettingsSub"] = "Features and members",
        ["Group.InviteSub"] = "Send invite",
        ["Group.LoginToJoin"] = "Sign in to join",
        ["Group.ShowLess"] = "Show less",
        ["Group.ViewAllMembers"] = "View all ({0})",
        ["Group.MemberActions"] = "Member actions",
        ["Group.SortNameAZ"] = "Name A-Z",
        ["Group.Selected"] = "selected",
        ["Group.Upcoming"] = "upcoming",
        ["Group.AttendanceRate"] = "Attendance Rate",
        ["Group.PendingRequestsLabel"] = "Pending Requests",
        ["Group.ActionNeeded"] = "Action needed",
        ["Group.NoFinishedMatches"] = "No finished matches in the period.",
        ["Group.Wins"] = "Wins",
        ["Group.RankingGames"] = "Matches",
        ["Group.RankingHighlights"] = "Highlights",
        ["Group.WeeklyRecurrences"] = "Weekly recurrences",
    };

    /// <summary>ES-ES Spanish (Spain) strings</summary>
    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Page titles
        ["Group.PageTitle"] = "Grupo",
        ["Group.CreatePageTitle"] = "Crear Grupo — Confirmai",
        ["Group.InvitePageTitle"] = "Invitación",
        ["Group.ConfigPageTitle"] = "Configuraciones — {0}",
        ["Group.PaymentsPageTitle"] = "Pagos — {0}",
        ["Group.RankingPageTitle"] = "Ranking — {0}",
        ["Group.PartidasPageTitle"] = "Partidas — {0}",

        // Common
        ["Group.NotFound"] = "Grupo no encontrado.",
        ["Group.NotAuthorized"] = "Acceso no autorizado.",
        ["Group.FeatureNotEnabled"] = "Función no habilitada.",
        ["Group.Inactive"] = "Grupo inactivo.",
        ["Group.BackToGroup"] = "← Volver al grupo",
        ["Group.BackToStart"] = "← Volver al inicio",
        ["Group.Member"] = "Miembro",
        ["Group.You"] = "Tú",
        ["Group.Admin"] = "admin",
        ["Group.Creator"] = "creador",
        ["Group.InactiveTag"] = "inactivo",
        ["Group.SportFutsal"] = "⚽ Futsal",
        ["Group.SportPoker"] = "🃏 Poker",

        // Index page
        ["Group.JoinCodeHint"] = "Usa un código de invitación o crea un nuevo grupo para empezar.",
        ["Group.Approve"] = "Aprobar",
        ["Group.PendingSingular"] = "pendiente",
        ["Group.PendingPlural"] = "pendientes",
        ["Group.PixPending"] = "⚠ Pix pendiente",
        ["Group.PixPendingTitle"] = "Ningún admin tiene clave Pix registrada",
        ["Group.NoMatchScheduled"] = "Ninguna partida programada",
        ["Group.MembersSingular"] = "miembro",
        ["Group.MembersPlural"] = "miembros",
        ["Group.Weekly"] = "Semanal",
        ["Group.WeeklyTitle"] = "Partida semanal automática",

        // Detail page
        ["Group.InviteLink"] = "Enlace de invitación:",
        ["Group.Code"] = "Código:",
        ["Group.Copy"] = "Copiar",
        ["Group.Copied"] = "¡Copiado!",
        ["Group.Invite"] = "Invitar",
        ["Group.Settings"] = "Configuraciones",
        ["Group.Metrics"] = "Métricas",
        ["Group.Members"] = "Miembros",
        ["Group.PartidasLink"] = "Partidas",
        ["Group.RankingLink"] = "Ranking",
        ["Group.PaymentsLink"] = "Pagos",
        ["Group.PixNotConfigured"] = "Pix del organizador no configurado",
        ["Group.PixNotConfiguredDesc"] = "Ningún administrador del grupo tiene clave Pix registrada. Los participantes no tendrán opción de pago manual vía Pix.",
        ["Group.ConfigureNow"] = "Configurar ahora →",
        ["Group.JoinRequestSent"] = "Solicitud enviada — esperando aprobación del administrador.",
        ["Group.CancelJoinRequest"] = "Cancelar solicitud",
        ["Group.CancellingJoin"] = "Cancelando…",
        ["Group.JoinRequestRejected"] = "Tu solicitud fue rechazada.",
        ["Group.NotMemberInfo"] = "No eres miembro de este grupo. Solicita entrada o pide el código de invitación al organizador.",
        ["Group.RequestJoin"] = "Solicitar entrada",
        ["Group.SendingJoin"] = "Enviando…",

        // Create page
        ["Group.NewGroup"] = "Nuevo Grupo",
        ["Group.CreateInfoBox"] = "¡Crea un grupo e invita jugadores a participar en las partidas!",
        ["Group.GroupIdentity"] = "Identidad del Grupo",
        ["Group.Sport"] = "Deporte",
        ["Group.SportFutsalOption"] = "Futsal / Fútbol",
        ["Group.SportPokerOption"] = "Poker",
        ["Group.GroupName"] = "Nombre del grupo",
        ["Group.GroupLogo"] = "Logo/Imagen del grupo",
        ["Group.NoImageSelected"] = "Ninguna imagen seleccionada",
        ["Group.SelectImage"] = "Seleccionar imagen",
        ["Group.UploadHint"] = "PNG, JPG o WebP • Máximo 5 MB",
        ["Group.Logo.Selected"] = "Imagen seleccionada con éxito!",
        ["Group.Logo.InvalidFormat"] = "Formato inválido. Usa PNG, JPG o WebP.",
        ["Group.Logo.TooLarge"] = "Archivo muy grande. Máximo 5 MB.",
        ["Group.Logo.ProcessError"] = "Error al procesar imagen.",
        ["Group.Location"] = "Ubicación",
        ["Group.SelectUF"] = "— Seleccione —",
        ["Group.ForeignUF"] = "EX — Extranjero",
        ["Group.SelectCity"] = "Seleccione la UF",
        ["Group.CreateButton"] = "Crear Grupo",
        ["Group.Creating"] = "Creando…",
        ["Group.AuthRequired"] = "Debes estar autenticado.",

        // Join page
        ["Group.InvalidInvite"] = "Invitación inválida o expirada.",
        ["Group.Home"] = "Inicio",
        ["Group.EnterToJoin"] = "Entrar para participar del grupo",
        ["Group.AlreadyMember"] = "Ya eres miembro de este grupo.",
        ["Group.ViewGroup"] = "Ver grupo",
        ["Group.JoinedGroup"] = "¡Entraste al grupo {0}!",
        ["Group.JoinGroupBtn"] = "Entrar al grupo",
        ["Group.Cancelled"] = "cancelado",
        ["Group.Full"] = "lleno",
        ["Group.Open"] = "abierto",
        ["Group.DateTimeHeader"] = "Fecha/Hora",
        ["Group.PlayersHeader"] = "Jugadores",
        ["Group.StatusHeader"] = "Estado",
        ["Group.PlayersHeader"] = "Jugadores",
        ["Group.SubNavLabel"] = "Navegación del grupo",
        ["Group.NavOverview"] = "Resumen",
        ["Group.Access"] = "Abrir",
        ["Group.NextMatch"] = "Próximo partido",
        ["Group.ConfirmPresence"] = "Confirmar asistencia",
        ["Group.CreateFirstMatch"] = "Crear el primer partido",
        ["Group.NoMatchOrganizer"] = "El organizador aún no programó el próximo partido.",
        ["Group.EventCancelled"] = "cancelado",
        ["Group.EventFull"] = "lleno",
        ["Group.EventOpen"] = "abierto",
        ["Group.EventNext"] = "próximo",
        ["Group.JoinError"] = "Error al entrar en el grupo. Inténtalo de nuevo.",

        // Features page
        ["Group.ConfigTitle"] = "Configuraciones del grupo",
        ["Group.RankingPostMatchEnabled"] = "Ranking post-partida activado.",
        ["Group.RankingPostMatchDisabled"] = "Ranking post-partida desactivado.",
        ["Group.BestPlayerVotingEnabled"] = "Votación del mejor de la partida activada.",
        ["Group.BestPlayerVotingDisabled"] = "Votación del mejor de la partida desactivada.",
        ["Group.SaveError"] = "Error al guardar. Inténtalo de nuevo.",

        // FeaturesToggles component
        ["Group.PaymentsSection"] = "Pagos",
        ["Group.PaymentsSectionSub"] = "Elige cómo los jugadores pagan las partidas de este grupo.",
        ["Group.GatewayTitle"] = "Intermediario del sitio (Pasarelas de pago)",
        ["Group.GatewayDesc"] = "Cuando está activado, el pago de las partidas se procesa vía pasarelas (EfiBank, Abacate y futuras integraciones) con transferencia automática al organizador. Desactivar significa pago vía Pix directo al organizador, pero funciones adicionales como ranking y votación del mejor de la partida quedan indisponibles.",
        ["Group.NoGateway"] = "Ninguna pasarela está disponible en este momento. Habilite/configure en Admin > Pasarelas.",
        ["Group.AvailableNow"] = "Disponibles ahora: {0}",
        ["Group.Activate"] = "Activar",
        ["Group.Deactivate"] = "Desactivar",
        ["Group.AdditionalFeatures"] = "Funciones adicionales",
        ["Group.AdditionalFeaturesSub"] = "Activa o desactiva funciones opcionales para este grupo.",
        ["Group.RankingPostMatch"] = "Ranking post-partida",
        ["Group.RankingPostMatchDesc"] = "Muestra un ranking de participaciones y desempeño de los miembros, con vistas mensual y anual, en la página del grupo.",
        ["Group.RequiresGateways"] = "Requiere intermediario del sitio (pasarelas) activado.",
        ["Group.BestPlayerVoting"] = "Votación del mejor de la partida",
        ["Group.BestPlayerVotingDesc"] = "Permite que los miembros voten por el mejor jugador de la partida tras el cierre del evento.",

        // MembersManager component
        ["Group.MembersPermissions"] = "Miembros & Permisos",
        ["Group.MembersPermissionsSub"] = "Promueve miembros a admin o quita permisos de admin.",
        ["Group.OnlyCreatorCanManage"] = "Solo el creador del grupo puede añadir o quitar administradores.",
        ["Group.RemoveAdmin"] = "Quitar admin",
        ["Group.MakeAdmin"] = "Hacer admin",
        ["Group.MakeAdminConfirm"] = "¿hacer admin?",
        ["Group.PromoteToAdmin"] = "Promover a admin",
        ["Group.MustHaveOneAdmin"] = "El grupo debe tener al menos un admin",
        ["Group.RemoveAdminTitle"] = "Quitar permiso de admin",

        // PayoutAccountEditor component
        ["Group.PayoutTitle"] = "Clave Pix de Transferencia (Tasa de Servicio)",
        ["Group.PayoutSub"] = "Configura la clave Pix del organizador para recibir el valor de las partidas (tras deducción de la tasa de servicio). Esta clave se usará para envío automático vía API cuando se confirmen los pagos.",
        ["Group.PayoutRegistered"] = "Clave registrada:",
        ["Group.PayoutBeneficiary"] = "Beneficiario: {0}",
        ["Group.PixKeyType"] = "Tipo de clave:",
        ["Group.PixKey"] = "Clave Pix:",
        ["Group.PixKeyPlaceholder"] = "Introduce la clave Pix",
        ["Group.BeneficiaryName"] = "Nombre del beneficiario:",
        ["Group.BeneficiaryNamePlaceholder"] = "Nombre completo o razón social",
        ["Group.BeneficiaryCpf"] = "CPF del beneficiario:",
        ["Group.BankAccountNumber"] = "Número de cuenta bancaria:",
        ["Group.BankAccountPlaceholder"] = "Número de cuenta (sin dígito)",
        ["Group.TestData"] = "Datos de prueba",
        ["Group.PayoutSaving"] = "Guardando…",
        ["Group.PixKeyRandom"] = "Clave Aleatoria",
        ["Group.PixKeyTypeUnknown"] = "Desconocido",
        ["Group.PayoutTestBeneficiaryName"] = "Organizador de Prueba",
        ["Group.PixKeyRequired"] = "La clave Pix es obligatoria.",
        ["Group.BeneficiaryNameRequired"] = "El nombre del beneficiario es obligatorio.",
        ["Group.BeneficiaryCpfRequired"] = "El CPF del beneficiario es obligatorio.",
        ["Group.BankAccountRequired"] = "El número de cuenta es obligatorio.",

        // Payments page
        ["Group.PaymentsTitle"] = "Pagos",
        ["Group.MyPaymentsTitle"] = "Mis pagos",
        ["Group.MyPaymentsEmpty"] = "No tienes pagos en este grupo.",
        ["Group.MyPaymentPaid"] = "Pagado",
        ["Group.MyPaymentPending"] = "Pendiente",
        ["Group.MyPaymentProofSent"] = "Comprobante en revisión",
        ["Group.MyPaymentPay"] = "Pagar",
        ["Group.MyPaymentsToPay"] = "Por pagar",
        ["Group.MyPaymentsInReview"] = "En revisión",
        ["Group.MyPaymentsPaid"] = "Pagados",
        ["Group.MyPaymentsTotalDue"] = "Total a pagar",
        ["Group.PaymentsPending"] = "Pendientes",
        ["Group.PaymentsHistory"] = "Historial",
        ["Group.PaymentsProofs"] = "Comprobantes",
        ["Group.PaymentsProofsEmpty"] = "Ningún comprobante esperando revisión.",
        ["Group.PaymentsProofPlayer"] = "Jugador",
        ["Group.PaymentsProofMatch"] = "Partida",
        ["Group.PaymentsProofDate"] = "Fecha",
        ["Group.PaymentsProofAmount"] = "Importe",
        ["Group.PaymentsProofUploadedAt"] = "Enviado el",
        ["Group.PaymentsProofAccept"] = "Aceptar",
        ["Group.PaymentsProofReject"] = "Rechazar",
        ["Group.PaymentsProofAcceptConfirm"] = "¿Confirmar este pago?",
        ["Group.PaymentsMarkPaidConfirm"] = "¿Seguro que deseas confirmar este pago?",
        ["Group.PaymentsProofRejectConfirm"] = "¿Rechazar este comprobante? El jugador tendrá que enviarlo de nuevo.",
        ["Group.PaymentsProofAccepting"] = "Aceptando...",
        ["Group.PaymentsProofRejecting"] = "Rechazando...",
        ["Group.PaymentsRefresh"] = "Recargar lista",
        ["Group.PaymentsLoading"] = "Cargando…",
        ["Group.AllParticipants"] = "Todos los participantes",
        ["Group.NoManualPayments"] = "Ningún pago manual registrado aún.",
        ["Group.NoDelinquent"] = "Ningún jugador moroso. ¡Todo al día!",
        ["Group.PaymentSingular"] = "pago",
        ["Group.PaymentPlural"] = "pagos",
        ["Group.GameSingular"] = "juego",
        ["Group.GamePlural"] = "juegos",
        ["Group.Notified"] = "Notificado",
        ["Group.NotifyEmail"] = "Enviar email de cobro",
        ["Group.NotifyWhatsApp"] = "Cobrar vía WhatsApp",
        ["Group.PendingMatches"] = "Partidas pendientes",
        ["Group.ViewProof"] = "Ver comprobante",
        ["Group.ViewMatch"] = "Ver partida",
        ["Group.ProofAlt"] = "Comprobante Pix",

        // Platform fee settlement tab
        ["Group.PlatformFeeTab"] = "Tasa de la plataforma",
        ["Group.PlatformFeeTabTitle"] = "Transferencia de la tasa de la plataforma",
        ["Group.PlatformFeeMatches"] = "Partidas con tasa",
        ["Group.PlatformFeeMatchesHint"] = "Selecciona las partidas para hacer la transferencia de la tasa",
        ["Group.PlatformFeeMatchDate"] = "Fecha",
        ["Group.PlatformFeeMatchName"] = "Partida",
        ["Group.PlatformFeeMatchPlayers"] = "Pagadores",
        ["Group.PlatformFeeMatchFee"] = "Tasa",
        ["Group.PlatformFeeMatchStatus"] = "Estado",
        ["Group.PlatformFeeMatchTotal"] = "Total",
        ["Group.PlatformFeeStatusPending"] = "Pendiente",
        ["Group.PlatformFeeStatusPaid"] = "Pagado",
        ["Group.PlatformFeeSummary"] = "Resumen de la transferencia",
        ["Group.PlatformFeeToSettle"] = "A transferir",
        ["Group.PlatformFeeAccrued"] = "Acumulado",
        ["Group.PlatformFeeInAnalysis"] = "En análisis",
        ["Group.PlatformFeeSettled"] = "Ya transferido",
        ["Group.PlatformFeePlatformPix"] = "Clave Pix de la plataforma",
        ["Group.PlatformFeePlatformPixHint"] = "Transfiere el valor a transferir a la clave Pix de la plataforma abajo y adjunta el comprobante.",
        ["Group.PlatformFeeNoPixConfigured"] = "La clave Pix de la plataforma no está configurada. Contacta al administrador del sistema.",
        ["Group.PlatformFeeSubmit"] = "Enviar comprobante de la transferencia",
        ["Group.PlatformFeeSubmitAmount"] = "Importe de la transferencia (R$)",
        ["Group.PlatformFeeFillDue"] = "Total a transferir",
        ["Group.PlatformFeeSelectMatches"] = "Selecciona al menos una partida para transferir.",
        ["Group.PlatformFeeSelectAll"] = "Seleccionar todas",
        ["Group.PlatformFeeClearSelection"] = "Limpiar selección",
        ["Group.PlatformFeeSelectedAmount"] = "Total seleccionado",
        ["Group.PlatformFeeSend"] = "Enviar comprobante",
        ["Group.PlatformFeeConfirmTitle"] = "Confirmar envío de la transferencia",
        ["Group.PlatformFeeConfirmMessage"] = "¿Confirmas el envío del comprobante de {0} para liquidar {1} partida(s)?",
        ["Group.PlatformFeeConfirmSend"] = "Confirmar envío",
        ["Group.PlatformFeeSubmitProof"] = "Comprobante (JPG, PNG o WebP hasta 5 MB)",
        ["Group.PlatformFeeSubmitting"] = "Enviando…",
        ["Group.PlatformFeeSubmitSuccess"] = "Transferencia enviada con éxito. Esperando revisión del administrador.",
        ["Group.PlatformFeeSubmitError"] = "Error al enviar la transferencia. Inténtalo de nuevo.",
        ["Group.PlatformFeeHistory"] = "Historial de transferencias",
        ["Group.PlatformFeeHistoryDate"] = "Enviado el",
        ["Group.PlatformFeeHistoryAmount"] = "Importe",
        ["Group.PlatformFeeHistoryStatus"] = "Estado",
        ["Group.PlatformFeeHistoryNote"] = "Motivo",
        ["Group.PlatformFeeHistoryReviewedAt"] = "Revisado el",
        ["Group.PlatformFeeHistoryProof"] = "Ver comprobante",
        ["Group.PlatformFeeHistoryEmpty"] = "Ninguna transferencia enviada aún.",
        ["Group.PlatformFeeMatchesEmpty"] = "Ninguna partida con tasa acumulada aún.",
        ["Group.PlatformFeeProofAlt"] = "Comprobante de la transferencia",

        // Ranking page
        ["Group.RankingTitle"] = "Ranking",
        ["Group.RankingFootnote"] = "Cuenta solo partidas cuya fecha ya ha finalizado.",

        // Partidas page
        ["Group.RecurringNotice"] = "Partidas generadas automáticamente (semanal)",

        // Group detail components (C28 migration)
        ["Group.NoMatchScheduledEmpty"] = "Ninguna partida programada.",
        ["Group.NoMatchPlayed"] = "Ninguna partida jugada.",
        ["Group.NoMembers"] = "Sin miembros.",
        ["Group.PaymentsRefreshShort"] = "Recargar",
        ["Group.PlayerSentProof"] = "Jugador envió comprobante",
        ["Group.PendingRequestUserFallback"] = "Usuario",
        ["Group.ApproveRequest"] = "Aprobar solicitud",
        ["Group.RejectRequest"] = "Rechazar solicitud",
        ["Group.ApproveAll"] = "Aprobar todos",
        ["Group.Reject"] = "Rechazar",
        ["Group.ActionsLabel"] = "Acciones del grupo",
        ["Group.PaymentsUpToDate"] = "Al día",
        ["Group.RankingSub"] = "Ver ranking",
        ["Group.SettingsSub"] = "Funciones y miembros",
        ["Group.InviteSub"] = "Enviar invitación",
        ["Group.LoginToJoin"] = "Inicia sesión para unirte",
        ["Group.ShowLess"] = "Mostrar menos",
        ["Group.ViewAllMembers"] = "Ver todos ({0})",
        ["Group.MemberActions"] = "Acciones del miembro",
        ["Group.SortNameAZ"] = "Nombre A-Z",
        ["Group.Selected"] = "seleccionado",
        ["Group.Upcoming"] = "próximos",
        ["Group.AttendanceRate"] = "Tasa de Asistencia",
        ["Group.PendingRequestsLabel"] = "Solicitudes Pendientes",
        ["Group.ActionNeeded"] = "Acción necesaria",
        ["Group.NoFinishedMatches"] = "Ninguna partida finalizada en el período.",
        ["Group.Wins"] = "Victorias",
        ["Group.RankingGames"] = "Partidas",
        ["Group.RankingHighlights"] = "Destaques",
        ["Group.WeeklyRecurrences"] = "Recurrencias semanales",
    };

    /// <summary>Get combined dictionary for all languages</summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
