namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Payment text domain: checkout flow, order history, payment status,
/// product details, and payment-related messaging.
/// Covers PaymentBuy, PaymentHistory, PaymentView, PaymentDetails, OrderStatus, etc.
/// </summary>
internal static class PaymentTexts
{
    /// <summary>PT-BR Portuguese (Brazil) strings</summary>
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Finalizar compra",
        ["PaymentBuy.Product"] = "Produto",
        ["PaymentBuy.Price"] = "Preco",
        ["PaymentBuy.Description"] = "Descricao",
        ["PaymentBuy.Seller"] = "Vendedor",
        ["PaymentBuy.Quantity"] = "Quantidade",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Metodo de pagamento",
        ["PaymentBuy.SelectMethod"] = "Selecione um metodo",
        ["PaymentBuy.Confirm"] = "Confirmar pagamento",
        ["PaymentBuy.Cancel"] = "Cancelar",
        ["PaymentBuy.Success"] = "Pagamento realizado com sucesso",
        ["PaymentBuy.Error"] = "Erro ao processar pagamento",
        ["PaymentBuy.InvalidProduct"] = "Produto invalido",
        ["PaymentBuy.InvalidQuantity"] = "Quantidade invalida",
        ["PaymentBuy.InsufficientFunds"] = "Saldo insuficiente",
        ["PaymentBuy.Processing"] = "Processando pagamento...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "Historico de faturas",
        ["PaymentHistory.Subtitle"] = "Acompanhe suas transacoes e pagamentos",
        ["PaymentHistory.Empty"] = "Nenhuma transacao encontrada",
        ["PaymentHistory.EmptyHint"] = "Quando voce fizer pagamentos, eles aparecerao aqui.",
        ["PaymentHistory.TabSent"] = "Enviados",
        ["PaymentHistory.TabReceived"] = "Recebidos",
        ["PaymentHistory.Date"] = "Data",
        ["PaymentHistory.Product"] = "Produto",
        ["PaymentHistory.Amount"] = "Valor",
        ["PaymentHistory.Status"] = "Status",
        ["PaymentHistory.Action"] = "Acao",
        ["PaymentHistory.View"] = "Visualizar",
        ["PaymentHistory.Filter.Status"] = "Status",
        ["PaymentHistory.Filter.Product"] = "Produto...",
        ["PaymentHistory.Filter.MinValue"] = "Valor minimo",
        ["PaymentHistory.Filter.MaxValue"] = "Valor maximo",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.MinAmount"] = "Valor minimo",
        ["PaymentHistory.Filter.MaxAmount"] = "Valor maximo",
        ["PaymentHistory.Filter.AllStatus"] = "Todos os status",
        ["PaymentHistory.AllStatuses"] = "Todos os status",

        // PaymentView
        ["PaymentView.Title"] = "Detalhes da transacao",
        ["PaymentView.Kicker"] = "Historico de faturas",
        ["PaymentView.TransactionId"] = "ID da transacao",
        ["PaymentView.Date"] = "Data",
        ["PaymentView.Product"] = "Produto",
        ["PaymentView.Seller"] = "Vendedor",
        ["PaymentView.Buyer"] = "Comprador",
        ["PaymentView.Amount"] = "Valor",
        ["PaymentView.Method"] = "Metodo de pagamento",
        ["PaymentView.Status"] = "Status",
        ["PaymentView.Back"] = "Voltar ao historico",
        ["PaymentView.Download"] = "Baixar recibo",
        ["PaymentView.NotFound"] = "Transacao nao encontrada",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Detalhes do pagamento",
        ["PaymentDetails.Summary"] = "Resumo",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Imposto",
        ["PaymentDetails.Fee"] = "Taxa de processamento",
        ["PaymentDetails.Discount"] = "Desconto",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Metodo de pagamento",
        ["PaymentDetails.TransactionId"] = "ID da transacao",
        ["PaymentDetails.Date"] = "Data",
        ["PaymentDetails.TimeToRefund"] = "Tempo para reembolso",
        ["PaymentDetails.RefundPolicy"] = "Politica de reembolso",
        ["PaymentDetails.Confirm"] = "Confirmar e enviar",
        ["PaymentDetails.Cancel"] = "Cancelar",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pendente",
        ["OrderStatus.Confirmed"] = "Confirmado",
        ["OrderStatus.Processing"] = "Processando",
        ["OrderStatus.Shipped"] = "Enviado",
        ["OrderStatus.Delivered"] = "Entregue",
        ["OrderStatus.Cancelled"] = "Cancelado",
        ["OrderStatus.Refunded"] = "Reembolsado",
        ["OrderStatus.Failed"] = "Falha no pagamento",
        ["OrderStatus.Disputed"] = "Disputado",
        ["OrderStatus.OnHold"] = "Em espera",
        ["OrderStatus.PartiallyShipped"] = "Parcialmente enviado",
        ["OrderStatus.WaitingForPayment"] = "Aguardando pagamento",
        ["OrderStatus.ReviewRequired"] = "Revisao necessaria",

        // Products (marketplace product strings)
        ["Products.Title"] = "Produtos",
        ["Products.Search"] = "Buscar produtos...",
        ["Products.Filter.Category"] = "Categoria",
        ["Products.Filter.Price"] = "Preco",
        ["Products.Filter.Seller"] = "Vendedor",
        ["Products.Filter.Delivery"] = "Tipo de entrega",
        ["Products.AllCategories"] = "Todas as categorias",
        ["Products.Physical"] = "Entrega fisica",
        ["Products.Digital"] = "Entrega digital",
        ["Products.AllDeliveryTypes"] = "Todos os tipos",
        ["Products.Empty"] = "Nenhum produto encontrado",
        ["Products.SortBy"] = "Ordenar por",
        ["Products.SortNewest"] = "Mais recentes",
        ["Products.SortPrice"] = "Preco",
        ["Products.SortPopular"] = "Mais populares",
        ["Products.Add"] = "Anunciar produto",

        // ProductForm
        ["ProductForm.Title"] = "Anunciar novo produto",
        ["ProductForm.EditTitle"] = "Editar produto",
        ["ProductForm.Name"] = "Nome do produto",
        ["ProductForm.Category"] = "Categoria",
        ["ProductForm.Description"] = "Descricao",
        ["ProductForm.Price"] = "Preco (BTC)",
        ["ProductForm.Delivery"] = "Tipo de entrega",
        ["ProductForm.DeliveryPhysical"] = "Entrega fisica",
        ["ProductForm.DeliveryDigital"] = "Entrega digital",
        ["ProductForm.DeliveryAgent"] = "Entregador",
        ["ProductForm.Images"] = "Imagens",
        ["ProductForm.Create"] = "Anunciar",
        ["ProductForm.Save"] = "Salvar",
        ["ProductForm.Cancel"] = "Cancelar",
        ["ProductForm.Error.NameRequired"] = "Nome obrigatorio",
        ["ProductForm.Error.PriceRequired"] = "Preco obrigatorio",
        ["ProductForm.Error.CategoryRequired"] = "Categoria obrigatoria",
        ["ProductForm.Error.PriceInvalid"] = "Preco invalido",
        ["ProductForm.Success"] = "Produto anunciado com sucesso",
        ["ProductForm.UpdateSuccess"] = "Produto atualizado com sucesso",

        // Marketplace
        ["Marketplace.Title"] = "Marketplace",
        ["Marketplace.Subtitle"] = "Compre e venda com seguranca",
        ["Marketplace.Featured"] = "Destaque",
        ["Marketplace.Recent"] = "Recentes",
        ["Marketplace.MyListings"] = "Meus anuncios",
        ["Marketplace.MyPurchases"] = "Minhas compras",
        ["Marketplace.MySales"] = "Minhas vendas",
    };

    /// <summary>EN-US English (United States) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Checkout",
        ["PaymentBuy.Product"] = "Product",
        ["PaymentBuy.Price"] = "Price",
        ["PaymentBuy.Description"] = "Description",
        ["PaymentBuy.Seller"] = "Seller",
        ["PaymentBuy.Quantity"] = "Quantity",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Payment method",
        ["PaymentBuy.SelectMethod"] = "Select a method",
        ["PaymentBuy.Confirm"] = "Confirm payment",
        ["PaymentBuy.Cancel"] = "Cancel",
        ["PaymentBuy.Success"] = "Payment successful",
        ["PaymentBuy.Error"] = "Payment processing error",
        ["PaymentBuy.InvalidProduct"] = "Invalid product",
        ["PaymentBuy.InvalidQuantity"] = "Invalid quantity",
        ["PaymentBuy.InsufficientFunds"] = "Insufficient funds",
        ["PaymentBuy.Processing"] = "Processing payment...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "Invoice History",
        ["PaymentHistory.Subtitle"] = "Track your transactions and payments",
        ["PaymentHistory.Empty"] = "No transactions found",
        ["PaymentHistory.Date"] = "Date",
        ["PaymentHistory.Product"] = "Product",
        ["PaymentHistory.Amount"] = "Amount",
        ["PaymentHistory.Status"] = "Status",
        ["PaymentHistory.Action"] = "Action",
        ["PaymentHistory.View"] = "View",
        ["PaymentHistory.Filter.Status"] = "Status",
        ["PaymentHistory.Filter.Product"] = "Product...",
        ["PaymentHistory.Filter.MinValue"] = "Minimum value",
        ["PaymentHistory.Filter.MaxValue"] = "Maximum value",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.MinAmount"] = "Minimum amount",
        ["PaymentHistory.Filter.MaxAmount"] = "Maximum amount",
        ["PaymentHistory.Filter.AllStatus"] = "All statuses",
        ["PaymentHistory.AllStatuses"] = "All statuses",

        // PaymentView
        ["PaymentView.Title"] = "Transaction details",
        ["PaymentView.Kicker"] = "Invoice history",
        ["PaymentView.TransactionId"] = "Transaction ID",
        ["PaymentView.Date"] = "Date",
        ["PaymentView.Product"] = "Product",
        ["PaymentView.Seller"] = "Seller",
        ["PaymentView.Buyer"] = "Buyer",
        ["PaymentView.Amount"] = "Amount",
        ["PaymentView.Method"] = "Payment method",
        ["PaymentView.Status"] = "Status",
        ["PaymentView.Back"] = "Back to history",
        ["PaymentView.Download"] = "Download receipt",
        ["PaymentView.NotFound"] = "Transaction not found",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Payment details",
        ["PaymentDetails.Summary"] = "Summary",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Tax",
        ["PaymentDetails.Fee"] = "Processing fee",
        ["PaymentDetails.Discount"] = "Discount",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Payment method",
        ["PaymentDetails.TransactionId"] = "Transaction ID",
        ["PaymentDetails.Date"] = "Date",
        ["PaymentDetails.TimeToRefund"] = "Time to refund",
        ["PaymentDetails.RefundPolicy"] = "Refund policy",
        ["PaymentDetails.Confirm"] = "Confirm and send",
        ["PaymentDetails.Cancel"] = "Cancel",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pending",
        ["OrderStatus.Confirmed"] = "Confirmed",
        ["OrderStatus.Processing"] = "Processing",
        ["OrderStatus.Shipped"] = "Shipped",
        ["OrderStatus.Delivered"] = "Delivered",
        ["OrderStatus.Cancelled"] = "Cancelled",
        ["OrderStatus.Refunded"] = "Refunded",
        ["OrderStatus.Failed"] = "Payment failed",
        ["OrderStatus.Disputed"] = "Disputed",
        ["OrderStatus.OnHold"] = "On hold",
        ["OrderStatus.PartiallyShipped"] = "Partially shipped",
        ["OrderStatus.WaitingForPayment"] = "Waiting for payment",
        ["OrderStatus.ReviewRequired"] = "Review required",

        // Products (marketplace product strings)
        ["Products.Title"] = "Products",
        ["Products.Search"] = "Search products...",
        ["Products.Filter.Category"] = "Category",
        ["Products.Filter.Price"] = "Price",
        ["Products.Filter.Seller"] = "Seller",
        ["Products.Filter.Delivery"] = "Delivery type",
        ["Products.AllCategories"] = "All categories",
        ["Products.Physical"] = "Physical delivery",
        ["Products.Digital"] = "Digital delivery",
        ["Products.AllDeliveryTypes"] = "All types",
        ["Products.Empty"] = "No products found",
        ["Products.SortBy"] = "Sort by",
        ["Products.SortNewest"] = "Newest",
        ["Products.SortPrice"] = "Price",
        ["Products.SortPopular"] = "Most popular",
        ["Products.Add"] = "List product",

        // ProductForm
        ["ProductForm.Title"] = "List new product",
        ["ProductForm.EditTitle"] = "Edit product",
        ["ProductForm.Name"] = "Product name",
        ["ProductForm.Category"] = "Category",
        ["ProductForm.Description"] = "Description",
        ["ProductForm.Price"] = "Price (BTC)",
        ["ProductForm.Delivery"] = "Delivery type",
        ["ProductForm.DeliveryPhysical"] = "Physical delivery",
        ["ProductForm.DeliveryDigital"] = "Digital delivery",
        ["ProductForm.DeliveryAgent"] = "Delivery agent",
        ["ProductForm.Images"] = "Images",
        ["ProductForm.Create"] = "List",
        ["ProductForm.Save"] = "Save",
        ["ProductForm.Cancel"] = "Cancel",
        ["ProductForm.Error.NameRequired"] = "Name required",
        ["ProductForm.Error.PriceRequired"] = "Price required",
        ["ProductForm.Error.CategoryRequired"] = "Category required",
        ["ProductForm.Error.PriceInvalid"] = "Invalid price",
        ["ProductForm.Success"] = "Product listed successfully",
        ["ProductForm.UpdateSuccess"] = "Product updated successfully",

        // Marketplace
        ["Marketplace.Title"] = "Marketplace",
        ["Marketplace.Subtitle"] = "Buy and sell securely",
        ["Marketplace.Featured"] = "Featured",
        ["Marketplace.Recent"] = "Recent",
        ["Marketplace.MyListings"] = "My listings",
        ["Marketplace.MyPurchases"] = "My purchases",
        ["Marketplace.MySales"] = "My sales",
    };

    /// <summary>ES-ES Spanish (Spain) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Finalizar compra",
        ["PaymentBuy.Product"] = "Producto",
        ["PaymentBuy.Price"] = "Precio",
        ["PaymentBuy.Description"] = "Descripcion",
        ["PaymentBuy.Seller"] = "Vendedor",
        ["PaymentBuy.Quantity"] = "Cantidad",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Metodo de pago",
        ["PaymentBuy.SelectMethod"] = "Seleccione un metodo",
        ["PaymentBuy.Confirm"] = "Confirmar pago",
        ["PaymentBuy.Cancel"] = "Cancelar",
        ["PaymentBuy.Success"] = "Pago exitoso",
        ["PaymentBuy.Error"] = "Error al procesar pago",
        ["PaymentBuy.InvalidProduct"] = "Producto invalido",
        ["PaymentBuy.InvalidQuantity"] = "Cantidad invalida",
        ["PaymentBuy.InsufficientFunds"] = "Saldo insuficiente",
        ["PaymentBuy.Processing"] = "Procesando pago...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "Historial de facturas",
        ["PaymentHistory.Subtitle"] = "Rastrea tus transacciones y pagos",
        ["PaymentHistory.Empty"] = "No se encontraron transacciones",
        ["PaymentHistory.Date"] = "Fecha",
        ["PaymentHistory.Product"] = "Producto",
        ["PaymentHistory.Amount"] = "Monto",
        ["PaymentHistory.Status"] = "Estado",
        ["PaymentHistory.Action"] = "Accion",
        ["PaymentHistory.View"] = "Ver",
        ["PaymentHistory.Filter.Status"] = "Estado",
        ["PaymentHistory.Filter.Product"] = "Producto...",
        ["PaymentHistory.Filter.MinValue"] = "Monto minimo",
        ["PaymentHistory.Filter.MaxValue"] = "Monto maximo",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.MinAmount"] = "Monto minimo",
        ["PaymentHistory.Filter.MaxAmount"] = "Monto maximo",
        ["PaymentHistory.Filter.AllStatus"] = "Todos los estados",
        ["PaymentHistory.AllStatuses"] = "Todos los estados",

        // PaymentView
        ["PaymentView.Title"] = "Detalles de transaccion",
        ["PaymentView.Kicker"] = "Historial de facturas",
        ["PaymentView.TransactionId"] = "ID de transaccion",
        ["PaymentView.Date"] = "Fecha",
        ["PaymentView.Product"] = "Producto",
        ["PaymentView.Seller"] = "Vendedor",
        ["PaymentView.Buyer"] = "Comprador",
        ["PaymentView.Amount"] = "Monto",
        ["PaymentView.Method"] = "Metodo de pago",
        ["PaymentView.Status"] = "Estado",
        ["PaymentView.Back"] = "Volver al historial",
        ["PaymentView.Download"] = "Descargar recibo",
        ["PaymentView.NotFound"] = "Transaccion no encontrada",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Detalles del pago",
        ["PaymentDetails.Summary"] = "Resumen",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Impuesto",
        ["PaymentDetails.Fee"] = "Tarifa de procesamiento",
        ["PaymentDetails.Discount"] = "Descuento",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Metodo de pago",
        ["PaymentDetails.TransactionId"] = "ID de transaccion",
        ["PaymentDetails.Date"] = "Fecha",
        ["PaymentDetails.TimeToRefund"] = "Tiempo para reembolso",
        ["PaymentDetails.RefundPolicy"] = "Politica de reembolso",
        ["PaymentDetails.Confirm"] = "Confirmar y enviar",
        ["PaymentDetails.Cancel"] = "Cancelar",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pendiente",
        ["OrderStatus.Confirmed"] = "Confirmado",
        ["OrderStatus.Processing"] = "Procesando",
        ["OrderStatus.Shipped"] = "Enviado",
        ["OrderStatus.Delivered"] = "Entregado",
        ["OrderStatus.Cancelled"] = "Cancelado",
        ["OrderStatus.Refunded"] = "Reembolsado",
        ["OrderStatus.Failed"] = "Fallo de pago",
        ["OrderStatus.Disputed"] = "Disputado",
        ["OrderStatus.OnHold"] = "En espera",
        ["OrderStatus.PartiallyShipped"] = "Parcialmente enviado",
        ["OrderStatus.WaitingForPayment"] = "Esperando pago",
        ["OrderStatus.ReviewRequired"] = "Revision requerida",

        // Products (marketplace product strings)
        ["Products.Title"] = "Productos",
        ["Products.Search"] = "Buscar productos...",
        ["Products.Filter.Category"] = "Categoria",
        ["Products.Filter.Price"] = "Precio",
        ["Products.Filter.Seller"] = "Vendedor",
        ["Products.Filter.Delivery"] = "Tipo de entrega",
        ["Products.AllCategories"] = "Todas las categorias",
        ["Products.Physical"] = "Entrega fisica",
        ["Products.Digital"] = "Entrega digital",
        ["Products.AllDeliveryTypes"] = "Todos los tipos",
        ["Products.Empty"] = "No se encontraron productos",
        ["Products.SortBy"] = "Ordenar por",
        ["Products.SortNewest"] = "Mas recientes",
        ["Products.SortPrice"] = "Precio",
        ["Products.SortPopular"] = "Mas populares",
        ["Products.Add"] = "Anunciar producto",

        // ProductForm
        ["ProductForm.Title"] = "Anunciar nuevo producto",
        ["ProductForm.EditTitle"] = "Editar producto",
        ["ProductForm.Name"] = "Nombre del producto",
        ["ProductForm.Category"] = "Categoria",
        ["ProductForm.Description"] = "Descripcion",
        ["ProductForm.Price"] = "Precio (BTC)",
        ["ProductForm.Delivery"] = "Tipo de entrega",
        ["ProductForm.DeliveryPhysical"] = "Entrega fisica",
        ["ProductForm.DeliveryDigital"] = "Entrega digital",
        ["ProductForm.DeliveryAgent"] = "Agente de entrega",
        ["ProductForm.Images"] = "Imagenes",
        ["ProductForm.Create"] = "Anunciar",
        ["ProductForm.Save"] = "Guardar",
        ["ProductForm.Cancel"] = "Cancelar",
        ["ProductForm.Error.NameRequired"] = "Nombre obligatorio",
        ["ProductForm.Error.PriceRequired"] = "Precio obligatorio",
        ["ProductForm.Error.CategoryRequired"] = "Categoria obligatoria",
        ["ProductForm.Error.PriceInvalid"] = "Precio invalido",
        ["ProductForm.Success"] = "Producto anunciado exitosamente",
        ["ProductForm.UpdateSuccess"] = "Producto actualizado exitosamente",

        // Marketplace
        ["Marketplace.Title"] = "Mercado",
        ["Marketplace.Subtitle"] = "Compra y vende con seguridad",
        ["Marketplace.Featured"] = "Destacado",
        ["Marketplace.Recent"] = "Recientes",
        ["Marketplace.MyListings"] = "Mis anuncios",
        ["Marketplace.MyPurchases"] = "Mis compras",
        ["Marketplace.MySales"] = "Mis ventas",
    };

    /// <summary>Get combined dictionary for all languages</summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
