namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Payment text domain: checkout flow, order history, payment status,
/// product details, and payment-related messaging.
/// Covers PaymentBuy, PaymentHistory, PaymentView, PaymentDetails, OrderStatus, etc.
/// </summary>
internal static class PaymentTexts
{
    /// <summary>PT-BR Portuguese (Brazil) strings</summary>
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Finalizar compra",
        ["PaymentBuy.Product"] = "Produto",
        ["PaymentBuy.Price"] = "Preco",
        ["PaymentBuy.Description"] = "Descricao",
        ["PaymentBuy.Seller"] = "Vendedor",
        ["PaymentBuy.Quantity"] = "Quantidade",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Metodo de pagamento",
        ["PaymentBuy.SelectMethod"] = "Selecione um metodo",
        ["PaymentBuy.Confirm"] = "Confirmar pagamento",
        ["PaymentBuy.Cancel"] = "Cancelar",
        ["PaymentBuy.Success"] = "Pagamento realizado com sucesso",
        ["PaymentBuy.Error"] = "Erro ao processar pagamento",
        ["PaymentBuy.InvalidProduct"] = "Produto invalido",
        ["PaymentBuy.InvalidQuantity"] = "Quantidade invalida",
        ["PaymentBuy.InsufficientFunds"] = "Saldo insuficiente",
        ["PaymentBuy.Processing"] = "Processando pagamento...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "Meus pagamentos",
        ["PaymentHistory.Subtitle"] = "Acompanhe suas transações e pagamentos",
        ["PaymentHistory.Aria"] = "Histórico de pagamentos",
        ["PaymentHistory.Empty"] = "Nenhuma transação encontrada",
        ["PaymentHistory.EmptyHint"] = "Quando você fizer pagamentos, eles aparecerão aqui.",
        ["PaymentHistory.TabSent"] = "Enviados",
        ["PaymentHistory.TabReceived"] = "Recebidos",
        ["PaymentHistory.Date"] = "Data",
        ["PaymentHistory.Product"] = "Produto",
        ["PaymentHistory.Buyer"] = "Comprador",
        ["PaymentHistory.Amount"] = "Valor",
        ["PaymentHistory.Status"] = "Status",
        ["PaymentHistory.Action"] = "Ação",
        ["PaymentHistory.View"] = "Visualizar",
        ["PaymentHistory.Filter.Status"] = "Status",
        ["PaymentHistory.Filter.Product"] = "Produto...",
        ["PaymentHistory.Filter.MinValue"] = "Valor mínimo",
        ["PaymentHistory.Filter.MaxValue"] = "Valor máximo",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.MinAmount"] = "Valor mínimo",
        ["PaymentHistory.Filter.MaxAmount"] = "Valor máximo",
        ["PaymentHistory.Filter.AllStatus"] = "Todos os status",
        ["PaymentHistory.AllStatuses"] = "Todos os status",
        ["PaymentHistory.ConfirmedToast"] = "Pagamento {0} confirmado com sucesso!",
        ["PaymentHistory.CanceledToast"] = "Pagamento cancelado.",
        ["PaymentHistory.ConfirmCancel"] = "Deseja realmente cancelar este pagamento?",
        ["PaymentHistory.UnknownProduct"] = "Produto desconhecido",

        // PaymentView
        ["PaymentView.Title"] = "Detalhes da transação",
        ["PaymentView.Kicker"] = "Histórico de faturas",
        ["PaymentView.TransactionId"] = "ID da transação",
        ["PaymentView.Date"] = "Data",
        ["PaymentView.Product"] = "Produto",
        ["PaymentView.Seller"] = "Vendedor",
        ["PaymentView.Buyer"] = "Comprador",
        ["PaymentView.Amount"] = "Valor",
        ["PaymentView.Method"] = "Método de pagamento",
        ["PaymentView.Status"] = "Status",
        ["PaymentView.Back"] = "Voltar ao histórico",
        ["PaymentView.Download"] = "Baixar recibo",
        ["PaymentView.NotFound"] = "Transação não encontrada",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Detalhes do pagamento",
        ["PaymentDetails.Summary"] = "Resumo",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Imposto",
        ["PaymentDetails.Fee"] = "Taxa de processamento",
        ["PaymentDetails.Discount"] = "Desconto",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Método de pagamento",
        ["PaymentDetails.TransactionId"] = "ID da transação",
        ["PaymentDetails.Date"] = "Data",
        ["PaymentDetails.TimeToRefund"] = "Tempo para reembolso",
        ["PaymentDetails.RefundPolicy"] = "Política de reembolso",
        ["PaymentDetails.Confirm"] = "Confirmar e enviar",
        ["PaymentDetails.Cancel"] = "Cancelar",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pendente",
        ["OrderStatus.Confirmed"] = "Confirmado",
        ["OrderStatus.Processing"] = "Processando",
        ["OrderStatus.Shipped"] = "Enviado",
        ["OrderStatus.Delivered"] = "Entregue",
        ["OrderStatus.Cancelled"] = "Cancelado",
        ["OrderStatus.Refunded"] = "Reembolsado",
        ["OrderStatus.Failed"] = "Falha no pagamento",
        ["OrderStatus.Disputed"] = "Disputado",
        ["OrderStatus.OnHold"] = "Em espera",
        ["OrderStatus.PartiallyShipped"] = "Parcialmente enviado",
        ["OrderStatus.WaitingForPayment"] = "Aguardando pagamento",
        ["OrderStatus.ReviewRequired"] = "Revisão necessária",

        // Products (marketplace product strings)
        ["Products.Title"] = "Produtos",
        ["Products.Search"] = "Buscar produtos...",
        ["Products.Filter.Category"] = "Categoria",
        ["Products.Filter.Price"] = "Preco",
        ["Products.Filter.Seller"] = "Vendedor",
        ["Products.Filter.Delivery"] = "Tipo de entrega",
        ["Products.AllCategories"] = "Todas as categorias",
        ["Products.Physical"] = "Entrega fisica",
        ["Products.Digital"] = "Entrega digital",
        ["Products.AllDeliveryTypes"] = "Todos os tipos",
        ["Products.Empty"] = "Nenhum produto encontrado",
        ["Products.SortBy"] = "Ordenar por",
        ["Products.SortNewest"] = "Mais recentes",
        ["Products.SortPrice"] = "Preco",
        ["Products.SortPopular"] = "Mais populares",
        ["Products.Add"] = "Anunciar produto",

        // ProductForm
        ["ProductForm.Title"] = "Anunciar novo produto",
        ["ProductForm.EditTitle"] = "Editar produto",
        ["ProductForm.Name"] = "Nome do produto",
        ["ProductForm.Category"] = "Categoria",
        ["ProductForm.Description"] = "Descricao",
        ["ProductForm.Price"] = "Preco (BTC)",
        ["ProductForm.Delivery"] = "Tipo de entrega",
        ["ProductForm.DeliveryPhysical"] = "Entrega fisica",
        ["ProductForm.DeliveryDigital"] = "Entrega digital",
        ["ProductForm.DeliveryAgent"] = "Entregador",
        ["ProductForm.Images"] = "Imagens",
        ["ProductForm.Create"] = "Anunciar",
        ["ProductForm.Save"] = "Salvar",
        ["ProductForm.Cancel"] = "Cancelar",
        ["ProductForm.Error.NameRequired"] = "Nome obrigatorio",
        ["ProductForm.Error.PriceRequired"] = "Preco obrigatorio",
        ["ProductForm.Error.CategoryRequired"] = "Categoria obrigatoria",
        ["ProductForm.Error.PriceInvalid"] = "Preco invalido",
        ["ProductForm.Success"] = "Produto anunciado com sucesso",
        ["ProductForm.UpdateSuccess"] = "Produto atualizado com sucesso",

        // Marketplace
        ["Marketplace.Title"] = "Marketplace",
        ["Marketplace.Subtitle"] = "Compre e venda com seguranca",
        ["Marketplace.Featured"] = "Destaque",
        ["Marketplace.Recent"] = "Recentes",
        ["Marketplace.MyListings"] = "Meus anuncios",
        ["Marketplace.MyPurchases"] = "Minhas compras",
        ["Marketplace.MySales"] = "Minhas vendas",

        // Payment flow (EventPayment page + components)
        ["Payment.PageTitle"] = "Pagamento",
        ["Payment.Loading"] = "Carregando…",
        ["Payment.ConfirmationNotFound"] = "Confirmação não encontrada.",
        ["Payment.Confirmed"] = "Pagamento confirmado",
        ["Payment.ConfirmedFor"] = "Pagamento de {0} foi confirmado.",
        ["Payment.BackToMatch"] = "Voltar para a partida",
        ["Payment.AdminReview"] = "Revisão de pagamento — {0}",
        ["Payment.ProofSentAt"] = "Comprovante enviado em {0}",
        ["Payment.ProofAlt"] = "Comprovante Pix",
        ["Payment.ErrorConfirm"] = "Erro ao confirmar pagamento. Tente novamente.",
        ["Payment.ConfirmPaymentFor"] = "Confirmar pagamento de {0}?",
        ["Payment.ConfirmPayment"] = "Confirmar pagamento",
        ["Payment.YesConfirm"] = "Sim, confirmar",
        ["Payment.NoProofSent"] = "O jogador ainda não enviou comprovante.",
        ["Payment.MarkAsPaidFor"] = "Marcar {0} como pago?",
        ["Payment.MarkAsPaid"] = "Marcar como pago",
        ["Payment.Player"] = "Jogador",
        ["Payment.GenerateQrError"] = "Não foi possível gerar o QR Code. Tente novamente em instantes.",
        ["Payment.ProofSuccess"] = "Comprovante enviado com sucesso! Redirecionando...",
        ["Payment.ProofTooLarge"] = "Arquivo muito grande ou inválido. Máximo 5 MB.",
        ["Payment.ProofError"] = "Erro ao enviar o comprovante. Tente novamente.",
        ["Payment.ManualFlow"] = "Pagamento manual via Pix. Pague diretamente ao organizador e envie o comprovante.",
        ["Payment.PixDirectToOrganizer"] = "Pix direto ao organizador",
        ["Payment.PixHint"] = "Escaneie o QR Code ou copie a chave e transfira R$ {0} diretamente. O organizador confirmará o recebimento.",
        ["Payment.NoPixKey"] = "O organizador ainda não cadastrou uma chave Pix. Entre em contato diretamente para combinar o pagamento.",
        ["Payment.Copied"] = "Copiado!",
        ["Payment.Copy"] = "Copiar",
        ["Payment.ProofTitle"] = "Comprovante de pagamento",
        ["Payment.ProofSentAtShort"] = "Comprovante enviado em {0}",
        ["Payment.UpdateProof"] = "Atualizar comprovante",
        ["Payment.SendProof"] = "Enviar comprovante",
        ["Payment.Sending"] = "Enviando…",
        ["Payment.ProofHint"] = "Após fazer o Pix, envie o comprovante para o organizador confirmar seu pagamento.",
        ["Payment.AwaitingPayment"] = "Aguardando pagamento…",
        ["Payment.PixCopyPaste"] = "Pix Copia e Cola",
        ["Payment.CopyPixCode"] = "Copiar código Pix",
        ["Payment.PaymentConfirmed"] = "Pagamento confirmado",
        ["Payment.ParticipationGuaranteed"] = "Sua participação está garantida. Boa partida!",
        ["Payment.PaymentMethods"] = "Forma de pagamento",
        ["Payment.NoGatewayAvailable"] = "Nenhum gateway de pagamento está disponível no momento.",
        ["Payment.ComingSoon"] = "em breve",
        ["Payment.GeneratingQr"] = "Gerando QR Code…",
        ["Payment.GenerateQrWithGateway"] = "Gerar QR Code ({0}) — R$ {1}",
        ["Payment.MatchValue"] = "Valor da partida:",
        ["Payment.AppFee"] = "Taxa do app:",
        ["Payment.GatewayFee"] = "Taxa do gateway:",
        ["Payment.TotalToPay"] = "Total a pagar:",
        ["Payment.SummaryPlayer"] = "Jogador",
        ["Payment.SummaryPosition"] = "Posição",
        ["Payment.SummaryGoalkeeper"] = "Goleiro",
        ["Payment.SummaryOutfield"] = "Linha",
        ["Payment.SummaryAmount"] = "Valor a pagar",
        ["Payment.SummaryMatchPrice"] = "Partida",
        ["Payment.SummaryPlatformFee"] = "Taxa da plataforma",
        ["PaymentBuy.GeneratePayment"] = "Gerar pagamento",
        ["PaymentBuy.NoMethod"] = "Nenhum método de pagamento disponível",
        ["PaymentBuy.NoMethodHint"] = "Tente novamente em instantes ou contate o suporte.",
        ["PaymentBuy.WithIntermediary"] = "Com intermédio do ADM do site",
        ["PaymentBuy.WithoutIntermediary"] = "Sem intermédio do ADM do site",
        ["PaymentBuy.NoIntermediaryWarning"] = "Sem intermediação, o pagamento vai diretamente ao vendedor. Só prossiga se você <strong>confia totalmente no vendedor</strong>. O site não poderá mediar disputas nesta transação.",
        ["PaymentBuy.PaymentMethod"] = "Forma de pagamento:",
        ["PaymentBuy.SelectGateway"] = "Selecionar gateway",
        ["PaymentBuy.GenerateAddress"] = "Gerar endereço de pagamento",
        ["PaymentBuy.PixCodeLabel"] = "Código Pix",
        ["PaymentBuy.InvoiceAddress"] = "Endereço da fatura",
        ["PaymentBuy.Copy"] = "Copiar",
        ["PaymentBuy.CopyCode"] = "Copiar código",
        ["PaymentBuy.PaidReceived"] = "Pago recebido",
        ["PaymentBuy.Waiting"] = "Aguardando pagamento…",
        ["PaymentBuy.WaitingManualPix"] = "Aguardando confirmação manual do pagamento PIX.",
        ["PaymentBuy.Check"] = "Verificar pagamento",
        ["PaymentBuy.PrivateKey"] = "Chave privada",
        ["PaymentBuy.PrivateKeyWarning"] = "Guarde esta chave em local seguro. Ela não será exibida novamente.",
        ["PaymentBuy.LoadingProduct"] = "Carregando produto…",

        // Payment product summary
        ["PaymentProductSummary.Title"] = "Resumo da oferta",
        ["PaymentProductSummary.ItemAria"] = "Resumo do item",
        ["PaymentProductSummary.ImageAlt"] = "Imagem do produto",
        ["PaymentProductSummary.Item"] = "Item",
        ["PaymentProductSummary.Name"] = "Nome",
        ["PaymentProductSummary.Quantity"] = "Quantidade",
        ["PaymentProductSummary.UnitPrice"] = "Valor unitário",
        ["PaymentProductSummary.TotalPrice"] = "Valor total",
        ["PaymentProductSummary.Seller"] = "Vendedor:",

        // Payment view extra
        ["PaymentView.Rechecking"] = "Reconfirmando...",
        ["PaymentView.CheckingGateways"] = "Consultando gateways para confirmar o pagamento...",
        ["PaymentView.Aria"] = "Visualizar pagamento",
        ["PaymentView.Checkout"] = "Checkout",
        ["PaymentView.OpenCheckout"] = "Abrir checkout no {0}",
        ["PaymentView.QrHint"] = "Escaneie o QR Code no site do {0} para concluir o pagamento.",
        ["PaymentDetails.Aria"] = "Detalhes do pagamento",
        ["PaymentDetails.PaymentId"] = "ID do pagamento",
        ["PaymentDetails.PaidAt"] = "Pago em",

        // Payment history export
        ["PaymentHistory.ExportCsv"] = "Exportar CSV",
        ["PaymentHistory.ExportPdf"] = "Exportar PDF",

        // Platform fee settlement service messages (Fase F do Ciclo 27)
        ["Payment.Settlement.InvalidImageType"] = "Apenas imagens JPG, PNG ou WebP são aceitas.",
        ["Payment.Settlement.FileTooLarge"] = "Arquivo muito grande. Máximo {0} MB.",
        ["Payment.Settlement.SubmitSuccess"] = "Repasse enviado com sucesso. Aguardando revisão.",
        ["Payment.Settlement.NotFound"] = "Repasse não encontrado.",
        ["Payment.Settlement.AlreadyReviewed"] = "Este repasse já foi revisado.",
        ["Payment.Settlement.EmptyFile"] = "Arquivo vazio.",
        ["Payment.Settlement.InvalidAmount"] = "Valor do repasse deve ser maior que zero.",
        ["Payment.Settlement.NotGroupAdmin"] = "Apenas um administrador do grupo pode enviar o repasse.",
        ["Payment.Settlement.NotSystemAdmin"] = "Apenas o administrador do sistema pode confirmar o recebimento do repasse.",
        ["Payment.Settlement.SubmitError"] = "Erro ao enviar repasse. Tente novamente.",
        ["Payment.Settlement.Approved"] = "Repasse aprovado.",
        ["Payment.Settlement.Rejected"] = "Repasse rejeitado.",
        ["Payment.Settlement.NoMatchesSelected"] = "Selecione as partidas que este repasse quita.",
        ["Payment.Settlement.InvalidMatchSelection"] = "Seleção de partidas inválida para este grupo.",
        ["Payment.Settlement.MatchAlreadyCovered"] = "Uma das partidas selecionadas já está em um repasse enviado ou aprovado.",
        ["Payment.Settlement.AmountMismatch"] = "O valor do repasse deve ser R$ {0}, igual à soma das taxas das partidas selecionadas.",
    };

    /// <summary>EN-US English (United States) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Checkout",
        ["PaymentBuy.Product"] = "Product",
        ["PaymentBuy.Price"] = "Price",
        ["PaymentBuy.Description"] = "Description",
        ["PaymentBuy.Seller"] = "Seller",
        ["PaymentBuy.Quantity"] = "Quantity",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Payment method",
        ["PaymentBuy.SelectMethod"] = "Select a method",
        ["PaymentBuy.Confirm"] = "Confirm payment",
        ["PaymentBuy.Cancel"] = "Cancel",
        ["PaymentBuy.Success"] = "Payment successful",
        ["PaymentBuy.Error"] = "Payment processing error",
        ["PaymentBuy.InvalidProduct"] = "Invalid product",
        ["PaymentBuy.InvalidQuantity"] = "Invalid quantity",
        ["PaymentBuy.InsufficientFunds"] = "Insufficient funds",
        ["PaymentBuy.Processing"] = "Processing payment...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "My Payments",
        ["PaymentHistory.Subtitle"] = "Track your transactions and payments",
        ["PaymentHistory.Aria"] = "Payment history",
        ["PaymentHistory.Empty"] = "No transactions found",
        ["PaymentHistory.EmptyHint"] = "When you make payments, they will appear here.",
        ["PaymentHistory.TabSent"] = "Sent",
        ["PaymentHistory.TabReceived"] = "Received",
        ["PaymentHistory.Buyer"] = "Buyer",
        ["PaymentHistory.ConfirmedToast"] = "Payment {0} confirmed successfully!",
        ["PaymentHistory.CanceledToast"] = "Payment canceled.",
        ["PaymentHistory.ConfirmCancel"] = "Do you really want to cancel this payment?",
        ["PaymentHistory.UnknownProduct"] = "Unknown product",
        ["PaymentHistory.Date"] = "Date",
        ["PaymentHistory.Product"] = "Product",
        ["PaymentHistory.Amount"] = "Amount",
        ["PaymentHistory.Status"] = "Status",
        ["PaymentHistory.Action"] = "Action",
        ["PaymentHistory.View"] = "View",
        ["PaymentHistory.Filter.Status"] = "Status",
        ["PaymentHistory.Filter.Product"] = "Product...",
        ["PaymentHistory.Filter.MinValue"] = "Minimum value",
        ["PaymentHistory.Filter.MaxValue"] = "Maximum value",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.MinAmount"] = "Minimum amount",
        ["PaymentHistory.Filter.MaxAmount"] = "Maximum amount",
        ["PaymentHistory.Filter.AllStatus"] = "All statuses",
        ["PaymentHistory.AllStatuses"] = "All statuses",

        // PaymentView
        ["PaymentView.Title"] = "Transaction details",
        ["PaymentView.Kicker"] = "Invoice history",
        ["PaymentView.TransactionId"] = "Transaction ID",
        ["PaymentView.Date"] = "Date",
        ["PaymentView.Product"] = "Product",
        ["PaymentView.Seller"] = "Seller",
        ["PaymentView.Buyer"] = "Buyer",
        ["PaymentView.Amount"] = "Amount",
        ["PaymentView.Method"] = "Payment method",
        ["PaymentView.Status"] = "Status",
        ["PaymentView.Back"] = "Back to history",
        ["PaymentView.Download"] = "Download receipt",
        ["PaymentView.NotFound"] = "Transaction not found",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Payment details",
        ["PaymentDetails.Summary"] = "Summary",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Tax",
        ["PaymentDetails.Fee"] = "Processing fee",
        ["PaymentDetails.Discount"] = "Discount",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Payment method",
        ["PaymentDetails.TransactionId"] = "Transaction ID",
        ["PaymentDetails.Date"] = "Date",
        ["PaymentDetails.TimeToRefund"] = "Time to refund",
        ["PaymentDetails.RefundPolicy"] = "Refund policy",
        ["PaymentDetails.Confirm"] = "Confirm and send",
        ["PaymentDetails.Cancel"] = "Cancel",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pending",
        ["OrderStatus.Confirmed"] = "Confirmed",
        ["OrderStatus.Processing"] = "Processing",
        ["OrderStatus.Shipped"] = "Shipped",
        ["OrderStatus.Delivered"] = "Delivered",
        ["OrderStatus.Cancelled"] = "Cancelled",
        ["OrderStatus.Refunded"] = "Refunded",
        ["OrderStatus.Failed"] = "Payment failed",
        ["OrderStatus.Disputed"] = "Disputed",
        ["OrderStatus.OnHold"] = "On hold",
        ["OrderStatus.PartiallyShipped"] = "Partially shipped",
        ["OrderStatus.WaitingForPayment"] = "Waiting for payment",
        ["OrderStatus.ReviewRequired"] = "Review required",

        // Products (marketplace product strings)
        ["Products.Title"] = "Products",
        ["Products.Search"] = "Search products...",
        ["Products.Filter.Category"] = "Category",
        ["Products.Filter.Price"] = "Price",
        ["Products.Filter.Seller"] = "Seller",
        ["Products.Filter.Delivery"] = "Delivery type",
        ["Products.AllCategories"] = "All categories",
        ["Products.Physical"] = "Physical delivery",
        ["Products.Digital"] = "Digital delivery",
        ["Products.AllDeliveryTypes"] = "All types",
        ["Products.Empty"] = "No products found",
        ["Products.SortBy"] = "Sort by",
        ["Products.SortNewest"] = "Newest",
        ["Products.SortPrice"] = "Price",
        ["Products.SortPopular"] = "Most popular",
        ["Products.Add"] = "List product",

        // ProductForm
        ["ProductForm.Title"] = "List new product",
        ["ProductForm.EditTitle"] = "Edit product",
        ["ProductForm.Name"] = "Product name",
        ["ProductForm.Category"] = "Category",
        ["ProductForm.Description"] = "Description",
        ["ProductForm.Price"] = "Price (BTC)",
        ["ProductForm.Delivery"] = "Delivery type",
        ["ProductForm.DeliveryPhysical"] = "Physical delivery",
        ["ProductForm.DeliveryDigital"] = "Digital delivery",
        ["ProductForm.DeliveryAgent"] = "Delivery agent",
        ["ProductForm.Images"] = "Images",
        ["ProductForm.Create"] = "List",
        ["ProductForm.Save"] = "Save",
        ["ProductForm.Cancel"] = "Cancel",
        ["ProductForm.Error.NameRequired"] = "Name required",
        ["ProductForm.Error.PriceRequired"] = "Price required",
        ["ProductForm.Error.CategoryRequired"] = "Category required",
        ["ProductForm.Error.PriceInvalid"] = "Invalid price",
        ["ProductForm.Success"] = "Product listed successfully",
        ["ProductForm.UpdateSuccess"] = "Product updated successfully",

        // Marketplace
        ["Marketplace.Title"] = "Marketplace",
        ["Marketplace.Subtitle"] = "Buy and sell securely",
        ["Marketplace.Featured"] = "Featured",
        ["Marketplace.Recent"] = "Recent",
        ["Marketplace.MyListings"] = "My listings",
        ["Marketplace.MyPurchases"] = "My purchases",
        ["Marketplace.MySales"] = "My sales",

        // Payment flow (EventPayment page + components)
        ["Payment.PageTitle"] = "Payment",
        ["Payment.Loading"] = "Loading…",
        ["Payment.ConfirmationNotFound"] = "Confirmation not found.",
        ["Payment.Confirmed"] = "Payment confirmed",
        ["Payment.ConfirmedFor"] = "Payment of {0} has been confirmed.",
        ["Payment.BackToMatch"] = "Back to match",
        ["Payment.AdminReview"] = "Payment review — {0}",
        ["Payment.ProofSentAt"] = "Proof sent at {0}",
        ["Payment.ProofAlt"] = "Pix proof",
        ["Payment.ErrorConfirm"] = "Error confirming payment. Try again.",
        ["Payment.ConfirmPaymentFor"] = "Confirm payment of {0}?",
        ["Payment.ConfirmPayment"] = "Confirm payment",
        ["Payment.YesConfirm"] = "Yes, confirm",
        ["Payment.NoProofSent"] = "Player has not sent proof yet.",
        ["Payment.MarkAsPaidFor"] = "Mark {0} as paid?",
        ["Payment.MarkAsPaid"] = "Mark as paid",
        ["Payment.Player"] = "Player",
        ["Payment.GenerateQrError"] = "Could not generate QR Code. Try again in a moment.",
        ["Payment.ProofSuccess"] = "Proof sent successfully! Redirecting...",
        ["Payment.ProofTooLarge"] = "File too large or invalid. Maximum 5 MB.",
        ["Payment.ProofError"] = "Error uploading proof. Try again.",
        ["Payment.ManualFlow"] = "Manual payment via Pix. Pay the organizer directly and send the proof.",
        ["Payment.PixDirectToOrganizer"] = "Pix directly to organizer",
        ["Payment.PixHint"] = "Scan the QR Code or copy the key and transfer R$ {0} directly. The organizer will confirm receipt.",
        ["Payment.NoPixKey"] = "The organizer has not registered a Pix key yet. Contact them directly to arrange payment.",
        ["Payment.Copied"] = "Copied!",
        ["Payment.Copy"] = "Copy",
        ["Payment.ProofTitle"] = "Payment proof",
        ["Payment.ProofSentAtShort"] = "Proof sent at {0}",
        ["Payment.UpdateProof"] = "Update proof",
        ["Payment.SendProof"] = "Send proof",
        ["Payment.Sending"] = "Sending…",
        ["Payment.ProofHint"] = "After making the Pix payment, send the proof to the organizer to confirm your payment.",
        ["Payment.AwaitingPayment"] = "Awaiting payment…",
        ["Payment.PixCopyPaste"] = "Pix Copy and Paste",
        ["Payment.CopyPixCode"] = "Copy Pix code",
        ["Payment.PaymentConfirmed"] = "Payment confirmed",
        ["Payment.ParticipationGuaranteed"] = "Your participation is guaranteed. Good game!",
        ["Payment.PaymentMethods"] = "Payment method",
        ["Payment.NoGatewayAvailable"] = "No payment gateway is available at the moment.",
        ["Payment.ComingSoon"] = "coming soon",
        ["Payment.GeneratingQr"] = "Generating QR Code…",
        ["Payment.GenerateQrWithGateway"] = "Generate QR Code ({0}) — R$ {1}",
        ["Payment.MatchValue"] = "Match value:",
        ["Payment.AppFee"] = "App fee:",
        ["Payment.GatewayFee"] = "Gateway fee:",
        ["Payment.TotalToPay"] = "Total to pay:",
        ["Payment.SummaryPlayer"] = "Player",
        ["Payment.SummaryPosition"] = "Position",
        ["Payment.SummaryGoalkeeper"] = "Goalkeeper",
        ["Payment.SummaryOutfield"] = "Outfield",
        ["Payment.SummaryAmount"] = "Amount to pay",
        ["Payment.SummaryMatchPrice"] = "Match",
        ["Payment.SummaryPlatformFee"] = "Platform fee",

        // PaymentBuy checkout panel
        ["PaymentBuy.GeneratePayment"] = "Generate payment",
        ["PaymentBuy.NoMethod"] = "No payment method available",
        ["PaymentBuy.NoMethodHint"] = "Try again in a moment or contact support.",
        ["PaymentBuy.WithIntermediary"] = "With site admin intermediary",
        ["PaymentBuy.WithoutIntermediary"] = "Without site admin intermediary",
        ["PaymentBuy.NoIntermediaryWarning"] = "Without intermediation, payment goes directly to the seller. Only proceed if you <strong>fully trust the seller</strong>. The site cannot mediate disputes for this transaction.",
        ["PaymentBuy.PaymentMethod"] = "Payment method:",
        ["PaymentBuy.SelectGateway"] = "Select gateway",
        ["PaymentBuy.GenerateAddress"] = "Generate payment address",
        ["PaymentBuy.PixCodeLabel"] = "Pix code",
        ["PaymentBuy.InvoiceAddress"] = "Invoice address",
        ["PaymentBuy.Copy"] = "Copy",
        ["PaymentBuy.CopyCode"] = "Copy code",
        ["PaymentBuy.PaidReceived"] = "Payment received",
        ["PaymentBuy.Waiting"] = "Waiting for payment…",
        ["PaymentBuy.WaitingManualPix"] = "Waiting for manual confirmation of PIX payment.",
        ["PaymentBuy.Check"] = "Check payment",
        ["PaymentBuy.PrivateKey"] = "Private key",
        ["PaymentBuy.PrivateKeyWarning"] = "Keep this key in a safe place. It will not be shown again.",
        ["PaymentBuy.LoadingProduct"] = "Loading product…",

        // Payment product summary
        ["PaymentProductSummary.Title"] = "Offer summary",
        ["PaymentProductSummary.ItemAria"] = "Item summary",
        ["PaymentProductSummary.ImageAlt"] = "Product image",
        ["PaymentProductSummary.Item"] = "Item",
        ["PaymentProductSummary.Name"] = "Name",
        ["PaymentProductSummary.Quantity"] = "Quantity",
        ["PaymentProductSummary.UnitPrice"] = "Unit price",
        ["PaymentProductSummary.TotalPrice"] = "Total price",
        ["PaymentProductSummary.Seller"] = "Seller:",

        // Payment view extra
        ["PaymentView.Rechecking"] = "Rechecking...",
        ["PaymentView.CheckingGateways"] = "Querying gateways to confirm payment...",
        ["PaymentView.Aria"] = "View payment",
        ["PaymentView.Checkout"] = "Checkout",
        ["PaymentView.OpenCheckout"] = "Open checkout on {0}",
        ["PaymentView.QrHint"] = "Scan the QR Code on the {0} website to complete the payment.",
        ["PaymentDetails.Aria"] = "Payment details",
        ["PaymentDetails.PaymentId"] = "Payment ID",
        ["PaymentDetails.PaidAt"] = "Paid at",

        // Payment history export
        ["PaymentHistory.ExportCsv"] = "Export CSV",
        ["PaymentHistory.ExportPdf"] = "Export PDF",

        // Platform fee settlement service messages (Fase F do Ciclo 27)
        ["Payment.Settlement.InvalidImageType"] = "Only JPG, PNG or WebP images are accepted.",
        ["Payment.Settlement.FileTooLarge"] = "File too large. Maximum {0} MB.",
        ["Payment.Settlement.SubmitSuccess"] = "Settlement sent successfully. Awaiting review.",
        ["Payment.Settlement.NotFound"] = "Settlement not found.",
        ["Payment.Settlement.AlreadyReviewed"] = "This settlement has already been reviewed.",
        ["Payment.Settlement.EmptyFile"] = "Empty file.",
        ["Payment.Settlement.InvalidAmount"] = "Settlement amount must be greater than zero.",
        ["Payment.Settlement.NotGroupAdmin"] = "Only a group administrator can submit the settlement.",
        ["Payment.Settlement.NotSystemAdmin"] = "Only the system administrator can confirm the settlement.",
        ["Payment.Settlement.SubmitError"] = "Error sending settlement. Please try again.",
        ["Payment.Settlement.Approved"] = "Settlement approved.",
        ["Payment.Settlement.Rejected"] = "Settlement rejected.",
        ["Payment.Settlement.NoMatchesSelected"] = "Select the matches this settlement covers.",
        ["Payment.Settlement.InvalidMatchSelection"] = "Invalid match selection for this group.",
        ["Payment.Settlement.MatchAlreadyCovered"] = "One of the selected matches is already in a submitted or approved settlement.",
        ["Payment.Settlement.AmountMismatch"] = "The settlement amount must be R$ {0}, matching the fees of the selected matches.",
    };

    /// <summary>ES-ES Spanish (Spain) strings - stub for extension</summary>
    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // PaymentBuy
        ["PaymentBuy.Title"] = "Finalizar compra",
        ["PaymentBuy.Product"] = "Producto",
        ["PaymentBuy.Price"] = "Precio",
        ["PaymentBuy.Description"] = "Descripcion",
        ["PaymentBuy.Seller"] = "Vendedor",
        ["PaymentBuy.Quantity"] = "Cantidad",
        ["PaymentBuy.Total"] = "Total",
        ["PaymentBuy.Method"] = "Metodo de pago",
        ["PaymentBuy.SelectMethod"] = "Seleccione un metodo",
        ["PaymentBuy.Confirm"] = "Confirmar pago",
        ["PaymentBuy.Cancel"] = "Cancelar",
        ["PaymentBuy.Success"] = "Pago exitoso",
        ["PaymentBuy.Error"] = "Error al procesar pago",
        ["PaymentBuy.InvalidProduct"] = "Producto invalido",
        ["PaymentBuy.InvalidQuantity"] = "Cantidad invalida",
        ["PaymentBuy.InsufficientFunds"] = "Saldo insuficiente",
        ["PaymentBuy.Processing"] = "Procesando pago...",

        // PaymentHistory
        ["PaymentHistory.Title"] = "Mis pagamentos",
        ["PaymentHistory.Subtitle"] = "Rastrea tus transacciones y pagos",
        ["PaymentHistory.Aria"] = "Historial de pagos",
        ["PaymentHistory.Empty"] = "No se encontraron transacciones",
        ["PaymentHistory.EmptyHint"] = "Cuando hagas pagos, aparecerán aquí.",
        ["PaymentHistory.TabSent"] = "Enviados",
        ["PaymentHistory.TabReceived"] = "Recibidos",
        ["PaymentHistory.Date"] = "Fecha",
        ["PaymentHistory.Product"] = "Producto",
        ["PaymentHistory.Amount"] = "Monto",
        ["PaymentHistory.Status"] = "Estado",
        ["PaymentHistory.Filter.Status"] = "Estado",
        ["PaymentHistory.Filter.Product"] = "Producto...",
        ["PaymentHistory.Filter.Gateway"] = "Gateway...",
        ["PaymentHistory.Filter.AllStatus"] = "Todos los estados",
        ["PaymentHistory.AllStatuses"] = "Todos los estados",
        ["PaymentHistory.Buyer"] = "Comprador",
        ["PaymentHistory.Action"] = "Acción",
        ["PaymentHistory.View"] = "Ver",
        ["PaymentHistory.Filter.MinValue"] = "Monto mínimo",
        ["PaymentHistory.Filter.MaxValue"] = "Monto máximo",
        ["PaymentHistory.Filter.MinAmount"] = "Monto mínimo",
        ["PaymentHistory.Filter.MaxAmount"] = "Monto máximo",
        ["PaymentHistory.ConfirmedToast"] = "¡Pago {0} confirmado con éxito!",
        ["PaymentHistory.CanceledToast"] = "Pago cancelado.",
        ["PaymentHistory.ConfirmCancel"] = "¿Deseas realmente cancelar este pago?",
        ["PaymentHistory.UnknownProduct"] = "Producto desconocido",

        // PaymentView
        ["PaymentView.Title"] = "Detalles de transacción",
        ["PaymentView.Kicker"] = "Historial de facturas",
        ["PaymentView.TransactionId"] = "ID de transacción",
        ["PaymentView.Date"] = "Fecha",
        ["PaymentView.Product"] = "Producto",
        ["PaymentView.Seller"] = "Vendedor",
        ["PaymentView.Buyer"] = "Comprador",
        ["PaymentView.Amount"] = "Monto",
        ["PaymentView.Method"] = "Método de pago",
        ["PaymentView.Status"] = "Estado",
        ["PaymentView.Back"] = "Volver al historial",
        ["PaymentView.Download"] = "Descargar recibo",
        ["PaymentView.NotFound"] = "Transacción no encontrada",

        // PaymentDetails
        ["PaymentDetails.Title"] = "Detalles del pago",
        ["PaymentDetails.Summary"] = "Resumen",
        ["PaymentDetails.Subtotal"] = "Subtotal",
        ["PaymentDetails.Tax"] = "Impuesto",
        ["PaymentDetails.Fee"] = "Tarifa de procesamiento",
        ["PaymentDetails.Discount"] = "Descuento",
        ["PaymentDetails.Total"] = "Total",
        ["PaymentDetails.PaymentMethod"] = "Método de pago",
        ["PaymentDetails.TransactionId"] = "ID de transacción",
        ["PaymentDetails.Date"] = "Fecha",
        ["PaymentDetails.TimeToRefund"] = "Tiempo para reembolso",
        ["PaymentDetails.RefundPolicy"] = "Política de reembolso",
        ["PaymentDetails.Confirm"] = "Confirmar y enviar",
        ["PaymentDetails.Cancel"] = "Cancelar",

        // OrderStatus
        ["OrderStatus.Pending"] = "Pendiente",
        ["OrderStatus.Confirmed"] = "Confirmado",
        ["OrderStatus.Processing"] = "Procesando",
        ["OrderStatus.Shipped"] = "Enviado",
        ["OrderStatus.Delivered"] = "Entregado",
        ["OrderStatus.Cancelled"] = "Cancelado",
        ["OrderStatus.Refunded"] = "Reembolsado",
        ["OrderStatus.Failed"] = "Fallo de pago",
        ["OrderStatus.Disputed"] = "Disputado",
        ["OrderStatus.OnHold"] = "En espera",
        ["OrderStatus.PartiallyShipped"] = "Parcialmente enviado",
        ["OrderStatus.WaitingForPayment"] = "Esperando pago",
        ["OrderStatus.ReviewRequired"] = "Revisión requerida",

        // Products (marketplace product strings)
        ["Products.Title"] = "Productos",
        ["Products.Search"] = "Buscar productos...",
        ["Products.Filter.Category"] = "Categoria",
        ["Products.Filter.Price"] = "Precio",
        ["Products.Filter.Seller"] = "Vendedor",
        ["Products.Filter.Delivery"] = "Tipo de entrega",
        ["Products.AllCategories"] = "Todas las categorias",
        ["Products.Physical"] = "Entrega fisica",
        ["Products.Digital"] = "Entrega digital",
        ["Products.AllDeliveryTypes"] = "Todos los tipos",
        ["Products.Empty"] = "No se encontraron productos",
        ["Products.SortBy"] = "Ordenar por",
        ["Products.SortNewest"] = "Mas recientes",
        ["Products.SortPrice"] = "Precio",
        ["Products.SortPopular"] = "Mas populares",
        ["Products.Add"] = "Anunciar producto",

        // ProductForm
        ["ProductForm.Title"] = "Anunciar nuevo producto",
        ["ProductForm.EditTitle"] = "Editar producto",
        ["ProductForm.Name"] = "Nombre del producto",
        ["ProductForm.Category"] = "Categoria",
        ["ProductForm.Description"] = "Descripcion",
        ["ProductForm.Price"] = "Precio (BTC)",
        ["ProductForm.Delivery"] = "Tipo de entrega",
        ["ProductForm.DeliveryPhysical"] = "Entrega fisica",
        ["ProductForm.DeliveryDigital"] = "Entrega digital",
        ["ProductForm.DeliveryAgent"] = "Agente de entrega",
        ["ProductForm.Images"] = "Imagenes",
        ["ProductForm.Create"] = "Anunciar",
        ["ProductForm.Save"] = "Guardar",
        ["ProductForm.Cancel"] = "Cancelar",
        ["ProductForm.Error.NameRequired"] = "Nombre obligatorio",
        ["ProductForm.Error.PriceRequired"] = "Precio obligatorio",
        ["ProductForm.Error.CategoryRequired"] = "Categoria obligatoria",
        ["ProductForm.Error.PriceInvalid"] = "Precio invalido",
        ["ProductForm.Success"] = "Producto anunciado exitosamente",
        ["ProductForm.UpdateSuccess"] = "Producto actualizado exitosamente",

        // Marketplace
        ["Marketplace.Title"] = "Mercado",
        ["Marketplace.Subtitle"] = "Compra y vende con seguridad",
        ["Marketplace.Featured"] = "Destacado",
        ["Marketplace.Recent"] = "Recientes",
        ["Marketplace.MyListings"] = "Mis anuncios",
        ["Marketplace.MyPurchases"] = "Mis compras",
        ["Marketplace.MySales"] = "Mis ventas",

        // Payment flow (EventPayment page + components)
        ["Payment.PageTitle"] = "Pago",
        ["Payment.Loading"] = "Cargando…",
        ["Payment.ConfirmationNotFound"] = "Confirmacion no encontrada.",
        ["Payment.Confirmed"] = "Pago confirmado",
        ["Payment.ConfirmedFor"] = "Pago de {0} ha sido confirmado.",
        ["Payment.BackToMatch"] = "Volver al partido",
        ["Payment.AdminReview"] = "Revision de pago — {0}",
        ["Payment.ProofSentAt"] = "Comprobante enviado en {0}",
        ["Payment.ProofAlt"] = "Comprobante Pix",
        ["Payment.ErrorConfirm"] = "Error al confirmar pago. Intente nuevamente.",
        ["Payment.ConfirmPaymentFor"] = "Confirmar pago de {0}?",
        ["Payment.ConfirmPayment"] = "Confirmar pago",
        ["Payment.YesConfirm"] = "Si, confirmar",
        ["Payment.NoProofSent"] = "El jugador aun no ha enviado comprobante.",
        ["Payment.MarkAsPaidFor"] = "Marcar {0} como pagado?",
        ["Payment.MarkAsPaid"] = "Marcar como pagado",
        ["Payment.Player"] = "Jugador",
        ["Payment.GenerateQrError"] = "No fue posible generar el codigo QR. Intente nuevamente en un momento.",
        ["Payment.ProofSuccess"] = "Comprobante enviado con exito! Redirigiendo...",
        ["Payment.ProofTooLarge"] = "Archivo demasiado grande o invalido. Maximo 5 MB.",
        ["Payment.ProofError"] = "Error al enviar el comprobante. Intente nuevamente.",
        ["Payment.ManualFlow"] = "Pago manual via Pix. Pague directamente al organizador y envie el comprobante.",
        ["Payment.PixDirectToOrganizer"] = "Pix directo al organizador",
        ["Payment.PixHint"] = "Escanee el codigo QR o copie la clave y transfiera R$ {0} directamente. El organizador confirmara la recepcion.",
        ["Payment.NoPixKey"] = "El organizador aun no ha registrado una clave Pix. Contactelo directamente para acordar el pago.",
        ["Payment.Copied"] = "Copiado!",
        ["Payment.Copy"] = "Copiar",
        ["Payment.ProofTitle"] = "Comprobante de pago",
        ["Payment.ProofSentAtShort"] = "Comprobante enviado en {0}",
        ["Payment.UpdateProof"] = "Actualizar comprobante",
        ["Payment.SendProof"] = "Enviar comprobante",
        ["Payment.Sending"] = "Enviando…",
        ["Payment.ProofHint"] = "Despues de hacer el Pix, envie el comprobante al organizador para confirmar su pago.",
        ["Payment.AwaitingPayment"] = "Esperando pago…",
        ["Payment.PixCopyPaste"] = "Pix Copiar y Pegar",
        ["Payment.CopyPixCode"] = "Copiar codigo Pix",
        ["Payment.PaymentConfirmed"] = "Pago confirmado",
        ["Payment.ParticipationGuaranteed"] = "Su participacion esta garantizada. Buen partido!",
        ["Payment.PaymentMethods"] = "Forma de pago",
        ["Payment.NoGatewayAvailable"] = "Ninguna pasarela de pago esta disponible en este momento.",
        ["Payment.ComingSoon"] = "proximamente",
        ["Payment.GeneratingQr"] = "Generando codigo QR…",
        ["Payment.GenerateQrWithGateway"] = "Generar codigo QR ({0}) — R$ {1}",
        ["Payment.MatchValue"] = "Valor del partido:",
        ["Payment.AppFee"] = "Comision de la app:",
        ["Payment.GatewayFee"] = "Comision de la pasarela:",
        ["Payment.TotalToPay"] = "Total a pagar:",
        ["Payment.SummaryPlayer"] = "Jugador",
        ["Payment.SummaryPosition"] = "Posicion",
        ["Payment.SummaryGoalkeeper"] = "Portero",
        ["Payment.SummaryOutfield"] = "Campo",
        ["Payment.SummaryAmount"] = "Monto a pagar",
        ["Payment.SummaryMatchPrice"] = "Partido",
        ["Payment.SummaryPlatformFee"] = "Tasa de la plataforma",

        // PaymentBuy checkout panel
        ["PaymentBuy.GeneratePayment"] = "Generar pago",
        ["PaymentBuy.NoMethod"] = "Ningun metodo de pago disponible",
        ["PaymentBuy.NoMethodHint"] = "Intente nuevamente en un momento o contacte soporte.",
        ["PaymentBuy.WithIntermediary"] = "Con intermediacion del ADM del sitio",
        ["PaymentBuy.WithoutIntermediary"] = "Sin intermediacion del ADM del sitio",
        ["PaymentBuy.NoIntermediaryWarning"] = "Sin intermediacion, el pago va directamente al vendedor. Solo continue si <strong>confia totalmente en el vendedor</strong>. El sitio no podra mediar disputas en esta transaccion.",
        ["PaymentBuy.PaymentMethod"] = "Forma de pago:",
        ["PaymentBuy.SelectGateway"] = "Seleccionar gateway",
        ["PaymentBuy.GenerateAddress"] = "Generar direccion de pago",
        ["PaymentBuy.PixCodeLabel"] = "Codigo Pix",
        ["PaymentBuy.InvoiceAddress"] = "Direccion de factura",
        ["PaymentBuy.Copy"] = "Copiar",
        ["PaymentBuy.CopyCode"] = "Copiar codigo",
        ["PaymentBuy.PaidReceived"] = "Pago recibido",
        ["PaymentBuy.Waiting"] = "Esperando pago…",
        ["PaymentBuy.WaitingManualPix"] = "Esperando confirmacion manual del pago PIX.",
        ["PaymentBuy.Check"] = "Verificar pago",
        ["PaymentBuy.PrivateKey"] = "Clave privada",
        ["PaymentBuy.PrivateKeyWarning"] = "Guarde esta clave en un lugar seguro. No se mostrara nuevamente.",
        ["PaymentBuy.LoadingProduct"] = "Cargando producto…",

        // Payment product summary
        ["PaymentProductSummary.Title"] = "Resumen de oferta",
        ["PaymentProductSummary.ItemAria"] = "Resumen del item",
        ["PaymentProductSummary.ImageAlt"] = "Imagen del producto",
        ["PaymentProductSummary.Item"] = "Item",
        ["PaymentProductSummary.Name"] = "Nombre",
        ["PaymentProductSummary.Quantity"] = "Cantidad",
        ["PaymentProductSummary.UnitPrice"] = "Precio unitario",
        ["PaymentProductSummary.TotalPrice"] = "Precio total",
        ["PaymentProductSummary.Seller"] = "Vendedor:",

        // Payment view extra
        ["PaymentView.Rechecking"] = "Reconfirmando...",
        ["PaymentView.CheckingGateways"] = "Consultando gateways para confirmar el pago...",
        ["PaymentView.Aria"] = "Ver pago",
        ["PaymentView.Checkout"] = "Checkout",
        ["PaymentView.OpenCheckout"] = "Abrir checkout en {0}",
        ["PaymentView.QrHint"] = "Escanee el codigo QR en el sitio de {0} para completar el pago.",
        ["PaymentDetails.Aria"] = "Detalles del pago",
        ["PaymentDetails.PaymentId"] = "ID del pago",
        ["PaymentDetails.PaidAt"] = "Pagado en",

        // Payment history export
        ["PaymentHistory.ExportCsv"] = "Exportar CSV",
        ["PaymentHistory.ExportPdf"] = "Exportar PDF",

        // Platform fee settlement service messages (Fase F do Ciclo 27)
        ["Payment.Settlement.InvalidImageType"] = "Solo se aceptan imagenes JPG, PNG o WebP.",
        ["Payment.Settlement.FileTooLarge"] = "Archivo demasiado grande. Maximo {0} MB.",
        ["Payment.Settlement.SubmitSuccess"] = "Liquidacion enviada con exito. Esperando revision.",
        ["Payment.Settlement.NotFound"] = "Liquidacion no encontrada.",
        ["Payment.Settlement.AlreadyReviewed"] = "Esta liquidacion ya fue revisada.",
        ["Payment.Settlement.EmptyFile"] = "Archivo vacio.",
        ["Payment.Settlement.InvalidAmount"] = "El valor de la liquidacion debe ser mayor que cero.",
        ["Payment.Settlement.NotGroupAdmin"] = "Solo un administrador del grupo puede enviar la liquidacion.",
        ["Payment.Settlement.NotSystemAdmin"] = "Solo el administrador del sistema puede confirmar la liquidacion.",
        ["Payment.Settlement.SubmitError"] = "Error al enviar la liquidacion. Intentalo de nuevo.",
        ["Payment.Settlement.Approved"] = "Liquidacion aprobada.",
        ["Payment.Settlement.Rejected"] = "Liquidacion rechazada.",
        ["Payment.Settlement.NoMatchesSelected"] = "Selecciona los partidos que cubre esta liquidacion.",
        ["Payment.Settlement.InvalidMatchSelection"] = "Seleccion de partidos invalida para este grupo.",
        ["Payment.Settlement.MatchAlreadyCovered"] = "Uno de los partidos seleccionados ya esta en una liquidacion enviada o aprobada.",
        ["Payment.Settlement.AmountMismatch"] = "El valor de la liquidacion debe ser R$ {0}, igual a la suma de las tasas de los partidos seleccionados.",
    };

    /// <summary>Get combined dictionary for all languages</summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
