namespace Confirmai.Services.Core.UiText;

/// <summary>
/// Utility and miscellaneous text strings.
/// Coverage: Cookie, About, Contact, Integration, Settings, Help, Mailbox, Widget, Common, Product forms
/// </summary>
internal static class UtilityTexts
{
    public static IReadOnlyDictionary<string, string> PtBr => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Cookie.Banner.Aria"] = "Consentimento de cookies",
        ["Cookie.Banner.Title"] = "Uso de cookies",
        ["Cookie.Banner.Description"] = "Usamos cookies essenciais para funcionamento e opcionais para analise de uso. Voce pode aceitar tudo ou personalizar.",
        ["Cookie.Banner.AcceptAll"] = "Aceitar tudo",
        ["Cookie.Banner.RejectOptional"] = "Recusar opcionais",
        ["Cookie.Banner.Customize"] = "Personalizar",
        ["Cookie.Modal.Aria"] = "Preferencias de cookies",
        ["Cookie.Modal.Title"] = "Preferencias de cookies",
        ["Cookie.Modal.Description"] = "Escolha quais tipos de cookies voce permite. Os essenciais sao sempre ativos.",
        ["Cookie.Category.Necessary"] = "Cookies essenciais",
        ["Cookie.Category.NecessaryDesc"] = "Necessarios para autenticacao, seguranca e funcionamento basico da plataforma.",
        ["Cookie.Category.Analytics"] = "Cookies de analise",
        ["Cookie.Category.AnalyticsDesc"] = "Ajudam a entender uso da plataforma para melhorar experiencia e performance.",
        ["Cookie.Modal.SavePreferences"] = "Salvar preferencias",

        ["About.PageTitle"] = "Sobre - Confirmai",
        ["About.Kicker"] = "Infraestrutura de comercio com Bitcoin",
        ["About.Hero"] = "Plataforma focada em transacoes rastreaveis, auditoria operacional e evolucao continua por backlog tecnico.",
        ["About.Aria.Pillars"] = "Pilares do projeto",
        ["About.Security.Title"] = "Seguranca como base",
        ["About.Security.Text"] = "Controles de autenticacao, lockout, confirmacao de e-mail e validacoes criticas para reduzir risco em fluxos sensiveis.",
        ["About.Audit.Title"] = "Auditoria real",
        ["About.Audit.Text"] = "Logs administrativos e trilhas de mudanca para permitir investigacao de incidentes, revisao de decisoes e conformidade operacional.",
        ["About.Incremental.Title"] = "Operacao incremental",
        ["About.Incremental.Text"] = "Entregas evolutivas com validacao constante em testes e ajustes praticos guiados por comportamento real em producao local.",
        ["About.Roadmap.Title"] = "Visao do roadmap",
        ["About.Roadmap.Text"] = "O projeto prioriza robustez do nucleo de pagamentos e gestao administrativa, seguido por refinamento de UX e expansao de observabilidade.",

        ["Contact.PageTitle"] = "Contato - Confirmai",
        ["Contact.Kicker"] = "Suporte e colaboracao",
        ["Contact.Title"] = "Contato",
        ["Contact.Hero"] = "Para incidentes, duvidas tecnicas e propostas de melhoria, use os canais abaixo com o maximo de contexto possivel.",
        ["Contact.Aria.Channels"] = "Canais de contato",
        ["Contact.Email.Title"] = "E-mail",
        ["Contact.Email.Text"] = "Canal principal para suporte operacional e duvidas de fluxo.",
        ["Contact.GitHub.Title"] = "GitHub",
        ["Contact.GitHub.Highlight"] = "Issues e discussoes do repositorio",
        ["Contact.GitHub.Text"] = "Use para reportes reproduziveis, propostas de melhoria e rastreio de evolucao.",
        ["Contact.Sla.Title"] = "SLA atual",
        ["Contact.Sla.Highlight"] = "Ate 2 dias uteis",
        ["Contact.Sla.Text"] = "Priorizacao por severidade e impacto no fluxo de pagamentos.",
        ["Contact.Aria.Checklist"] = "Checklist de abertura de chamado",
        ["Contact.Checklist.Title"] = "Checklist para abrir chamado",
        ["Contact.Checklist.Item1"] = "ID do pagamento, quando aplicavel",
        ["Contact.Checklist.Item2"] = "Descricao objetiva do problema e horario aproximado",
        ["Contact.Checklist.Item3"] = "Navegador, ambiente e captura de tela/evidencia",
        ["Contact.Checklist.Item4"] = "Passos para reproduzir o comportamento",

        ["Mailbox.Title"] = "Caixa Postal",
        ["Mailbox.PageTitle"] = "Caixa postal",
        ["Mailbox.Aria"] = "Caixa postal",
        ["Mailbox.MyProfile"] = "Meu perfil",
        ["Mailbox.Loading"] = "Carregando mensagens...",
        ["Mailbox.FilterSearch"] = "Buscar na mensagem",
        ["Mailbox.FilterPageSize"] = "Conversas por pagina",
        ["Mailbox.FilterUnreadOnly"] = "Somente com nao lidas",
        ["Mailbox.FilterApply"] = "Aplicar filtros",
        ["Mailbox.FilterClear"] = "Limpar",
        ["Mailbox.TabActive"] = "Conversas",
        ["Mailbox.TabArchived"] = "Arquivadas",
        ["Mailbox.NoConversations"] = "Nenhuma conversa encontrada.",
        ["Mailbox.ConversationInProgress"] = "Conversa em andamento",
        ["Mailbox.Unread"] = "nao lida(s)",
        ["Mailbox.MarkAsRead"] = "Marcar lida",
        ["Mailbox.Archive"] = "Arquivar",
        ["Mailbox.Unarchive"] = "Desarquivar",
        ["Mailbox.PrevPage"] = "Anterior",
        ["Mailbox.NextPage"] = "Proxima",
        ["Mailbox.SelectConversation"] = "Selecione uma conversa para abrir o painel de leitura.",
        ["Mailbox.ThreadKickerOrder"] = "Conversa do",
        ["Mailbox.ThreadKickerUser"] = "Conversa com",
        ["Mailbox.ThreadMessages"] = "mensagem(ns)",
        ["Mailbox.ThreadLoading"] = "Carregando conversa...",
        ["Mailbox.ThreadEmpty"] = "Nenhuma mensagem nesta conversa.",
        ["Mailbox.ComposerLabel"] = "Enviar mensagem",
        ["Mailbox.Sending"] = "Enviando...",
        ["Mailbox.Send"] = "Enviar mensagem",
        ["Mailbox.NoContent"] = "Sem conteudo.",
        ["Mailbox.Yesterday"] = "ontem",
        ["Mailbox.Now"] = "agora",

        ["Integration.Title"] = "Integracao do Servidor via API",
        ["Integration.Subtitle"] = "Conecte seu servidor OpenTibia ao marketplace em poucos minutos",

        ["ProductForm.NewTitle"] = "Novo produto",
        ["ProductForm.EditTitle"] = "Editar produto",
        ["ProductForm.Subtitle"] = "Crie e atualize seus produtos em uma interface padronizada.",
        ["ProductForm.Aria"] = "Formulario de produto",
        ["ProductForm.Processing"] = "Processando...",
        ["ProductForm.Price"] = "Preco",
        ["ProductForm.RequiresPhysicalDelivery"] = "Este produto requer entrega fisica",
        ["ProductForm.DigitalHint"] = "Desmarque para infoprodutos/entrega digital.",
        ["ProductForm.Image"] = "Imagem",
        ["ProductForm.ImageAlt"] = "Imagem do produto",
        ["ProductForm.LogCreated"] = "Produto criado: {0} (ID: {1})",
        ["ProductForm.LogUpdated"] = "Produto atualizado: {0} (ID: {1})",
        ["ProductForm.CreatedToast"] = "Produto criado com sucesso!",
        ["ProductForm.UpdatedToast"] = "Produto atualizado com sucesso!",

        ["Profile.Loading"] = "Carregando perfil...",
        ["Profile.NotFound"] = "Usuario nao encontrado.",
        ["Profile.Kicker"] = "Perfil publico",
        ["Profile.Subtitle"] = "Visualizacao publica com informacoes nao sensiveis do usuario.",
        ["Profile.PublicInfo"] = "Informacoes publicas",
        ["Profile.DisplayName"] = "Nome de exibicao",
        ["Profile.ProfileType"] = "Tipo de perfil",
        ["Profile.Presentation"] = "Apresentacao",
        ["Profile.Privacy"] = "Privacidade",
        ["Profile.PrivacyText"] = "Dados de conta, credenciais e informacoes administrativas nao sao exibidos publicamente.",
        ["Profile.NoSensitive"] = "Apenas dados nao sensiveis",
        ["Profile.UserType"] = "Usuario",
        ["Profile.PresentationText"] = "Perfil ativo na plataforma para operacoes de compra e venda.",

        ["DeliveryProfile.Loading"] = "Carregando entregador...",
        ["DeliveryProfile.NotFound"] = "Entregador nao encontrado.",
        ["DeliveryProfile.Subtitle"] = "Visualizacao publica do entregador com dados operacionais nao sensiveis.",
        ["DeliveryProfile.AverageLeadTime"] = "Tempo medio de entrega",
        ["DeliveryProfile.OperationalStatus"] = "Status operacional",
        ["DeliveryProfile.Unavailable"] = "Indisponivel",
        ["DeliveryProfile.PrivacyText"] = "Apenas dados operacionais sao exibidos no perfil publico do entregador.",
        ["DeliveryProfile.NoSensitive"] = "Sem dados sensiveis",

        ["Common.Filter"] = "Filtrar",
        ["Common.Clear"] = "Limpar",
        ["Common.Name"] = "Nome",
        ["Common.Previous"] = "Anterior",
        ["Common.Next"] = "Proxima",
        ["Common.Page"] = "Pagina",
        ["Common.Of"] = "de",
        ["Common.Loading"] = "Carregando...",
        ["Common.Email"] = "Email",
        ["Common.Description"] = "Descricao",
        ["Common.Seller"] = "Vendedor",
        ["Common.Buyer"] = "Comprador",
        ["Common.Buy"] = "Comprar",
        ["Common.Status"] = "Status",
        ["Common.Value"] = "Valor",
        ["Common.Address"] = "Endereco",
        ["Common.Date"] = "Data",
        ["Common.Gateway"] = "Gateway",
        ["Common.Actions"] = "Acoes",
        ["Common.Paid"] = "Pago",
        ["Common.Pending"] = "Pendente",
        ["Common.View"] = "Visualizar",
        ["Common.Edit"] = "Editar",
        ["Common.Save"] = "Salvar",
        ["Common.Cancel"] = "Cancelar",
        ["Common.Details"] = "Detalhes",
        ["Common.Back"] = "Voltar",
        ["Common.Yes"] = "Sim",
        ["Common.No"] = "Nao",
        ["Common.ToBeDefined"] = "A definir",

        ["Widget.PaymentMethods.Title"] = "formas de pagamento",
        ["Widget.PaymentMethods.Loading"] = "Carregando metodos ativos...",
        ["Widget.PaymentMethods.Empty"] = "Nenhuma forma de pagamento ativa no painel admin.",
    };

    public static IReadOnlyDictionary<string, string> EnUs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Cookie.Banner.Aria"] = "Cookie consent",
        ["Cookie.Banner.Title"] = "Cookie usage",
        ["Cookie.Banner.Description"] = "We use essential cookies for core functionality and optional cookies for analytics. You can accept all or customize.",
        ["Cookie.Banner.AcceptAll"] = "Accept all",
        ["Cookie.Banner.RejectOptional"] = "Reject optional",
        ["Cookie.Banner.Customize"] = "Customize",
        ["Cookie.Modal.Aria"] = "Cookie preferences",
        ["Cookie.Modal.Title"] = "Cookie preferences",
        ["Cookie.Modal.Description"] = "Choose which cookie categories you allow. Essential cookies are always active.",
        ["Cookie.Category.Necessary"] = "Essential cookies",
        ["Cookie.Category.NecessaryDesc"] = "Required for authentication, security, and core platform behavior.",
        ["Cookie.Category.Analytics"] = "Analytics cookies",
        ["Cookie.Category.AnalyticsDesc"] = "Help us understand platform usage to improve experience and performance.",
        ["Cookie.Modal.SavePreferences"] = "Save preferences",

        ["About.PageTitle"] = "About - Confirmai",
        ["About.Kicker"] = "Bitcoin commerce infrastructure",
        ["About.Hero"] = "Platform focused on traceable transactions, operational auditing, and continuous evolution through a technical backlog.",
        ["About.Aria.Pillars"] = "Project pillars",
        ["About.Security.Title"] = "Security as a foundation",
        ["About.Security.Text"] = "Authentication controls, lockout, email confirmation and critical validations to reduce risk in sensitive flows.",
        ["About.Audit.Title"] = "Real auditability",
        ["About.Audit.Text"] = "Administrative logs and change trails to support incident investigation, decision review and operational compliance.",
        ["About.Incremental.Title"] = "Incremental operation",
        ["About.Incremental.Text"] = "Incremental deliveries with continuous test validation and practical adjustments guided by real behavior in local production.",
        ["About.Roadmap.Title"] = "Roadmap vision",
        ["About.Roadmap.Text"] = "The project prioritizes payment-core robustness and administrative management, followed by UX refinement and observability expansion.",

        ["Contact.PageTitle"] = "Contact - Confirmai",
        ["Contact.Kicker"] = "Support and collaboration",
        ["Contact.Title"] = "Contact",
        ["Contact.Hero"] = "For incidents, technical questions and improvement proposals, use the channels below with as much context as possible.",
        ["Contact.Aria.Channels"] = "Contact channels",
        ["Contact.Email.Title"] = "Email",
        ["Contact.Email.Text"] = "Main channel for operational support and flow questions.",
        ["Contact.GitHub.Title"] = "GitHub",
        ["Contact.GitHub.Highlight"] = "Repository issues and discussions",
        ["Contact.GitHub.Text"] = "Use it for reproducible reports, improvement proposals and evolution tracking.",
        ["Contact.Sla.Title"] = "Current SLA",
        ["Contact.Sla.Highlight"] = "Up to 2 business days",
        ["Contact.Sla.Text"] = "Prioritization by severity and impact on payment flows.",
        ["Contact.Aria.Checklist"] = "Ticket opening checklist",
        ["Contact.Checklist.Title"] = "Checklist to open a ticket",
        ["Contact.Checklist.Item1"] = "Payment ID, when applicable",
        ["Contact.Checklist.Item2"] = "Objective problem description and approximate time",
        ["Contact.Checklist.Item3"] = "Browser, environment, and screenshot/evidence",
        ["Contact.Checklist.Item4"] = "Steps to reproduce the behavior",

        ["Mailbox.Title"] = "Mailbox",
        ["Mailbox.PageTitle"] = "Mailbox",
        ["Mailbox.Aria"] = "Mailbox",
        ["Mailbox.MyProfile"] = "My profile",
        ["Mailbox.Loading"] = "Loading messages...",
        ["Mailbox.FilterSearch"] = "Search in messages",
        ["Mailbox.FilterPageSize"] = "Conversations per page",
        ["Mailbox.FilterUnreadOnly"] = "Unread only",
        ["Mailbox.FilterApply"] = "Apply filters",
        ["Mailbox.FilterClear"] = "Clear",
        ["Mailbox.TabActive"] = "Conversations",
        ["Mailbox.TabArchived"] = "Archived",
        ["Mailbox.NoConversations"] = "No conversations found.",
        ["Mailbox.ConversationInProgress"] = "Ongoing conversation",
        ["Mailbox.Unread"] = "unread",
        ["Mailbox.MarkAsRead"] = "Mark as read",
        ["Mailbox.Archive"] = "Archive",
        ["Mailbox.Unarchive"] = "Unarchive",
        ["Mailbox.PrevPage"] = "Previous",
        ["Mailbox.NextPage"] = "Next",
        ["Mailbox.SelectConversation"] = "Select a conversation to open the reading pane.",
        ["Mailbox.ThreadKickerOrder"] = "Conversation for",
        ["Mailbox.ThreadKickerUser"] = "Conversation with",
        ["Mailbox.ThreadMessages"] = "message(s)",
        ["Mailbox.ThreadLoading"] = "Loading conversation...",
        ["Mailbox.ThreadEmpty"] = "No messages in this conversation.",
        ["Mailbox.ComposerLabel"] = "Send message",
        ["Mailbox.Sending"] = "Sending...",
        ["Mailbox.Send"] = "Send message",
        ["Mailbox.NoContent"] = "No content.",
        ["Mailbox.Yesterday"] = "yesterday",
        ["Mailbox.Now"] = "now",

        ["Integration.Title"] = "Server Integration via API",
        ["Integration.Subtitle"] = "Connect your OpenTibia server to the marketplace in minutes",

        ["ProductForm.NewTitle"] = "New Product",
        ["ProductForm.EditTitle"] = "Edit Product",
        ["ProductForm.Subtitle"] = "Create and update your products in a standardized interface.",
        ["ProductForm.Aria"] = "Product form",
        ["ProductForm.Processing"] = "Processing...",
        ["ProductForm.Price"] = "Price",
        ["ProductForm.RequiresPhysicalDelivery"] = "This product requires physical delivery",
        ["ProductForm.DigitalHint"] = "Uncheck for infoproducts/digital delivery.",
        ["ProductForm.Image"] = "Image",
        ["ProductForm.ImageAlt"] = "Product image",
        ["ProductForm.LogCreated"] = "Product created: {0} (ID: {1})",
        ["ProductForm.LogUpdated"] = "Product updated: {0} (ID: {1})",
        ["ProductForm.CreatedToast"] = "Product created successfully!",
        ["ProductForm.UpdatedToast"] = "Product updated successfully!",

        ["Profile.Loading"] = "Loading profile...",
        ["Profile.NotFound"] = "User not found.",
        ["Profile.Kicker"] = "Public profile",
        ["Profile.Subtitle"] = "Public view with non-sensitive user information.",
        ["Profile.PublicInfo"] = "Public information",
        ["Profile.DisplayName"] = "Display name",
        ["Profile.ProfileType"] = "Profile type",
        ["Profile.Presentation"] = "Presentation",
        ["Profile.Privacy"] = "Privacy",
        ["Profile.PrivacyText"] = "Account data, credentials, and administrative information are not publicly displayed.",
        ["Profile.NoSensitive"] = "Only non-sensitive data",
        ["Profile.UserType"] = "User",
        ["Profile.PresentationText"] = "Active profile on the platform for buying and selling operations.",

        ["DeliveryProfile.Loading"] = "Loading delivery agent...",
        ["DeliveryProfile.NotFound"] = "Delivery agent not found.",
        ["DeliveryProfile.Subtitle"] = "Public delivery-agent view with non-sensitive operational data.",
        ["DeliveryProfile.AverageLeadTime"] = "Average lead time",
        ["DeliveryProfile.OperationalStatus"] = "Operational status",
        ["DeliveryProfile.Unavailable"] = "Unavailable",
        ["DeliveryProfile.PrivacyText"] = "Only operational data is displayed in the delivery agent public profile.",
        ["DeliveryProfile.NoSensitive"] = "No sensitive data",

        ["Common.Filter"] = "Filter",
        ["Common.Clear"] = "Clear",
        ["Common.Name"] = "Name",
        ["Common.Previous"] = "Previous",
        ["Common.Next"] = "Next",
        ["Common.Page"] = "Page",
        ["Common.Of"] = "of",
        ["Common.Loading"] = "Loading...",
        ["Common.Email"] = "Email",
        ["Common.Description"] = "Description",
        ["Common.Seller"] = "Seller",
        ["Common.Buyer"] = "Buyer",
        ["Common.Buy"] = "Buy",
        ["Common.Status"] = "Status",
        ["Common.Value"] = "Value",
        ["Common.Address"] = "Address",
        ["Common.Date"] = "Date",
        ["Common.Gateway"] = "Gateway",
        ["Common.Actions"] = "Actions",
        ["Common.Paid"] = "Paid",
        ["Common.Pending"] = "Pending",
        ["Common.View"] = "View",
        ["Common.Edit"] = "Edit",
        ["Common.Save"] = "Save",
        ["Common.Cancel"] = "Cancel",
        ["Common.Details"] = "Details",
        ["Common.Back"] = "Back",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.ToBeDefined"] = "To be defined",

        ["Widget.PaymentMethods.Title"] = "payment methods",
        ["Widget.PaymentMethods.Loading"] = "Loading active methods...",
        ["Widget.PaymentMethods.Empty"] = "No active payment methods in the admin panel.",
    };

    public static IReadOnlyDictionary<string, string> EsEs => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Cookie.Banner.Aria"] = "Consentimiento de cookies",
        ["Cookie.Banner.Title"] = "Uso de cookies",
        ["Cookie.Banner.Description"] = "Usamos cookies esenciales para el funcionamiento y opcionales para analitica. Puedes aceptar todo o personalizar.",
        ["Cookie.Banner.AcceptAll"] = "Aceptar todo",
        ["Cookie.Banner.RejectOptional"] = "Rechazar opcionales",
        ["Cookie.Banner.Customize"] = "Personalizar",
        ["Cookie.Modal.Aria"] = "Preferencias de cookies",
        ["Cookie.Modal.Title"] = "Preferencias de cookies",
        ["Cookie.Modal.Description"] = "Elige que categorias de cookies permites. Las esenciales siempre estan activas.",
        ["Cookie.Category.Necessary"] = "Cookies esenciales",
        ["Cookie.Category.NecessaryDesc"] = "Necesarias para autenticacion, seguridad y funcionamiento basico de la plataforma.",
        ["Cookie.Category.Analytics"] = "Cookies de analitica",
        ["Cookie.Category.AnalyticsDesc"] = "Ayudan a entender el uso de la plataforma para mejorar experiencia y rendimiento.",
        ["Cookie.Modal.SavePreferences"] = "Guardar preferencias",

        ["About.PageTitle"] = "Acerca de - Confirmai",
        ["About.Kicker"] = "Infraestructura de comercio con Bitcoin",
        ["About.Hero"] = "Plataforma enfocada en transacciones trazables, auditoría operacional y evolución continua a través de un backlog tecnico.",
        ["About.Aria.Pillars"] = "Pilares del proyecto",
        ["About.Security.Title"] = "Seguridad como fundamento",
        ["About.Security.Text"] = "Controles de autenticacion, bloqueo, confirmacion de correo electronico y validaciones criticas para reducir riesgos en flujos sensibles.",
        ["About.Audit.Title"] = "Auditoria real",
        ["About.Audit.Text"] = "Registros administrativos y rastros de cambios para apoyar investigacion de incidentes, revision de decisiones y cumplimiento operacional.",
        ["About.Incremental.Title"] = "Operacion incremental",
        ["About.Incremental.Text"] = "Entregas incrementales con validacion continua de pruebas y ajustes practicos guiados por el comportamiento real en produccion local.",
        ["About.Roadmap.Title"] = "Vision del roadmap",
        ["About.Roadmap.Text"] = "El proyecto prioriza la robustez del nucleo de pagos y la gestion administrativa, seguida del refinamiento de UX y expansion de observabilidad.",

        ["Contact.PageTitle"] = "Contacto - Confirmai",
        ["Contact.Kicker"] = "Soporte y colaboracion",
        ["Contact.Title"] = "Contacto",
        ["Contact.Hero"] = "Para incidentes, preguntas tecnicas y propuestas de mejora, utiliza los canales a continuacion con el maximo contexto posible.",
        ["Contact.Aria.Channels"] = "Canales de contacto",
        ["Contact.Email.Title"] = "Correo electronico",
        ["Contact.Email.Text"] = "Canal principal para soporte operacional y preguntas de flujo.",
        ["Contact.GitHub.Title"] = "GitHub",
        ["Contact.GitHub.Highlight"] = "Problemas y discusiones del repositorio",
        ["Contact.GitHub.Text"] = "Utiliza para reportes reproducibles, propuestas de mejora y seguimiento de evolucion.",
        ["Contact.Sla.Title"] = "SLA actual",
        ["Contact.Sla.Highlight"] = "Hasta 2 dias habiles",
        ["Contact.Sla.Text"] = "Priorizacion por severidad e impacto en los flujos de pago.",
        ["Contact.Aria.Checklist"] = "Lista de verificacion para abrir ticket",
        ["Contact.Checklist.Title"] = "Lista de verificacion para abrir un ticket",
        ["Contact.Checklist.Item1"] = "ID de pago, cuando sea aplicable",
        ["Contact.Checklist.Item2"] = "Descripcion objetiva del problema y tiempo aproximado",
        ["Contact.Checklist.Item3"] = "Navegador, ambiente, y captura de pantalla/evidencia",
        ["Contact.Checklist.Item4"] = "Pasos para reproducir el comportamiento",

        ["Mailbox.Title"] = "Bandeja de entrada",
        ["Mailbox.PageTitle"] = "Bandeja de entrada",
        ["Mailbox.Aria"] = "Bandeja de entrada",
        ["Mailbox.MyProfile"] = "Mi perfil",
        ["Mailbox.Loading"] = "Cargando mensajes...",
        ["Mailbox.FilterSearch"] = "Buscar en mensajes",
        ["Mailbox.FilterPageSize"] = "Conversaciones por pagina",
        ["Mailbox.FilterUnreadOnly"] = "Solo sin leer",
        ["Mailbox.FilterApply"] = "Aplicar filtros",
        ["Mailbox.FilterClear"] = "Limpiar",
        ["Mailbox.TabActive"] = "Conversaciones",
        ["Mailbox.TabArchived"] = "Archivadas",
        ["Mailbox.NoConversations"] = "No se encontraron conversaciones.",
        ["Mailbox.ConversationInProgress"] = "Conversacion en progreso",
        ["Mailbox.Unread"] = "sin leer",
        ["Mailbox.MarkAsRead"] = "Marcar como leído",
        ["Mailbox.Archive"] = "Archivar",
        ["Mailbox.Unarchive"] = "Desarchivar",
        ["Mailbox.PrevPage"] = "Anterior",
        ["Mailbox.NextPage"] = "Siguiente",
        ["Mailbox.SelectConversation"] = "Selecciona una conversacion para abrir el panel de lectura.",
        ["Mailbox.ThreadKickerOrder"] = "Conversacion para",
        ["Mailbox.ThreadKickerUser"] = "Conversacion con",
        ["Mailbox.ThreadMessages"] = "mensaje(s)",
        ["Mailbox.ThreadLoading"] = "Cargando conversacion...",
        ["Mailbox.ThreadEmpty"] = "No hay mensajes en esta conversacion.",
        ["Mailbox.ComposerLabel"] = "Enviar mensaje",
        ["Mailbox.Sending"] = "Enviando...",
        ["Mailbox.Send"] = "Enviar mensaje",
        ["Mailbox.NoContent"] = "Sin contenido.",
        ["Mailbox.Yesterday"] = "ayer",
        ["Mailbox.Now"] = "ahora",

        ["Integration.Title"] = "Integracion del servidor via API",
        ["Integration.Subtitle"] = "Conecta tu servidor OpenTibia al mercado en minutos",

        ["ProductForm.NewTitle"] = "Nuevo producto",
        ["ProductForm.EditTitle"] = "Editar producto",
        ["ProductForm.Subtitle"] = "Crea y actualiza tus productos en una interfaz estandarizada.",
        ["ProductForm.Aria"] = "Formulario de producto",
        ["ProductForm.Processing"] = "Procesando...",
        ["ProductForm.Price"] = "Precio",
        ["ProductForm.RequiresPhysicalDelivery"] = "Este producto requiere entrega fisica",
        ["ProductForm.DigitalHint"] = "Desmarque para infoproductos/entrega digital.",
        ["ProductForm.Image"] = "Imagen",
        ["ProductForm.ImageAlt"] = "Imagen del producto",
        ["ProductForm.LogCreated"] = "Producto creado: {0} (ID: {1})",
        ["ProductForm.LogUpdated"] = "Producto actualizado: {0} (ID: {1})",
        ["ProductForm.CreatedToast"] = "Producto creado exitosamente!",
        ["ProductForm.UpdatedToast"] = "Producto actualizado exitosamente!",

        ["Profile.Loading"] = "Cargando perfil...",
        ["Profile.NotFound"] = "Usuario no encontrado.",
        ["Profile.Kicker"] = "Perfil publico",
        ["Profile.Subtitle"] = "Vista publica con informacion no sensible del usuario.",
        ["Profile.PublicInfo"] = "Informacion publica",
        ["Profile.DisplayName"] = "Nombre mostrado",
        ["Profile.ProfileType"] = "Tipo de perfil",
        ["Profile.Presentation"] = "Presentacion",
        ["Profile.Privacy"] = "Privacidad",
        ["Profile.PrivacyText"] = "Los datos de la cuenta, credenciales e informacion administrativa no se muestran publicamente.",
        ["Profile.NoSensitive"] = "Solo datos no sensibles",
        ["Profile.UserType"] = "Usuario",
        ["Profile.PresentationText"] = "Perfil activo en la plataforma para operaciones de compra y venta.",

        ["DeliveryProfile.Loading"] = "Cargando agente de entrega...",
        ["DeliveryProfile.NotFound"] = "Agente de entrega no encontrado.",
        ["DeliveryProfile.Subtitle"] = "Vista publica del agente de entrega con datos operacionales no sensibles.",
        ["DeliveryProfile.AverageLeadTime"] = "Tiempo medio de entrega",
        ["DeliveryProfile.OperationalStatus"] = "Estado operacional",
        ["DeliveryProfile.Unavailable"] = "No disponible",
        ["DeliveryProfile.PrivacyText"] = "Solo los datos operacionales se muestran en el perfil publico del agente de entrega.",
        ["DeliveryProfile.NoSensitive"] = "Sin datos sensibles",

        ["Common.Filter"] = "Filtrar",
        ["Common.Clear"] = "Limpiar",
        ["Common.Name"] = "Nombre",
        ["Common.Previous"] = "Anterior",
        ["Common.Next"] = "Siguiente",
        ["Common.Page"] = "Pagina",
        ["Common.Of"] = "de",
        ["Common.Loading"] = "Cargando...",
        ["Common.Email"] = "Correo electronico",
        ["Common.Description"] = "Descripcion",
        ["Common.Seller"] = "Vendedor",
        ["Common.Buyer"] = "Comprador",
        ["Common.Buy"] = "Comprar",
        ["Common.Status"] = "Estado",
        ["Common.Value"] = "Valor",
        ["Common.Address"] = "Direccion",
        ["Common.Date"] = "Fecha",
        ["Common.Gateway"] = "Gateway",
        ["Common.Actions"] = "Acciones",
        ["Common.Paid"] = "Pagado",
        ["Common.Pending"] = "Pendiente",
        ["Common.View"] = "Ver",
        ["Common.Edit"] = "Editar",
        ["Common.Save"] = "Guardar",
        ["Common.Cancel"] = "Cancelar",
        ["Common.Details"] = "Detalles",
        ["Common.Back"] = "Atras",
        ["Common.Yes"] = "Si",
        ["Common.No"] = "No",
        ["Common.ToBeDefined"] = "A definir",

        ["Widget.PaymentMethods.Title"] = "metodos de pago",
        ["Widget.PaymentMethods.Loading"] = "Cargando metodos activos...",
        ["Widget.PaymentMethods.Empty"] = "No hay metodos de pago activos en el panel admin.",
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> GetAllTexts()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["pt-BR"] = PtBr,
            ["en-US"] = EnUs,
            ["es-ES"] = EsEs,
        };
    }
}
